ArduPilot/ardupilot_wiki

common/source/docs/common-cuav-c-rtk-9p-gps.rst, common/source/docs/common-cuav-nora-overview.rst, common/source/docs/common-gps-for-yaw.rst, common/source/docs/common-magnetic-interference.rst
=> Add C-RTK 9p to estimate yaw

common/source/docs/common-lua-scripts.rst
Small text addition to avoid that imprudent users like me run into issues like that https://github.com/ArduPilot/ardupilot/issues/15683 :)
F4's are still widely around, IMHO.
=> Lua scripts: Add note on situation for F4 autopilots

common/source/docs/common-px4flow-overview.rst
=> Corrected typo in common-px4flow-overview.rst

common/source/docs/common-lua-scripts.rst
=> Lua Script Location alt field missing

copter/source/docs/autotune.rst, plane/source/docs/qautotune-mode.rst, plane/source/docs/quadplane-vtol-tuning-process.rst
notes about QAUTOTUNE not be applicable for Tailsitter pitch and notes that yaw tune cannot loose position hold during tune
=> Add notes about QAUTOTUNE and AUTOTUNE for copter

plane/source/docs/apms-failsafe-function.rst
Correct typo in apms-failsafe-function.rst
=> Correct typo in apms-failsafe-function.rst

Sphinxsetup.sh
=> Sphinxsetup.sh: install Python

common/source/docs/common-prearm-safety-checks.rst
We do NOT want people to treat these as if they were trivial problems.
=> common: adjust advice on what do do in case of internal errors

dev/source/docs/style-guide.rst
*almost* like a FAQ...
Might help people avoiding common traps in the AP codebase - like wasteful initialisation of memory.
=> dev: add a section on various design decisions made in the ArduPilot codebase

common/source/docs/common-gps-for-yaw.rst, common/source/docs/common-gps-septentrio.rst, common/source/docs/common-positioning-landing-page.rst
Clean up of GPS for YAW listing and related GPS pages for missing references and listings of discontinued gps
=> Update RTK GPS info

common/source/docs/common-future-wiki-changes.rst
@tridge  Please verify the note is correct
=> Add rear tilt functions to upcoming features

common/source/docs/common-archived-topics.rst, copter/source/docs/archived-tricopter.rst, copter/source/docs/tricopter.rst
there was info that needed to be archived with this pages cleanup so created an archive page for it
=> removed outdated firmware revs from tricopter

common/source/docs/common-reach-rtk-receiver.rst, plane/source/docs/arming-your-plane.rst, plane/source/docs/fixed-wing-faq.rst, plane/source/docs/stall-prevention.rst, plane/source/docs/training-mode.rst
=> removed references to old firmware revs

dev/source/docs/copter-sitl-mavproxy-tutorial.rst, dev/source/docs/plane-sitlmavproxy-tutorial.rst, dev/source/docs/rover-sitlmavproxy-tutorial.rst
=> Update path for CMAC-circuit.txt

rover/source/docs/sailboat-home.rst
This adds a link to this excellent demo vid on the sailboat landing page.
https://youtu.be/kzGciG7cCBc
=> rover: sailboat: add simulator demo vid

dev/source/docs/ap-peripheral-landing-page.rst
There is additional info in readme
=> Add link to AP_Periph readme

mavproxy/source/docs/getting_started/quickstart.rst
only changes were under WINDOWs bullets....my editor is Linux and this had Windows line endings, so everything is shown changed..its not
=> Add note about Windows shortcut for starting with multiple ports

common/source/docs/common-rtf.rst
=> Ready-To-Use & Easy-To-Buy vehicles: Add Dual RC

common/source/docs/common-rtf.rst
Hopefully there'll be a few of these over the coming days.
=> RTF Update

dev/source/docs/building-setup-windows10.rst
Made some changes to the documentation for building Ardupilot on wsl. 
Provided a note in this case if the user runs into the error shown above.
THANKS !!!
=> building-setup-windows10.rst: Updated the documentation

common/source/docs/common-wiki-editing-setup.rst, common/source/docs/common-wiki-editing-submitting-changes.rst, common/source/docs/common-wiki_editing_guide.rst
I had to update my fork after downloading in order to run Sphinxsetup. I am updating the wiki to include these instructions.
Google also offers whole site translation services and I wanted to included this link to increase access to non-English speakers.
=> Instructions to update fork after cloning and added language translation option

common/source/docs/common-rtf.rst
=> Update RTF list

common/source/docs/common-understanding-altitude.rst
=> Fix minor typo

common/source/docs/common-flight-controller-wiring.rst
=> grammar mistakes

common/source/docs/common-advanced-configuration.rst, common/source/docs/common-ek3-affinity-lane-switching.rst, common/source/docs/common-flight-controller-wiring.rst, common/source/docs/common-positioning-landing-page.rst
Perhaps we should change the code to try each SERIAL port configured for GPS before giving up during initialization?
=> Add note about GPS connection ordering

common/source/docs/common-sik-telemetry-radio.rst
also add warning about interoperability of "clones"
=> update SiK radio links

common/source/docs/common-lua-scripts.rst
Thanks to @IamPete1 for helping me figure this out.
I have updated the docs to help others.
You can't do "make run" in master
=> Update "How to Add New Bindings" section in Lua Scripting docs

common/source/docs/common-minim-osd-quick-installation-guide.rst
=> Typo in common-minim-osd-quick-installation-guide

dev/source/docs/editing-the-code-with-eclipse.rst
See https://github.com/ArduPilot/ardupilot/issues/16681#issuecomment-790975227
=> dev: add warning to eclipse page that it is out-of-date

common/source/docs/common-limited-firmware.rst, common/source/docs/common-non-gps-navigation-landing-page.rst
Update the list of limited boards and features.
=> Common: Update firmware limitations

dev/source/docs/gsoc-ideas-list.rst
Corrected spelling and grammatical error
=> Updated GSoC Idea List

dev/source/docs/learning-the-ardupilot-codebase.rst
=> Dev: Learning ArduPilot Code Base add Sub to note

common/source/docs/common-lua-scripts.rst
this refers to issue https://github.com/ArduPilot/ardupilot_wiki/issues/3429
It is my first contribution to the wiki, please let me know if I need to modify anything. Thanks!
=> Include link to OEM customization here for including lua scripts during build

update.py
Based on previous PR.  This is actually a trivial change.
I'm not sure this is actually useful because only a very small subset of these parameters will be available on many devices - not all AP_Periph nodes support all of the libraries we document in here.
=> Generate ap periph paramaeters

dev/source/docs/building-setup-windows.rst, dev/source/docs/building-setup-windows10.rst
There are number of requests on discord and discuss regarding how to setup the WSL environment. I added a few things that are required for setting it up to use with SITL. I also added a few more notes on useful tools and integrations with WSL. 
I think new developers should be pointed to use WSL and not Cygwin as I have done here. 
The note I have about why one may need to compile using cygwin may need to be fixed up a bit?
I'm not sure if the note at the end about "Ground Control Station software on wsl" is true anymore?
=> Dev: Update Setup of Windows WSL Environment

common/source/docs/common-lua-scripts.rst
I think this is everything that was in #2447 plus a few more. I did not tackle the AP_Mission bindings.
=> Update Lua bindings documentation

common/source/docs/common-uavcan-escs.rst
Telemetry issue of UAVCAN ESCs was fixed [here](https://github.com/ArduPilot/ardupilot/pull/14851).
=> Remove resolved issue

dev/source/docs/building-setup-windows-cygwin.rst, dev/source/docs/building-setup-windows.rst
Dependent on ArduPilot/ardupilot#17083
=> Add section for building SITL binaries for Windows

common/source/docs/common-imu-batchsampling.rst
decided it should go im the batch sampliing doc...please review
=> 4.1: Update info on IMU rates

update.py
1) This fix the parameter Versioning for all vehicles but AP_Periph. 
2) Uses tha latest AP_Periph-Parameters.rst from atutotest server to build it in DEV wiki.
=> Fix parameter Versioning and add AP_Periph-Parameters

common/source/docs/common-rtf.rst
Add Holybro S500 V2 kits and Holybro X500 kits with pix32v5 pre-flashed with Ardupilot
=> Update common-rtf.rst with Holybro Multicopter Kits (pix32v5 Ardupilot)

plane/source/docs/automatic-tuning-with-autotune.rst
will need to expand limit cycle stuff for other vehicles...but wanted to make sure it was okay format content first
=> 4.1: Update Autotuning for plane

dev/source/docs/the-ardupilot-autotest-framework.rst
Improvements and updates to the [autotest documentation](https://ardupilot.org/dev/docs/the-ardupilot-autotest-framework.html#)
Changes include :
- Updating the autotest file structure [section](https://ardupilot.org/dev/docs/the-ardupilot-autotest-framework.html#file-structure) in accordance with the current codebase
- Typo Error Fixes
- Grammatical Fixes
Thanks !!
=> autotest-framework.rst:Updated the docs

common/source/docs/common-ac2_simple_geofence.rst
please check the existing entries for Rover...they do not agree with its param metadata...let me know what to change...thanks
=> 4.1 update FENCE_ACTIONS for Copter and Rover

copter/source/docs/traditional-helicopters.rst
first addition to the wiki as I learn and build...
=> Add TradHeli param list at a glance page

dev/source/docs/sitl-with-airsim.rst
Also splits documents into sections
I wanted to have the sections appear in the left bar, but didn't work. Any idea if it's possible?
Can be merged after https://github.com/ArduPilot/ardupilot/pull/15007, https://github.com/microsoft/AirSim/pull/2920
=> Dev: AirSim: Add info about Rangefinder

copter/source/docs/loiter-mode.rst
Correcting description of LOIT_ANG_MAX to reflect real-world and also full-param-list documentation
=> Update loiter-mode.rst to correct LOIT_ANG_MAX

plane/source/docs/quadplane-simulation.rst
The mission referred to in the instructions has moved:
https://github.com/ArduPilot/ardupilot/blob/affff0fc84a7b95dbac3ade42fff0ff97c343b8b/Tools/autotest/Generic_Missions/KSFO-VTOL.txt
=> Correct path to KSFO-VTOL mission

Sphinxsetup.sh
Hit an issue while trying to use the script on bionic WSL 1. I've narrowed the scope of when the script can be used.
=> Fix Sphinxsetup.sh script for Ubuntu 18.04 and 20.04

common/source/docs/common-brushed-motors.rst
Based on the discussion at https://discuss.ardupilot.org/t/is-my-skid-steer-configuration-correct-solved/70854, we should clarify which interface to use on motor controllers that have multiple interface options.
=> Common: Clarify motor controllers

dev/source/docs/learning-ardupilot-introduction.rst
=> Remove reference to make.inc

dev/source/docs/debugging.rst
changed dependendant to dependent
=> Wiki:dev: fixed typo

plane/source/docs/servo-functions.rst, plane/source/docs/yaw-in-plane.rst
Consolidates all the possible yaw actors into one page for plane
=> Add YAW info page

common/source/docs/common-qiotek-zealot.rst
=> Add reseller link

antennatracker/source/conf.py, ardupilot/source/conf.py, copter/source/conf.py, dev/source/conf.py, plane/source/conf.py, planner/source/conf.py, planner2/source/conf.py, rover/source/conf.py
Should resolve https://github.com/ArduPilot/ardupilot_wiki/issues/3555 if merged
=> fix: Bumps year in confs to 2021

plane/source/index.rst
remove reference to APM in plane home page
=> remove reference to APM

copter/source/docs/land-mode.rst
This is for https://github.com/ArduPilot/ardupilot/pull/16506
=> Copter: Add note about WoW to land-mode.rst

common/source/docs/common-vtx.rst
=> Update SmartAudio instructions

ardupilot/source/conf.py
Should resolve https://github.com/ArduPilot/ardupilot_wiki/issues/3553 if merged
=> fix: Removes full stop in ardupilot conf

common/source/docs/common-external-leds.rst, common/source/docs/common-imutempcal.rst
I changed GSC to GCS and IC2 to I2C.
=> common: Change the misnomer

rover/source/docs/sailboat-configure.rst, rover/source/docs/sailboat-hardware.rst, rover/source/docs/sailboat-home.rst, rover/source/docs/sailboat-modes.rst
@arikrupnik @srmainwaring I would be great full if you could have a quick look over this and make sure its mostly coherent., Thanks!
Fixes #3461
=> Rover: Sailboat: update

copter/source/docs/ac2_followme.rst
Only proper concern is that the wiki states to set the drone to 5ft in altitude but that could be too low in some cases. Everything else is just my opinion on what reads better.
=> Nitpicking

dev/source/docs/building-setup-windows-cygwin.rst
DELAY MERGE for ArduPilot/ardupilot#17083
The previous changes to this page went in before the PR was merged. That's on me for not saying that this was a delayed merge.
=> Update Cygwin package list for SITL binaries

common/source/docs/common-future-wiki-changes.rst, plane/source/docs/auto-mode.rst, plane/source/docs/qhover-mode.rst, plane/source/docs/qrtl-mode.rst, plane/source/docs/quadplane-auto-mode.rst, plane/source/docs/quadplane-flight-modes.rst, plane/source/docs/quadplane-flying.rst
re-organized a little to accommodate seamless inclusion of new QRTL/LAND behvior..updated QHOVER
=> More moves and updates for 4.1

common/source/docs/common-video-landingpage.rst
add XBLink 4G LTE Transmission System
=> add XBLink 4G LTE Transmission System

dev/source/docs/extended-kalman-filter.rst
Fixed minor grammatical errors in paragraph 3 under overview section.
=> fixed grammatical errors in overview section

common/source/docs/common-vio-tracking-camera.rst
fix https://github.com/ArduPilot/ardupilot/issues/17922
Thank @rmackay9 very much
=> Add hint to fix slow telemetry

.github/workflows/test.yml, Sphinxsetup.sh, scripts/initvagrant.sh
Alternative to https://github.com/ArduPilot/ardupilot_wiki/pull/3636
=> Sphinxsetup.sh: use most recent version of Sphinx

copter/source/docs/traditional-helicopter-aerobatic-setup.rst, copter/source/docs/traditional-helicopter-swashplate-setup.rst
just a few tweaks and an addition re acro setup
=> minor re-formatting and tweaks

dev/source/docs/unit-tests.rst
This just makes the second command a little easier to spot.
[ArduPilot Unit Tests — Dev documentation.pdf](https://github.com/ArduPilot/ardupilot_wiki/files/6870203/ArduPilot.Unit.Tests.Dev.documentation.pdf)
=> Dev: unit-tests.rst

common/source/docs/common-teraranger-one-rangefinder.rst
I would like to change the note with the actual note which is written in the Specification sheet of the sensor. 
Also I would like to include the Test Report which hopefully will give better understanding of the sensor's performances outdoors.
=> Update Note Sensor Performances Outdoors

copter/source/docs/flight-modes.rst
=> Expand flight mode information regarding position info requirements

common/source/docs/common-loading-firmware-onto-pixhawk.rst
=> Grammar pass on loading firmware page

dev/source/docs/sitl-with-webots.rst
This is related to [PR 18337](https://github.com/ArduPilot/ardupilot/pull/18337) in Ardupilot.
There is no major changes in the way SITL_WEBOTS is used. I removed paragraphs that are not needed.
=> DEV: Updating Webots2021b Documentation

common/source/docs/common-terrain-following.rst, copter/source/docs/terrain-following.rst
Updated terrain generator details
=> Terrain Update

Sphinxsetup.sh, antennatracker/source/conf.py, ardupilot/source/conf.py, copter/source/conf.py, dev/source/conf.py, mavproxy/source/conf.py, plane/source/conf.py, planner/source/conf.py, planner2/source/conf.py, rover/source/conf.py
This reverts commit d82bd556627ef368346c0934fb96fa161fa9ecc1.
We can't install a recent enough version on Python2 for the youtube
plugin to cover this
=> Revert "Remove sphinxcontrib.vimeo plugin"

common/source/docs/common-holybro-kakutef4.rst
Tested and checked on a KakuteF4 in my lab.
=> Common: Correct RC input for KakuteF4

common/source/docs/common-rpm.rst
Co-authored-by: Matt Kear <matthewnkear@gmail.com>
I am splitting your PR into a merge-able one (4.1 things) and will create an upcoming features PR for the commit on the ESC PRM Type ....I will put you as co-author on both...and close your existing one...
added a bit to the base one also...
=> update rpm page

common/source/docs/common-donation.rst
new paypal link for the ArduPilot Foundation
=> update paypal link

dev/source/docs/copter-sitl-mavproxy-tutorial.rst
Fixed a broken verbatim in testing the vehicle section.
=> fix broken verbatim

common/source/docs/common-obal-overview.rst
=> Obal style fix

common/source/docs/common-positioning-landing-page.rst
=> Update GPS landing page

plane/source/docs/assisted_fixed_wing_flight.rst, plane/source/docs/quadplane-flying.rst, plane/source/docs/quadplane-transitions.rst, plane/source/docs/quadplane_rtl.rst
no content change...just easier to find stuff
=> Re-organize Quadplane flying into multiple pages for easier reading

common/source/docs/common-telemetry-landingpage.rst
=> Update Telemetry landing page

plane/source/docs/quadplane-flying.rst
we will try this for the first entry and see if the web server has issues
=> fix TOC link on page

update.py
=> Revert #3763

update.py
Reverts ArduPilot/ardupilot_wiki#3811...duh, needed to run the new install script for #3673
=> Revert "Revert part of #3763"

update.sh
Reverts ArduPilot/ardupilot_wiki#3822
Applying and observing.
=> Revert "Testing auto build"

common/source/docs/common-archived-topics.rst, dev/source/docs/learning-ardupilot-uarts-and-the-console.rst, dev/source/docs/sitl-serial-mapping.rst, dev/source/docs/sitl-simulator-software-in-the-loop.rst, dev/source/docs/using-sitl-for-ardupilot-testing.rst
Updating the dev docs for the SITL UART options. Also consolidates the information into one less page.
=> Dev: SITL UARTS: Update and consolidate information

copter/source/docs/introduction.rst, copter/source/docs/mission-command-list.rst, dev/source/docs/ros.rst
=> corrections

common/source/docs/common-flight-controller-wiring.rst
=> add note about modes not needing gps or compass

mavproxy/source/docs/development/mavdevenvwindows.rst
This updates the list of required packages on Windows to match what we use in CI (https://github.com/ArduPilot/MAVProxy/blob/master/.github/workflows/windows_build.yml)
=> MAVProxy: Update required Windows packages

common/source/docs/common-ais.rst
=> common: Change the units

common/source/docs/common-rtf.rst, plane/source/docs/airframe-fighter-hand-throw.rst, plane/source/docs/airframe-fighter-vtol.rst, plane/source/docs/airframe-guides.rst, plane/source/docs/airframe-striver-mini-hand-throw.rst, plane/source/docs/airframe-striver-mini-vtol.rst
I have fixed build issues, edited formatting and naming, updated existing links on other pages, a little grammar editing....
=> Add MakeFlyEasy planes

common/source/docs/common-holybro-kakutef4-mini.rst, common/source/docs/common-holybro-kakutef4.rst
@andyp1per please reveiw carefully...
=> Update KakuteF4 descriptions for RCin, firmware, and Dshot

dev/source/docs/roadmap.rst
Small update related finished items.
=> Roadmap 2021: Update finished items

.gitignore
adding missing leading slashes
=> .gitignore add leading slashes

frontend/index.html
=> Frontend: Fixing typo

common/source/docs/common-choosing-a-ground-station.rst
Reference to #3215 
- Updated the qgroundcontrol forum link to point to px4.io's qgroundcontrol section
=> Common: Updated groundstation gitter links to forum links 

common/source/docs/common-lua-scripts.rst
=> Update common-lua-scripts.rst, remove duplicates

dev/source/docs/turnkey-companion-computer-solutions.rst
Add details for horizon31.com turnkey companion computer solutions, PixC4-Jetson and PixC4-Pi
=> addition of horizon31 turnkey products

copter/source/docs/loiter-mode.rst
=> Fixed : typo

frontend/index.html
This allow the browser to load images only on need.
This doesn't work on Safari for now
=> frontend: use lazyloading for images

common/source/docs/common-3d-mapping.rst
update the link for OpenDroneMap
=> update odm link

common/source/docs/common-donation.rst, common/source/docs/common-partners-program.rst
better information on partners program
=> update partners page

copter/source/docs/radio-failsafe.rst, plane/source/docs/apms-failsafe-function.rst
Added some warning about using the
=> Add warning about using receiver mode failsafes

common/source/docs/common-vio-tracking-camera.rst
Corrected a typo. 
Reference: https://github.com/IntelRealSense/librealsense/tree/master/wrappers/python/examples
=> Corrected a typo in common-vio-tracking-camera.rst

common/source/docs/common-dshot-blheli32-telemetry.rst
Clearing up the confusion about the capabilities of blheli32 current monitoring. Should be added to plane and rover too.
=> Blheli32 current monitoring capabilities

rover/source/docs/rover-steering-input-type-and-reversing-behaviour.rst
added mention omni and nothing else
=> added mention of omni and nothing else

dev/source/docs/building-setup-linux.rst
=> Dev: Environment Update to Current Arm Compilers

common/source/docs/common-esc-telem-based-notch.rst, common/source/docs/common-imu-fft.rst, common/source/docs/common-imu-notch-filtering-helicopter-setup.rst, common/source/docs/common-imu-notch-filtering.rst, common/source/docs/common-rpm-based-notch.rst, common/source/docs/common-throttle-based-notch.rst
same approach as taken in #3947...makes is easier to follow for a given setup choice...trimmed it down a bit to essentials so as not to lose a reader with too many words... addresses #3273.....next will trim down the In-Flight FFT to remove duplications
=> Re-org notch filtering into easier to follow pages

common/source/docs/common-msp-osd-overview-4.2.rst
This reverts commit 69237c188eb5389eccf515987831a8461b99ce7e.
=> Revert "fix error in screen switching and statics comments"

common/source/docs/common-future-wiki-changes.rst, common/source/docs/common-master-features.rst, plane/source/docs/soaring-speed-to-fly.rst, plane/source/docs/soaring-upcoming.rst
Documentation for new features introduced in https://github.com/ArduPilot/ardupilot/pull/17650
=> Soaring: Add airspeed management/speed-to-fly documentation.

common/source/docs/common-holybro-pix32v5.rst
=> Update Pix32V5 Wiki

common/source/docs/common-telemetry-landingpage.rst
note about falling back to mavlink 1 if no mavlink 2 data is received from the ground station.
https://github.com/ArduPilot/ardupilot/pull/19502
=> note about falling back to mavlink 1

planner/source/docs/mission-planner-overview.rst
Note MP "Donate" tab is now gone and link to DYIDrones was dead.  There was also a lingering editor's note now removed.
=> Assorted corrections.

.github/workflows/test-Windows.yml, Sphinxsetup.bat, common/source/docs/common-wiki-editing-setup.rst, update.py
This PR allows users to build the Wiki directly on Windows - no WSL or Cygwin required.
=> Allow building on Windows (direct)

dev/source/docs/setting-up-sitl-using-vagrant.rst
Corrected the spelling of 'step' and transformed that point like the second one.
=> Correct sentence that can confuse beginner.

update.py
=> update.py: use unlink/rename in place of os.replace

common/source/docs/common-packetdigital-mppt.rst, copter/source/docs/drift-mode.rst, copter/source/docs/setting-up-for-tuning.rst, dev/source/docs/editing-the-code-with-atom.rst, dev/source/docs/making-a-mavlink-wifi-bridge-using-the-raspberry-pi.rst, dev/source/docs/raspberry-pi-via-mavlink.rst, dev/source/docs/unit-tests.rst, plane/source/docs/soaring-4_1.rst, plane/source/docs/soaring.rst
update typo series
`to to` -> `to`
=> Update : fixed typo

common/source/docs/common-3d-mapping.rst, common/source/docs/common-camera-gimbal.rst, common/source/docs/common-compass-setup-advanced.rst, common/source/docs/common-electro-permanent-magnet-gripper.rst, common/source/docs/common-mission-planner-bluetooth-connectivity.rst, copter/source/docs/dji-f330-flamewheel.rst, copter/source/docs/esc-calibration.rst, mavproxy/source/docs/analysis/mavtools.rst, mavproxy/source/docs/modules/adsb.rst, mavproxy/source/docs/modules/gimbal.rst, mavproxy/source/docs/modules/terrain.rst, mavproxy/source/docs/uav_configuration/calibration.rst, mavproxy/source/docs/uav_configuration/rally.rst, mavproxy/source/docs/uav_configuration/waypoints.rst, planner2/source/docs/installation-for-linux.rst
This is a follow up to previous PR's I have submitted, rewording APM to autopilot or ArduPilot as appropriate for the context. I don't think I have modified any of the pages that are supposed to be specific to APM hardware. Will do more updates as I find the time/motivation.
=> Reword APM to autopilot/ArduPilot as appropriate

common/source/docs/common-logs.rst, update.py
Reverts ArduPilot/ardupilot_wiki#4034
=> Revert "Fix case error with log messages"

common/source/docs/common-future-wiki-changes.rst, common/source/docs/common-master-features.rst, plane/source/docs/loiter-to-qland-mode.rst
need to add stuff to wiki  changes page after merging previous PRs regarding batt fs page and quadplane flight modes page updates (reminder to me) in addition to the new page..
@IamPete1 made some assumptions on relevant params...let me know if changes are needed...
=> Add Loiter to Alt and QLAND mode to upcoming features

plane/source/docs/airframe-disco.rst, plane/source/docs/fpv-plane.rst, plane/source/docs/guide-elevon-plane.rst, plane/source/docs/guide-four-channel-plane.rst, plane/source/docs/guide-tailsitter.rst, plane/source/docs/guide-vtail-plane.rst, plane/source/docs/miniTalon-build.rst, plane/source/docs/quadplane-auto-mode.rst, plane/source/docs/quadplane-building.rst, plane/source/docs/quadplane-flying.rst, plane/source/docs/quadplane-frame-setup.rst, plane/source/docs/quadplane-transitions.rst, plane/source/docs/quadplane-vtol-tuning-process.rst, plane/source/docs/quadplane-weathervaning.rst, plane/source/docs/records.rst, plane/source/docs/servo-functions.rst, plane/source/docs/soaring-4_1.rst, plane/source/docs/soaring.rst, plane/source/docs/takeoff-landingpage.rst, plane/source/docs/takeoff-mode.rst, plane/source/docs/tuning-quickstart.rst
First of a few PR to fix typos in wiki.
=> Fix Typos #1 - Plane

Dockerfile, common/source/docs/common-Swan-K1.rst, common/source/docs/common-benewake-tfmini-lidar.rst, common/source/docs/common-can-pmu.rst, common/source/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.rst, common/source/docs/common-durandal-overview.rst, common/source/docs/common-glossary.rst, common/source/docs/common-here-plus-gps.rst, common/source/docs/common-holybro-kakutef7aio.rst, common/source/docs/common-holybro-kakutef7mini.rst, common/source/docs/common-holybro-pix32v5.rst, common/source/docs/common-lightware-lw20-lidar.rst, common/source/docs/common-minim-osd-quick-installation-guide.rst, common/source/docs/common-omnibusf4pro.rst, common/source/docs/common-openpilot-revo-mini.rst, common/source/docs/common-optical-flow-sensor-setup.rst, common/source/docs/common-optional-hardware.rst, common/source/docs/common-optitrack.rst, common/source/docs/common-pixhawk-wiring-and-quick-start.rst, common/source/docs/common-radiolink-minipix.rst, common/source/docs/common-serial-led-ProfiLED.rst, common/source/docs/common-telemetry-port-setup.rst, common/source/docs/common-thecubeorange-overview.rst, common/source/docs/common-wireless-gcs-repeater.rst, common/source/docs/common-zed.rst, frontend/scripts/get_discourse_posts.py, plane/source/docs/servo-functions.rst
=> Fix Typos #2 - Common

common/source/docs/common-FPort-receivers.rst, common/source/docs/common-blicube-rlink.rst, common/source/docs/common-camera-control-and-auto-missions-in-mission-planner.rst, common/source/docs/common-compatible-rc-transmitter-and-receiver-systems-erle-brain-2.rst, common/source/docs/common-connecting-sport-fport.rst, common/source/docs/common-downloads_advanced_user_tools.rst, common/source/docs/common-erle-brain-linux-autopilot.rst, common/source/docs/common-frsky-telemetry.rst, common/source/docs/common-geofencing-landing-page.rst, common/source/docs/common-holybro-kakutef4-mini.rst, common/source/docs/common-ie650-fuelcell.rst, common/source/docs/common-matekf765-wse.rst, common/source/docs/common-mission-planner-gps-based-antenna-tracking.rst, common/source/docs/common-msp-osd-overview-4.2.rst, common/source/docs/common-oem-customizations.rst, common/source/docs/common-omnibusnanov6.rst, common/source/docs/common-osd-overview.rst, common/source/docs/common-paramosd.rst, common/source/docs/common-piksi-multi-rtk-receiver.rst, common/source/docs/common-power-module-configuration-in-mission-planner.rst, common/source/docs/common-rc-systems.rst, common/source/docs/common-rfd900.rst, common/source/docs/common-sbus-out.rst, common/source/docs/common-servo-robotis.rst, common/source/docs/common-spektrum-rc.rst, common/source/docs/common-tbs-rc.rst, common/source/docs/common-thecubeyellow-overview.rst, common/source/docs/common-vl53l0x-lidar.rst, common/source/docs/common-wiki-editing-setup.rst
=> Fix Typos #3 - Common

common/source/docs/common-rtf.rst
=> common-rtf.rst - update/remove dead links

common/source/docs/common-packetdigital-mppt.rst
the title says it all.. I've tested this on my local machine
=> Common: add video to packet digitial MPPT page

common/source/docs/common-partners.rst
There is no drone company enroute in Japan.
There is no domain website.
If you are not getting partner support money, you should remove it.
=> partners: There is no drone company Enroute in Japan

copter/source/docs/altholdmode.rst, copter/source/docs/autotune.rst, copter/source/docs/circle-mode.rst, copter/source/docs/flight-modes.rst, copter/source/docs/follow-mode.rst, copter/source/docs/sport-mode.rst
=> Update mode pages with altitude control info

dev/source/docs/building-setup-windows10.rst
Adds a note about windows firewall settings that can cause issues when setting up WSL
=> Dev: add note about VcXsrv  Windows firewall settings

dev/source/docs/ros-install.rst, dev/source/docs/ros-rviz.rst, dev/source/docs/ros-timesync.rst, dev/source/docs/ros.rst
Some of the ROS instructions are quite out of date. This updates them.
=> Dev: Update ROS instructions

dev/source/docs/ros.rst
added working video link ros documentation.
=> wiki: fixed private video link in ROS doc

ardupilot/source/index.rst
easy way to tell if wiki is building or not
=> Add build date at bottom of main wiki page

copter/source/docs/traditional-helicopter-swashplate-setup.rst
This PR updates the heli collective blade pitch setup in 4.2
=> Update wiki for new collective pitch setup in 4.2

copter/source/docs/mission-command-list.rst
Update warning from 15 to 100 based on below PR.
https://github.com/ArduPilot/ardupilot/pull/18914
=> Update Warning for Do_Jump Max Number Limit from 15 to 100

common/source/docs/common-logs.rst
The link has been updated making the older one inaccessible.
For more info https://discuss.ardupilot.org/t/droneeplotter-an-elite-drone-flight-log-analysis-tool/39576/21
=> Updated link for Dronee Plotter

common/source/docs/common-advanced-configuration.rst, common/source/docs/common-optional-hardware.rst
=> Move multi RX setup to Advanced Config

dev/source/docs/gsoc-ideas-list.rst
Initial update of GSoC project ideas.  We need to make a bunch more updates to the details but at least this fixes the title and a number of the top ideas.
=> Dev: update gsoc ideas list for 2022

dev/source/docs/gsoc-ideas-list.rst
This adds more details on the projects that Randy is mentoring.
I've tested this locally and it seems ok.
=> Dev: update gsoc 2022 ideas detailed section

dev/source/docs/bootloader.rst
Updated the documentation to outline firmware flashing via UART ports in detail.
=> UART fw update procedure

common/source/docs/common-holybro-ph5x.rst
Add batt  monitor info for PM02D
=> Add batt monitor params

common/source/docs/common-lua-scripts.rst
The GCS message level has a debug level.
=> Lua: Add a debug level

plane/source/docs/advanced-failsafe-configuration.rst, plane/source/docs/analog-airspeed-sensors.rst, plane/source/docs/arming-your-plane.rst, plane/source/docs/automatic-landing.rst, plane/source/docs/mocking-an-airspeed-sensor-for-bench-testing.rst
continuing pulls off local WIP slowly generalizing away from Pixhawk only references...this cover the plane subdirectory
=> Generalization for all autopilots and minor cleanups as drive-bys

copter/source/docs/precision-landing-with-irlock.rst, copter/source/docs/radio-failsafe.rst, copter/source/docs/sprayer.rst, copter/source/docs/trad-heli-preflight-testing.rst, copter/source/docs/traditional-helicopter-connecting-apm.rst, copter/source/docs/traditional-helicopters.rst, copter/source/docs/what-you-need.rst
this completes the Pixhawk vs autopilot update for the copter docs....plus a few minor drive-bys
=> Generalize for all autopilots, plus a few drive-by tweaks

common/source/docs/common-lua-scripts.rst, common/source/docs/common-scripting-parameters.rst
=> Add page on scripting parameters

plane/source/docs/quadplane-transitions.rst
4.2 wiki for #19326 and #19664
=> Add transition failure actions

common/source/docs/common-scripting-aerobatics.rst, plane/source/docs/flight-features.rst
needs to have the Tricks on a Switch (ie aerobatics in any mode) PR merged, of course
I intend to add to the video on how to clean up the LUA after creating a new trick from a template also
=> Add Aerobatics page

plane/source/docs/apms-failsafe-function.rst
simplify and modernize the RC failsafe section....delay merge until new GCS messages merged...
would like Nick to review to catch my dyslexic typing...
=> RC Failsafe update

copter/source/docs/traditional-helicopter-autotune.rst, copter/source/docs/traditional-helicopter-tuning-preparing.rst
This PR adds videos for the autotune feature to help users better understand setup and what the actual autotune maneuvers were look like in flight.
=> Tradheli: add videos for autotune feature

common/source/docs/common-ads-b-receiver.rst, common/source/docs/common-airbotpower-power-module.rst, common/source/docs/common-antenna-tracking.rst, common/source/docs/common-benewake-tf02-lidar.rst
starting on common file...a's and b's in this one
=> Pixhawk generalization

rover/source/docs/reference-frames-deset-mapping-boat.rst
prettied up the page a bit and added a link to the sponsoring organisation
=> Rover: minor fixes to DeSET mapping boat reference frame page

common/source/docs/common-optitrack.rst
update info to use https://github.com/ArduPilot/MAVProxy/pull/1018
=> Optitrack: use mavproxy optitrack module

common/source/_static/common_theme_override.css
Looks a little something like this. Looks very similar on Rover and Copter too.
=> Add red text to Copter, Rover, and Plane toc 1st time items

common/source/_static/common_theme_override.css
Reverts ArduPilot/ardupilot_wiki#4239
=> Revert "Add red text to Copter, Rover, and Plane toc 1st time items"

ardupilot/source/index.rst
=> Fixies Rover land page link error

common/source/_static/common_theme_override.css
Reverts ArduPilot/ardupilot_wiki#4249
=> Re-instate "Add red text to Copter, Rover, and Plane toc 1st time items""

common/source/docs/common-tuning.rst
@lthall time to fix your link ;)
=> Copter: Tuning Fix Leonard's Link

dev/source/docs/porting.rst
Not sure if there are others we need to add?
=> Add H743 to list of supported CPUs

plane/source/docs/quadplane-flying.rst
discovered this while working on Blimp EKF FS....
=> Add EKF failsafe info for QuadPlanes

rover/source/docs/reference-frames.rst
I've tested this on my local machine and it seems ok.
=> Rover: add maker boat to reference frames page

common/source/docs/common-measuring-vibration.rst
There was a request made to add this information from a forum post.
https://discuss.ardupilot.org/t/imus-reporting-vibration-on-different-axis/82415/2?u=allister
=> Copter: Updates to vibration analsys for mechanical issues.

dev/source/docs/mavlink-get-set-flightmode.rst
Here's an attempt to resolve issue https://github.com/ArduPilot/ardupilot_wiki/issues/4301
=> Dev: add flight mode number ref to mavlink-get-set-flightmode

rover/source/docs/learning-a-mission.rst
SaveWP behavior while disarmed was not documented.
=> Rover: add note about clearing waypoints

dev/source/docs/ros-cartographer-slam.rst
Added ceresScanMatcher and realtimeCorrelativeScanMatching tuning parameters in cartographer.lua required to tune cartographer especially for multicopters
=> Cartographer: Added ceres_scan_matcher tuning parameters for multicopter

plane/source/docs/tecs-total-energy-control-system-for-speed-height-tuning-guide.rst
@tridge I get many requests for this from users. and to stop typing the same thing, decided to update the wiki..here is how I do it on all my planes...feel free to comment on anything that gives heartburn
=> Add TECS tuning info for no airspeed sensor

dev/source/docs/ros-cartographer-slam.rst
SLAM had an issue estimating position without remapping. Added remap tag with appropriate topics.
=> Updated Cartographer launch "Remap odom and imu data"

common/source/docs/common-aerotenna-usd1.rst
the US-D1 is not DroneCAN, it is a proprietary CAN protocol
=> fixed ainstein can docs

copter/source/docs/autotune.rst
=> Add notes about AUTOTUNE mode in AutoTune docs

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst, common/source/docs/common-mission-rewind.rst
DO_SET_RESUME_DIST is not defined.
I would change it to DO_SET_RESUME_REPEAT_DIST.
https://github.com/ArduPilot/mavlink/blob/2828d9dc21682b83d6f67825a883a857b73879d3/message_definitions/v1.0/ardupilotmega.xml#L31
=> common: Change to DO_SET_RESUME_REPEAT_DIST

.flake8, .github/workflows/test.yml, Sphinxsetup.sh, build_parameters.py, common_conf.py, frontend/scripts/get_discourse_posts.py, scripts/cap_params.py, update.py
These should be non-functional changes in the code. Added specific noqa where needed are removed unneeded noqa.
Added flake8 to CI with the same .flake8 config as the main repo. Tested that this does return a CI failure if flake8 finds an issue. Right now it is clean.
=> Add flake8 format checking

common/source/docs/common-partners.rst
I have written a script to autogenerate the partner's table. The autogenerated code obviously has perfect formatting which the manual entries did not. Hence this PR to fix that.
This makes it easy for us to add new partners. More importantly, we can finally remove old Partners. It was almost impossible to do in the current way.. I want to further automate the system. But this is the first step
=> NFC: Fix formatting on Partners Page to be consistent

dev/source/docs/building-setup-windows.rst, dev/source/docs/building-setup-windows10.rst, dev/source/docs/editing-the-code-with-vscode.rst
Should resolve some of the issues discussed in #4343. Most of the pieces were there already, just need to stitch them together like the Cygwin/Eclipse docs are.
Completes one item in #3688.
=> Update VSCode editor instructions and references

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst
Add the existing NAV_DELAY command and start cleanup of page...beginning with basiv NAV_WAYPOINT
=> Update with NAV_DELAY and correct NAV_WP

dev/source/docs/porting.rst
Add 1 MB flash note, and a few other fixes.
=> Add 1 MB flash note, other fixes

common/source/docs/common-cuav-nora-overview.rst
Also a few drive by small changes for unicode to ascii characters.
Covers one item in #3688.
=> Add CUAV-Nora UART3 to serial list

dev/source/docs/mavlink-commands.rst, dev/source/docs/mavlink-gimbal-mount.rst
This adds a new gimbal page to the MAVLink interface section of our development wiki.
I've tested the contents and rendering fairly carefully on my machine so hopefully it is ok.
=> Dev: mavlink interface for gimbal control

common/source/docs/common-watchdog.rst
Fix watchdog faultype enum link to the right place
=> Common watchdog

common/source/docs/common-gremsy-pixyu-gimbal.rst
This is in response to [this discussion](https://discuss.ardupilot.org/t/ardupilot-4-3-gremsy-gimbal-improvements-testers-wanted/86479/31) in which a user is struggling to get the autopilot and gremsy gimbal communicating.
I have tested this on my local machine
=> Common: Gremsy gets note about mini-banner upon successful connection

update.py
=> Fix build server

update.py
Missed the "el" of "elif" on the last one.
=> Revert logic change for wiki copy destination

Sphinxsetup.bat, Sphinxsetup.sh, update.py, update.sh
- check that each wiki did build ok
- check for key python version and modules
=> make backups and wiki runs safer

common/source/docs/common-buzzer.rst, common/source/docs/common-camera-gimbal.rst, common/source/docs/common-gremsy-pixyu-gimbal.rst, common/source/docs/common-rcoutput-mapping.rst, common/source/docs/common-simple-object-avoidance.rst, common/source/docs/common-simplebgc-gimbal.rst, common/source/docs/common-storm32-gimbal.rst, common/source/docs/common-tarot-gimbal.rst, copter/source/docs/sprayer.rst, dev/source/docs/mavlink-gimbal-mount.rst, dev/source/docs/using-sitl-for-ardupilot-testing.rst, plane/source/docs/differential-spoilers.rst
A double build on the server will be required to remake the inventory.
=> Update mount parameters

common/source/docs/common-gps-for-yaw.rst
addresses #4376   sorry it took a while
=> Update DroneCAN GPSS-for-yaw instructions

dev/source/docs/copter-adding-custom-controller.rst, dev/source/docs/learning-the-ardupilot-codebase.rst
Custom controller support 2nd version wiki https://github.com/ArduPilot/ardupilot/pull/21216
=> Add custom controller documentation

common/source/docs/common-oem-customizations.rst
Based items brought up on the 7/11/2022 devcall.
Also fixes a few formatting issues.
=> common: Custom OEM firmware and frame name

copter/source/docs/tuning.rst
The link is broken.
I will change this link to the new link.
This link takes you to ArduPilot member Leonard Hall's role description page.
=> tuning: Change the link

update.py, update.sh
This is a small effort to make the output quieter to make it easier to spot build issues when running things locally. I think I understand the build server method more now. That needs to be checked carefully so I can reduce my breakage per PR ratio. @peterbarker
=> Use debug() in more places in update.py

rover/source/docs/manual-mode.rst, rover/source/docs/rover-motor-and-servo-configuration.rst
Wiki to complete ArduPilot/ardupilot#21121.
=> Rover: Add steering speed scaling information

common/source/docs/common-ship-landing.rst
=> fixed link to ship landing lua script

copter/source/docs/trad-heli-mounting.rst, copter/source/docs/traditional-helicopter-configuration.rst, copter/source/docs/traditional-helicopter-connecting-apm.rst, copter/source/docs/traditional-helicopter-swashplate-setup.rst
This PR adds setup videos for 
Swashplate setup and leveling
Collective and stabilize curve setup
Flight controller mounting 
Flight controller connections and transmitter setup. 
@Hwurzburg please upload the videos [here](https://drive.google.com/drive/folders/1fNPRdNuvSaJQGEBA5j3mnc4NpRWkN9QY)  to YouTube.  There are 4 videos. I only see three at the moment. I will get the other one up there when I get home. 
Once they are uploaded, I will update the PR with the YouTube links.
=> add setup videos for trad heli

common/source/docs/common-qiotek-zealoth7.rst
Update common-qiotek-zealoth7.rst: added new sales partner within north America. I have purchased from this supplier and can verify they are reputable and quick source of this flight controller in NA
=> Update common-qiotek-zealoth7.rst: Add SmartFleet

dev/source/index.rst
=> Update roadmap link

frontend/includes/_topbar.html
I cant check this...Charlie pls review
=> cahnge roadmap menu link

common/source/docs/common-airvolute-DroneCore-Suite.rst, dev/source/docs/ap-peripheral-landing-page.rst, dev/source/docs/can-bus.rst, dev/source/docs/code-overview-sensor-drivers.rst, dev/source/index.rst, plane/source/docs/airspeed.rst
addresses #4698 and other instances
=> DroneCAN nomenclature updates

plane/source/docs/quadplane-frame-setup.rst
Co-authored-by:TimTuxworth(tim@objectivedata.com)
replaces #4708 with more clarifications
=> Update QPlane frame page with tricopter motor defaults

dev/source/docs/building-the-code.rst
haven't supported this in years
=> dev: building-the-code: remove references to make build system

common/source/docs/common-mro-nexus.rst
fixed broken link to the power module. this is the new link as they have updated their product numbering.  https://store.mrobotics.io/product-p/m10026a.htm
=> Update common-mro-nexus.rst: fix broken link

dev/source/docs/acadamic-works.rst
Added a link to the paper about balance bot implementation
@peterbarker
=> dev: add link to balance-bot paper

common/source/docs/common-holybro-ph5x.rst
change RC in recommendation to DMA enabled UART
=> change RC in to Serial5 on Pixhawk5X

copter/source/docs/copter-use-case-overview.rst
@Hwurzburg  
again the dronkit python link was broke so I updated it to the dronkit webpage. also 3dr links broken and I removed the link completely as they will never be back. not sure if you want the dronekit link to go to their webpage or the dronekit github?
=> Update: broken links dronekit and 3dr robotics

common/source/docs/common-modalai-voxl.rst
This adds my latest modalai testing video to the modalai wiki page.
I've tested this locally and it seems OK.
=> Common: add video to modalai wiki page

common/source/docs/common-cuav-x7-family-overview.rst
@Hwurzburg  
again the dronkit python link was broke so I updated it to the dronkit webpage. also 3dr links broken and I removed the link completely as they will never be back. not sure if you want the dronekit link to go to their webpage or the dronekit github?
=> Update: fixed broken link

common/source/docs/common-cuav-nora-overview.rst
aliexpress link was broken
https://leixun.aliexpress.com/store/all-wholesale-products/1101268771.html?spm=a2g0o.store_pc_promotion.pcShopHead_7913971.1
=> Update: broken link

common/source/docs/common-cuav-v5nano-overview.rst
fixed broken aliexpress link
https://leixun.aliexpress.com/store/all-wholesale-products/1101268771.html?spm=a2g0o.store_pc_promotion.pcShopHead_7913971.1
=> Update: fixed broken aliexpress link

dev/source/docs/code-overview-adding-a-new-mavlink-message.rst
Co-authored-by: Henry Wurzburg <hwurzburg@yahoo.com>
=> Add html link to MAV_CMD_NAV_WAYPOINT

dev/source/docs/setting-up-sitl-on-windows.rst
Remove useless steps on VM configuration.
It would need a full rewrite , but outside the scope of this PR
=> dev: improve setting sitl on VM

dev/source/docs/gsoc.rst
There were some tiny grammatical errors which I encountered while going through gsoc.rst
=> Corrected some grammatical errors in  gsoc.rst

common/source/docs/common-external-ahrs.rst, common/source/docs/common-optional-hardware.rst
took a stab at this...let me know if it needs anything else?
=> add page for external AHRS systems

common/source/docs/common-donation.rst
Added a link to the page explaining how funds are spent at the bottom of the donations page
=> Add how funds are spent on the donations page

common/source/docs/common-positioning-landing-page.rst
need more info on SBF yaw setup from @WickedShell
=> Add info for GPS driver options

dev/source/docs/sitl-with-realflight.rst
I just setup SITL with RealFlight Evolution and learned some things that might be helpful.
=> Update docs for SITL with RealFlight

common/source/docs/common-MAVLink-high-latency.rst, common/source/docs/common-telemetry-landingpage.rst
Finally remembered to add documentation for https://github.com/ArduPilot/ardupilot/pull/19882
=> Add Mavlink High Latency information

dev/source/docs/mavlink-requesting-data.rst
This resolves some user confusion raised in this issue https://github.com/ArduPilot/ardupilot/issues/22361
=> Dev: correct file location used for setting message rates

common/source/docs/common-archived-topics.rst, dev/source/docs/bootloader.rst, dev/source/docs/esp32-autopilot.rst, dev/source/docs/pixhawk-advanced-hardware-info.rst, dev/source/docs/troubleshooting-pixhawkpx4-boot.rst, dev/source/docs/using-DFU-to-load-bootloader.rst
archives the old Pixhawk boot issue page also
=> Add ESP32 info and update Adv Hdwr pages

copter/source/docs/terrain-following-manual-modes.rst, copter/source/docs/terrain-following.rst
@rmackay9 we need to explain how terrain following and surface tracking co-exist...ie hand-offs....does terrain following take over once out of downward facing RF range?what happens if it goes out of upward facing range?
=> add SURFTRAK_MODE info

common/source/docs/common-esc-issues.rst
Add links to firmware fixes for over voltage issue.
=> Common: update APD ESC errata

.vscode/settings.json, .vscode/tasks.json
Recreation of #4556 after a IDE git mess.
=> .vscode: Add tasks for each wiki and create a settings file

dev/source/docs/raspberry-pi-via-mavlink.rst
Added a note about performance of mavproxy.py on low powered PIs. mavlink-routerd works much better.
=> mavproxy.py performs poorly on slow PIs

plane/source/docs/quadplane_rtl.rst
=> info for hybrid rtl type 2

copter/source/docs/airmode.rst
@bnsgeyer Bill, just want to be sure Trad Heli still does not use AIRMODE per note here....
=> update AIRMODE page

dev/source/docs/raspberry-pi-via-mavlink.rst
=> Add MAVp2p to MAVLink router options

dev/source/docs/events.rst
I've tested this on my local machine and it seems OK.
=> Dev: add 2023 conference to events page

copter/source/docs/connect-escs-and-motors.rst
making a correction to the spelling error
=> shoould to should

common/source/docs/common-torqeedo.rst
replaced 483 with 485
This has been tested on my local machine and seems ok
=> Common: fix torqeedo typo

common/source/docs/common-non-gps-navigation-landing-page.rst
Vicon can still be used on 1MB boards.
=> Add note about Vicon being available on 1MB boards

mavproxy/source/docs/uav_configuration/arming.rst
Document how to force arm in mavproxy
=> MAVPRoxy documentation arm throttle force

plane/source/docs/automatic-landing.rst
I did some SITL testing of the AutoLanding page updates and found these suggestions might be helpful. The second one is especially important for anyone using QGroundControl because it has a very cool landing wizard, but it doesn't quite work the same way as we described.
=> Wiki Plane: Minor tweaks to autolanding

common/source/docs/common-esc-telem-based-notch.rst
Add a note about dynamic notches and latency. 
@tridge @andyp1per let me know if this makes sense. 
Does it nead a suggested notch width?
=> Note for dynamic harmonics and narrower bandwidth

common/source/docs/common-gremsy-pixyu-gimbal.rst
I've added warnings re the MIO and T3V3 based on testing we've done in the dev team.
=> Common: Gremsy gimbal warning re MIO and T3V3

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst
=> add DO_GIMBAL_MANAGER_PITCHYAW command

dev/source/docs/gsoc-ideas-list.rst, dev/source/docs/gsoc.rst
These are my updates to the GSoC 2023 projects list
=> Dev: update GSoC 2023 projects list

dev/source/docs/gsoc-ideas-list.rst
This adds two more projects to the list
- Camera and Gimbal enhancements
- Multcopter swarming avoidance
This has been tested locally and looks ok.
=> Dev: GSoC 2023 project list update 2

dev/source/docs/mavlink-camera.rst
This adds developer documentation and examples for 5 camera related mavlink commands that will be supported in 4.4 ([see flight code PR here](https://github.com/ArduPilot/ardupilot/pull/23147))
=> Dev: fix and improve mavlink interface camera controls

dev/source/docs/style-guide.rst
Grammatical update in style-guide introduction
=> Style guide

common/source/docs/common-modalai-voxl.rst
This is a minor fix to the VOXL camera configuration section based on feedback from @patrickpoirier51 and a couple of users who have reported issues.
This has been tested locally on my machine and seems fine.
=> Common: ModalAI setup instruction fix

copter/source/docs/copter-flight-features.rst, copter/source/docs/weathervaning.rst
this is for 4.4...if okay I will put a link in the upcoming features document to this PR
=> Add copter specific weathervaning

plane/source/docs/automatic-takeoff.rst
=> Add TKOFF_GND_PITCH param

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst
when it appears in MP I will capture a screenshot
=> Add DO_JUMP_TAG cmds

common/source/docs/common-auxiliary-functions.rst, common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst
for 4.4...assumes #23129 is merged before branching
=> add plane payload place mission item

common/source/docs/common-advanced-configuration.rst, common/source/docs/common-archived-topics.rst, common/source/docs/common-arkflow.rst, common/source/docs/common-cheerson-cxof.rst, common/source/docs/common-hereflow.rst, common/source/docs/common-mouse-based-optical-flow-sensor-adns3080.rst, common/source/docs/common-non-gps-navigation-landing-page.rst, common/source/docs/common-openmv-optflow.rst, common/source/docs/common-optical-flow-sensor-setup.rst, common/source/docs/common-optical-flow-sensors-landingpage.rst, common/source/docs/common-optional-hardware.rst, common/source/docs/common-px4flow-overview.rst, common/source/docs/common-upixels-upflow.rst
Add documentation for using optical flow sensors on rover
=> Common: Add optical flow on rover

copter/source/docs/traditional-helicopter-autotune.rst
This PR updates the autotune wiki to include changes that were made to the angle p autotune test (#20780).  This change included a tune check test to allow the user check the tune once they completed the autotune testing.
=> tradheli-update for angle P autotune test

copter/source/docs/traditional-helicopter-autorotation.rst, copter/source/docs/traditional-helicopter-rsc-setup.rst, copter/source/docs/traditional-helicopters.rst
PR that explains how to set up manual autoroation.
=> Tradheli: explanation of manual autorotation setup

common/source/docs/common-auxiliary-functions.rst
@rmackay9 Randy, feel free to expand on the details
=> update camera options in aux functions

common/source/docs/common-dronecan-servos.rst, common/source/docs/common-servo-landingpage.rst, common/source/docs/common-uavcan-escs.rst, common/source/docs/common-uavcan-peripherals.rst
=> Add DroneCAN Servos page and update ESCs page

common/source/docs/common-brushless-escs.rst, common/source/docs/common-esc-calibration.rst, plane/source/docs/a-high-quality-bixler-1-1-build.rst, plane/source/docs/apms-failsafe-function.rst, plane/source/docs/guide-elevon-plane.rst, plane/source/docs/guide-four-channel-plane.rst, plane/source/docs/guide-vtail-plane.rst, plane/source/docs/plane-configuration-landing-page.rst, planner/source/docs/mission-planner-initial-setup.rst, rover/source/docs/rover-code-configuration.rst
Rover has needed this for a while
NB @rmackay9
=> Common ESC cal page for plane and rover

plane/source/docs/quadplane-frame-setup.rst
Co-Authored-by:Jet<taijunjet@hotmail.com>
=> Expand info on frame and class types for quadplane

frontend/index.html
thanks to
https://discuss.ardupilot.org/t/misspelled-word-on-ardupilot-com/90764
=> fix unfortunately spelling error

plane/source/docs/apms-failsafe-function.rst
Current explanations are hard to follow and a bit incomplete....this should make it easier to understand what each parameter value actually produces as an action....the param metadata is confusing also, I will attempt to improve that next...
@peterbarker will include URLs to the param section of this in that metadata since we can and MP can parse it...
=> Plane: Clarify failsafe actions by mode

dev/source/docs/sim-on-hardware.rst
new link depends on #23773 being merged
=> Update SITL on hardware docs

common/source/docs/common-auxiliary-functions.rst
=> add winch aux switches

common/source/docs/common-aerotenna-usd1.rst
This resolves issue https://github.com/ArduPilot/ardupilot_wiki/issues/5169 and also fixes the link to the user manual.
=> Common: usd1 lidar baud fix

common/source/docs/common-speedybeef405wing.rst
=> correct typos,add wifi note

dev/source/docs/sitl-with-gazebo.rst
without -p option the command gives error
=> Dev: Added -p for parent folder

common/source/docs/common-optical-flow-sensor-setup.rst
=> add note on max height and fix formatting

common/source/_static/common_theme_override.css, copter/source/docs/traditional-helicopter-first-flight.rst, copter/source/docs/traditional-helicopter-first-time-setup.rst, copter/source/docs/traditional-helicopters.rst, copter/source/index.rst
NFC...change org to match other vehicles
=> Re-org traditional heli to match other vehicles

common/source/docs/common-pozyx.rst
This updates the Pozyx page to remove references to very old AP versions and fixup the EKF settings.
=> Common: update pozyx EKF3 param settings

common/source/docs/common-gps-for-yaw.rst
this requires another PR to be merged once completed
=> update and expand gps for yaw for DroneCAN single units

common/source/docs/common-cuav-c-rtk2-hp.rst, common/source/docs/common-uavcan-peripherals.rst
Modify display error and add C-RTK2 HP to droncan peripheral.
=> Modify C-RTK2 hp error message and add to droncan peripherals

common/source/docs/common-rcoutput-mapping.rst
Parameter name was incorrect in note.
=> Fix serv to servo

.gitignore, common/source/docs/common-esp8266-telemetry.rst
Adding more detail for mac user to how to flash the ESP8266
=> Esp8266 detail esptool

common/source/docs/common-positioning-landing-page.rst, common/source/docs/common-uavcan-peripherals.rst, plane/source/docs/airspeed.rst
Added links to Qiotek M10 GNSS and fix expired issues
=> Added links to Qiotek M10 GNSS and fix expired issues 

dev/source/docs/building-setup-windows-cygwin.rst
In line with `cygwin_build.sh`
=> Toolchain name update

common/source/docs/common-pixhawk-overview.rst
Background: https://www.rcgroups.com/forums/showthread.php?1493712-JST-connector-confusion-the-real-story/page3#post29192314
=> Add warning about picoblade connectors to Pixhawk

common/source/docs/common-imu-notch-filtering.rst
added options and explanations
=> Update notch options

common/source/docs/common-external-ahrs.rst
Wiki updates for https://github.com/ArduPilot/ardupilot/pull/24510
=> Rename LORD to MicroStrain

copter/source/docs/traditional-helicopter-tailrotor-setup.rst, dev/source/docs/porting.rst
=> typos: ArudPilot -> ArduPilot

rover/source/docs/additional-information.rst
=> Fix hidden Rover additional info

antennatracker/source/docs/choosing-antenna.rst
I updated the lower case bullet list to capital bullet lists
=> updated bullets to caps

common/source/docs/common-uavcan-peripherals.rst
I'm happy to send out samples A/R.
=> Added anyleaf GNSS to CAN devices

common/source/docs/common-xacti-gimbal.rst
This adds some extra info on the Xacti setup discovered during testing.
I've tested this locally on my machine and it looks OK
=> Common: Xacti can and devid param info

common/source/docs/common-msp-osd-overview-4.2.rst, common/source/docs/common-msp-overview.rst, common/source/docs/common-osd-boards-on-screen-display.rst
Just been trying to set up HDZero on my quad, and noticed the documentation is a bit outdated, so I've updated some parts, and also added the mention of stick commands.
Added Walksnail as well - I think it's correct?
=> Include HDZero and Walksnail in MSP pages, add mention of stick commands etc

common/source/docs/common-compass-calibration-in-mission-planner.rst
two instances recent with users not setting orientation before magcal
=> common: upgrade orientation note to warning

common/source/docs/common-uavcan-peripherals.rst
Of note, the RC input functionality currently works with AP, but the arbitrary telemetry (ELRS Airport) and CRSF telemetry functionalities will need additions to AP to support telemetry over CAN. I'm happy to implement whatever y'all decide on.
=> Added anyleaf-elrs-rx

dev/source/docs/ardupilot-on-linux-init-scripts.rst, dev/source/docs/ardupilot-on-linux-kernel-configuration.rst, dev/source/docs/ardupilot-on-linux-porting.rst, dev/source/docs/ardupilot-on-linux-starting.rst, dev/source/docs/ardupilot-on-linux.rst, dev/source/index.rst
Add pages about kernel config, init scripts, and startup options.
Also add a new landing page.
=> dev: Add more linux pages

common/source/docs/common-speedybeef405wing.rst
=> SpeedyBee F405 Wing Group Typo

common/source/docs/common-partners-program.rst
=> Add contact form link to Partners Program page

common/source/docs/common-3dr-power-module.rst
fix BATT2_CURR_PIN typing error
=> fix BATT2_CURR_PIN typing error

frontend/css/main.css
Added hover effects to links in navbar for better user experience.
Screenshot for preview:
=> Improved navabar links

frontend/scripts/get_discourse_posts.py
allow to catch image if they are in the right img field but not have .jpg/.png type in url
=> frontend: add another regext to catch blog image in first 5 lines

common/source/docs/common-commercial-support.rst
I'm having issues with eosbandi.com, so changed to the contact email to a gmail.one
=> Update common-commercial-support.rst : Email address change

common/source/docs/common-advanced-configuration.rst, common/source/docs/common-optional-hardware.rst, copter/source/docs/precision-landing-with-irlock.rst
This brings wiki up to date with stable..once merged will add the 4.5 option additon
=> Add precision landing information and params

common/source/docs/common-choosing-a-ground-station.rst
needed some updates and expansion
=> clairfy gcs selection page

common/source/docs/common-apm-navigation-extended-kalman-filter-overview.rst
need to add this so new AHRS_OPTIONS have a home in wiki
=> add section on DCM fallback to EKF3 doc

common/source/docs/common-here-plus-gps.rst, common/source/docs/common-positioning-landing-page.rst, common/source/docs/common-uavcan-peripherals.rst
@bugobliterator Sid, maybe I should archive the here+ page and just link to the docs like the others?
=> update gps landing page with CubePilot gps

dev/source/docs/bootloader.rst
List would be mangled into previous paragraph before, now it shows as a list
=> fix list formatting in bootloader.rst

dev/source/docs/ros2-gazebo.rst, dev/source/docs/sitl-with-gazebo.rst
* It's the next release, and is LTS
=> Support gazebo harmonic

dev/source/docs/learning-ardupilot-uarts-and-the-console.rst, dev/source/docs/sitl-serial-mapping.rst, dev/source/docs/using-sitl-for-ardupilot-testing.rst
Missed a couple bits with https://github.com/ArduPilot/ardupilot_wiki/pull/5653 .
=> Excise legacy UART order more thoroughly

common/source/docs/common-auxiliary-functions.rst
Reverts ArduPilot/ardupilot_wiki#5675
=> Revert "4.5:add extAHRS rc switch"

common/source/docs/common-future-wiki-changes.rst
and update ahrs additions on existing PR
=> add extAHRS switch to upcoming

common/source/docs/common-auxiliary-functions.rst
All test should be readable without using table slider now on most displays
=> eliminate need to use horz slider to see text

common/source/docs/common-loading-firmware-onto-pixhawk.rst
Noticed there was a lack of clear documentation on this procedure, so added the steps based on the ChibiOS loading page (which is very easy to overlook) and some recent Discord chats.
=> Update loading firmware page with custom firmware instructions

common/source/docs/common-gps-for-yaw.rst, common/source/docs/common-positioning-landing-page.rst
=> OEM neuter moving basline setup page

antennatracker/source/conf.py, ardupilot/source/conf.py, blimp/source/conf.py, copter/source/conf.py, dev/source/conf.py, frontend/index.html, mavproxy/source/conf.py, plane/source/conf.py, planner/source/conf.py, planner2/source/conf.py, rover/source/conf.py
Global change for all of the copyright years in the wiki.
=> Bump copyright year to 2024

common/source/docs/common-prearm-safety-checks.rst
a few copter nitpicks fixed also
=> add plane pre-arms to table

dev/source/docs/gsoc-ideas-list.rst
Initial update GSoC Ideas list for 2024
- updated dates
- added projects from last year.
=> GSoC: Update gsoc-ideas-list.rst

update.sh
freshening these resources is bad for several reasons:
- we are updating the "old_params" directory from the "new_params" directory and thus next time we check for changes we find none (lost update trigger)
- we do unnecessary work when the build is already running
=> update.sh: check lockfile before freshening remote resources

dev/source/docs/mavlink-gimbal-mount.rst
This adds developer information on how to use MAV_CMD_DO_GIMBAL_MANAGER_CONFIGURE to the mavlink interfaces section.
This has been tested locally and looks OK.  I've also tested the copy-paste-able commands to ensure they work.
This is related to this flight code PR https://github.com/ArduPilot/ardupilot/pull/25937
=> Dev: mavlink interface for do-gimbal-manager-configure

copter/source/docs/traditional-helicopter-tailrotor-setup.rst
this consolidates several previous PRs (#5522, #5328, and #5584) and rebases them upon an expansion PR that should be merged before this (#5590)
=> 4.5/heli tail update

common/source/docs/common-canbus-setup-advanced.rst, common/source/docs/common-rangefinder-landingpage.rst
Added docs for:
Nooploop TOF Sense P
Nooploop TOF Sense F
NanoRadar NRA24 (CAN)
=> Add new rangefinders

common/source/docs/common-gremsy-pixyu-gimbal.rst
This is a small update to tell users how the Gremsy ZIO camera should be configured.
This covers the wiki update required for this autopilot flight code PR https://github.com/ArduPilot/ardupilot/pull/23138
=> Common: gremsy gets ZIO cam1_type param setting

common/source/docs/common-osd-overview.rst
Add explanation of OSD_TYPE2 second OSD backend
=> 4.5: add OSD_TYPE2

copter/source/docs/circle-mode.rst
Refrence to [#23627](https://github.com/ArduPilot/ardupilot/pull/23627)
=> Wiki:Copter: Add CIRCLE_OPTIONS 3rd bit description in Circle mode doc

common/source/docs/common-efi.rst
replaces #5288 since I can fix merge conflicts in that PR since it was not made on a working branch
=> add EFI MAVLink setup

dev/source/docs/gsoc-ideas-list.rst
I've removed three old projects and added two new ones.
I've run this locally and it looks OK to me.
=> Dev: update GSoC ideas list

dev/source/docs/sitl-with-gazebo.rst
Update docs for Gazebo Harmonic support.
Fix: #5735
=> Update SITL instruction for Gazebo harmonic

dev/source/docs/gsoc-ideas-list.rst
This adds a project idea for GSOC 2024.
=> gsoc-idea-list: add custom build server project to idea list

common/source/docs/common-ekf-sources.rst
I think it is worth adding some information about the source options bit in the switching page.
=> common-ekf-sources: Add comments around source options

common/source/docs/common-ekf-sources.rst
=> Revert "common-ekf-sources: Add comments around source options"

common/source/docs/common-ekf-sources.rst
fixed ver of #5770 that I merged too soon
=> Add comments about source fusing option

common/source/docs/common-compass-setup-advanced.rst, common/source/docs/common-magfit.rst
=> switch to webtool magfit as a recommendation

dev/source/docs/gsoc-ideas-list.rst
This adds one new idea to the GSoC projects list.
It also fixes a couple of links and some formatting of the custom build server project idea
=> Dev: GSoC ideas gets high-altitude Non-GPS estimation

copter/source/docs/brake-mode.rst
Added parameter changes necessary for more aggressive braking.
=> Copter: Update brake-mode.rst

common/source/docs/common-network.rst
This PR was merged today https://github.com/ArduPilot/ardupilot/pull/26562#event-12180963748
=> NET_ENABLED is now NET_ENABLE

common/source/docs/common-imutempcal.rst
Relates to: https://github.com/ArduPilot/ardupilot/pull/26623
=> common: add requirement of setting INS_TCAL_OPTIONS bits when persistently saving

common/source/docs/common-optitrack.rst
Thank Tristan Redish for pointing out doc error
https://discuss.ardupilot.org/t/optitrack-with-quadplane/116077/2?u=chobitsfan
=> optitrack: note software version & add missing steps

common/source/docs/common-mount-targeting.rst
Just make it clearer how to target another vehicle.
=> Update common-mount-targeting.rst to better describe SysID targeting

copter/source/docs/additional-information.rst, plane/source/docs/additional-information.rst, rover/source/docs/additional-information.rst
This resolves issue https://github.com/ArduPilot/ardupilot_wiki/issues/5885
=> Copter: add WebTools to Additional Information

common/source/docs/common-modalai-voxl.rst, dev/source/docs/companion-computers.rst
Added VOXL2 to the list of companion computers
=> VOXL2 companion computer

dev/source/docs/porting.rst
=> add test suggestions for a new board port

common/source/docs/common-auxiliary-functions.rst
Reverts ArduPilot/ardupilot_wiki#5914   prematurely merged
=> Revert "4.6:Add mission pause switch"

common/source/docs/common-flywoof405pro.rst
=> fixed typo (Arduplot -> Ardupilot)

README.md, dev/source/docs/ros.rst, dev/source/docs/ros2-over-ethernet.rst
This creates a tutorial for communicating with your FC over ethernet using DDS.
=> Add ros2 ethernet docs

dev/source/docs/acadamic-works.rst
Adding research that I conducted with a University of Portland Professor on UAS automation/handling qualities.  All vehicle used in this research used ArduCopter.  Dr. Ivler's aircraft used modified firmware that had a separate flight mode that utilized a control law that she designed whereas my aircraft used stock Arducopter firmware.
=> Add research paper reference for UAS automation/handling qualities

dev/source/docs/ros2.rst
Documenting build error from ArduPilot/ardupilot_gz#50
=> build deps for ros2 and gz

common/source/docs/common-rtf.rst
This adds the RToS SPARK Kit to our list of RTF vehicles.  RToS is one of our newer partners
This has been tested locally and looks OK to me
=> Common: add RToS SparkKit to RTF rovers list

copter/source/docs/ac2_guidedmode.rst, copter/source/docs/auto-mode.rst
=> add GUIDED mode speed info

copter/source/docs/terrain-following.rst
=> expand info on ter follow in rtl

common/source/docs/common-geofencing-landing-page.rst
Update fence info including AUTOEANBLE 1 and 2 deprecation warning
=> Fence update

dev/source/docs/ros2-sitl.rst
* Lots of people change this and forget about it
=> Dev: Recommend checking ROS_DOMAIN_ID

common/source/docs/common-rangefinder-nooploop-tofsense-f.rst, common/source/docs/common-rangefinder-nooploop-tofsense-p.rst
Due to product iteration, updating manuals and product names
=> Update common-rangefinder-nooploop doc

common/source/docs/common-custom-firmware.rst, common/source/docs/common-loading-firmware-onto-chibios-only-boards.rst, common/source/docs/common-loading-firmware-onto-pixhawk.rst, dev/source/docs/building-the-code.rst, dev/source/docs/custom-build-server.rst
This adds documentation for custom build server.
=> add documentation for custom build server

dev/source/docs/learning-ardupilot-uarts-and-the-console.rst
Since the Wiki doesn't already have this - added details on how to connect to SITL serial ports
=> Dev: Add details and examples of SITL serial ports

copter/source/docs/traditional-helicopter-tailrotor-setup.rst
Spotted a couple of minor errors on the DDFP tail config advice.
=> Trad Heli Tail Types: fixup DDFP settings and defaults

common/source/docs/common-vio-tracking-camera.rst, dev/source/docs/raspberry-pi-via-mavlink.rst
Updating product links, as the "v2" Pi-Connect Lite has been released.
=> update product links for Rpanion

copter/source/docs/copter-flight-features.rst, copter/source/docs/introduction.rst, copter/source/docs/traditional-helicopter-autorotation.rst, copter/source/docs/traditional-helicopter-inverted-flight.rst, copter/source/docs/traditional-helicopters.rst
A few tweaks but mainly info on inverted flight
=> Add Copter inverted flight info

common/source/docs/common-optitrack.rst
With https://github.com/ArduPilot/MAVProxy/pull/1444 merged, now we support both Motive 2 and 3
=> Optitrack: update supported software version

dev/source/docs/building-setup-linux.rst
Wiki for https://github.com/ArduPilot/ardupilot/pull/28122
=> Clarify minimum support for Ubuntu setup

common/source/docs/common-electro-permanent-magnet-V3.rst
Added information regarding product status and updated links.
=> Updated OpenGrab EPM v3 information

plane/source/docs/introduction.rst
It seems that the paragraph was with an extra line feed
=> Plane: Wiki, fixed paragraph line position

dev/source/docs/ros2.rst
=> Use help instead of version to verify uxrcegen

dev/source/docs/ros2.rst
Add `-y -r` flags to continue on error and accept all changes.
=> ROS: update rosdep command

common/source/docs/common-telemetry-xbee.rst
- added XBee SX 868 example config
- reformatted XBee ZB table for better readability (more spaces)
- some consistency (80 char line length, line breaks with new sentences, ...)
- typo fixes
=> Add XBee SX 868 Config

common/source/docs/common-transmitter-tuning.rst
Wiki needed for PR https://github.com/ArduPilot/ardupilot/pull/25203
=> Add RC channel selection procedure for Copter Transmitter Based Tuning

common/source/docs/common-stores.rst
Add Hardware Vendor Pogo-Tech.
=> Update common-stores.rst：Add Hardware Vendor Pogo-Tech.

common/source/docs/common-stores.rst
Reverts ArduPilot/ardupilot_wiki#6404...sorry...Partners only
=> Revert "Update common-stores.rst：Add Hardware Vendor Pogo-Tech."

copter/source/docs/setting-up-for-tuning.rst
Co-authored-by: Michelle Rossouw <michelleros128@gmail.com>
=> Adjust max and min battery voltage suggestions 

common/source/docs/common-mount-targeting.rst
=> add mount option param

common/source/docs/common-auxiliary-functions.rst, plane/source/docs/qautotune-mode.rst, plane/source/docs/quadplane-flight-modes.rst, plane/source/docs/quadplane-tuning-landingpage.rst, plane/source/docs/quadplane-vtol-tuning-process.rst, plane/source/docs/quadplane-vtol-tuning.rst, plane/source/docs/quicktune.rst
@MichelleRos I created shell for the QwikTune PR and highlighted in bold sections that need your input...if you could squash your added commits to this to a single commit, it would save me a step later...thanks
=> 4.7:Add Quadplane QwikTune

scripts/initvagrant.sh
allows build process to complete
=> scripts: initvagrant.sh: create www backup dir

dev/source/docs/support_proxy_supportengineer.rst
proxy now supports both UDP and TCP
=> note TCP available for proxy

common/source/docs/common-continue-mission.rst
=> add note to mission continue page

plane/source/docs/soaring.rst
Wiki for https://github.com/ArduPilot/ardupilot/pull/14815 that got lost along the way
=> plane: Use  RCx_OPTION to enable soaring on a switch

mavproxy/source/docs/modules/graph.rst
=> mavproxy: Document how to graph NAMED_VALUE_FLOAT

Vagrantfile, scripts/initvagrant.sh
This allows the user to run /vagrant/update.sh in the VM and produce a successful build
=>  initvagrant: set up build_wiki structure in /home/vagrant 

dev/source/docs/gsoc-ideas-list.rst, dev/source/docs/gsoc.rst
This updates the GSoC pages for 2025 including:
1. replace "2024" with "2025"
2. added projects completed in 2024
3. project suggestions from Randy
4. other minor changes
=> Dev: GSoC 2025 updates

dev/source/docs/gsoc-ideas-list.rst
We were missing one project from the list.  I've tested this locally and it looks OK to me
=> Dev: add missing GSoC 2024 completed project

dev/source/docs/gsoc-ideas-list.rst
I've added a 3rd item to the GSoC 2025 ideas list which is to add an AI chat bot to all our web tools
=> Dev: gsoc ideas list gets one more item

dev/source/docs/gsoc-ideas-list.rst
This adds 3 more GSoC ideas from Nate who has agreed to be a mentor this year, thanks!
Similar to PR https://github.com/ArduPilot/ardupilot_wiki/pull/6612, I'll merge this as soon as it passes CI
=> Dev: GSoC ideas from Nate

dev/source/docs/ros2-sitl.rst
Fixes user question here: https://discord.com/channels/674039678562861068/850924523610963988/1339938011307053137
=> dev: Fix incorrect node name

dev/source/docs/ros2-over-ethernet.rst, dev/source/docs/ros2-waypoint-goal-interface.rst
The XML profile isn't used anymore, follow up from here: https://github.com/ArduPilot/ardupilot_wiki/pull/6603
=> dev: Remove XML profile usage

dev/source/docs/ArduSub_MAVLink_Messages.rst, dev/source/docs/mavlink-commands.rst
Longer term hoping to automate this (per #6065), but handling it manually for now.
Extends the additions of #6379.
=> dev: add Sub MAVLink messages

rover/source/docs/rover-video-demonstrations.rst
Randy made a nice video showing off ArduRover functionality - seems worthwhile to include :-)
=> rover: video-demonstrations: include skid-steer boat example

dev/source/docs/using-sitl-for-ardupilot-testing.rst
=> Correct typo

dev/source/docs/porting.rst, dev/source/docs/readme_file.rst
=> add Readme.md guide

dev/source/docs/gsoc-ideas-list.rst
It seems like some students had confusion with the unavailable Intel D465 model. Replaced it with Intel D455.
=> Dev: Updated the intel realsense model name in gsoc project

dev/source/docs/debugging-with-gdb-using-vscode.rst
Add --vs-launch docutment
linked PR: https://github.com/ArduPilot/ardupilot/pull/28839
=> Add vscode debug --vs-launch document

dev/source/docs/mavlink-requesting-data.rst
This PR makes two changes to our [mavlink-requesting-data wiki page](https://ardupilot.org/dev/docs/mavlink-requesting-data.html):
1. Adds a method to set the rates using a Lua script
2. Moves and expands the note re message rates reverting to some fixed rate
This closes issue https://github.com/ArduPilot/ardupilot_wiki/issues/6715
By the way, the reason I've made this PR is because amazingly two unrelated people contacted me in the past 24hrs both facing issues getting the mavlink messages rates working correctly
=> Dev: mavlink requesting data pages get lua script method

common/source/docs/common-siyi-zr10-gimbal.rst
Siyi seems to have broken the old link and uses this one now
=> Correct link to siyi a8 mini

common/source/docs/common-telemetry-rockblock.rst
Update the Rockblock documentation as per the changes in https://github.com/ArduPilot/ardupilot/pull/29314 and https://github.com/ArduPilot/ardupilot/pull/29192
=> Common: Update Rockblock usage

common/source/docs/common-cabling-guide.rst, common/source/docs/common-flight-controller-io.rst, common/source/docs/common-optional-hardware.rst
This is a cleanup of #6755 and replaces it
=> Add  detailed cabling guide

plane/source/docs/automatic-tuning-with-autotune.rst
=> Common: Fix missing ref link

common/source/docs/common-tuning.rst, copter/source/docs/configuring-hardware.rst, copter/source/docs/tuning-process-instructions.rst
Feedback in the forums re the Methodic Configurator indicates that it is helping users.  This updates the wording to recommend it to a wider user base
FYI @amilcarlucas
=> Copter: expand Methodic Configurator recommendation

common/source/docs/common-prearm-safety-checks.rst
=> add BARO/GPS alt error prearm

common/source/docs/common-autopilots.rst
=> add VOXL2 to autopilots

common/source/docs/common-install-sdcard.rst, dev/source/docs/porting.rst
=> update flashing from sd card

dev/source/docs/style-guide.rst
Document standard c++ suffix/abbreviations for units. 
Updated based on the DevCall 13 May 2025.
=> Dev: document unit abbreviations for c++

sub/source/docs/sub-hardware.rst
merge when https://github.com/ArduPilot/ardupilot/pull/30018 is merged
=> Sub:add note re RCMAP to defaults

sub/source/docs/arming-the-motors.rst
#6839 added the page, but links to it with dashes in the name, so it's not appearing in the sidebar.
Dashes also seems more consistent with most of the other filenames, so I opted to rename the (recently added) file rather than changing the link.
=> sub: Rename arming_the_motors.rst to arming-the-motors.rst

rover/source/docs/rover-failsafes.rst
=> add info on crash_angle param

frontend/Dockerfile, frontend/scripts/get_discourse_posts.py
also change User-Agent name to not have bot in it
=> frontend: use only one Session to grab discuss data

dev/source/docs/companion-computers.rst, dev/source/docs/mavlink-commands.rst
=> add MAVSDK links

mavproxy/source/docs/modules/chat.rst
These changes should be made together with:
* ArduPilot/MAVProxy#1588
=> `wave` is a Python Standard Library module

ardupilot/source/index.rst, common/source/docs/common-choosing-a-ground-station.rst
- Add link to all GCSes
- Reordered Link Pan
Testing:
Full wiki build tested locally on linux
=> GCS: Updated to link to all GCS

sub/source/docs/modes.rst
- stop dashes in the table from rendering as dots
- add ACRO mode parameters
- rearrange mode-specific parameters to match the order of the table
=> Sub: Update mode params

plane/source/docs/configuration-files-for-common-airframes.rst
I dont think this page has been updated in a long time, It talks about APM controllers .
=> APM references in documentation.

sub/source/docs/pilot-control.rst
Relevant info for people trying to adjust how their vehicle performs in response to pilot input.
Considered from [this forum thread](https://discuss.bluerobotics.com/t/ardusub-control-response-issue/20915).
Relevant section preview:
=> Sub: cover pilot control responsiveness configuration

common/source/docs/common-advanced-configuration.rst, common/source/docs/common-network-capture.rst, common/source/docs/common-network.rst
https://github.com/ArduPilot/ardupilot/pull/30637
=> document network capture

dev/source/docs/porting.rst
=> update porting document

dev/source/docs/porting.rst
noticed some typos whilst reviewing.  A format error remains in the code block (not sure rst supports hyperlinks within codeblocks, tbh)
=> update porting document: minor typos
