common/source/docs/common-stores.rst

VR store had broken link that sphinx did not understand

fixing VR store link

---

plane/source/docs/arming-your-plane.rst

It is possible to disarm in plane since this PR: ArduPilot/ardupilot#2565
Aslo ARMING_DIS_RUD parameter changed to ARMING_RUDDER.

Update due to new functionality

---

common/source/docs/common-history-of-ardupilot.rst

Rework of https://github.com/ArduPilot/ardupilot_wiki/pull/321.

Common History of APM: Add some milestones

---

copter/source/docs/pdf-guides.rst

fixing links to PDF guides, Issue #339

---

common/source/docs/common-downloads_advanced_user_tools.rst
common/source/docs/common-downloads_developer_tools.rst
common/source/docs/common-downloads_firmware.rst
common/source/docs/common-mouse-based-optical-flow-sensor-adns3080.rst
common/source/docs/common-ppm-encoder-8-channel-standalone-encoder.rst
common/source/docs/common-ppm-encoder-apm2x-atmega32u2.rst
common/source/docs/common-ppm-encoder.rst
common/source/docs/common-px4flow-overview.rst
common/source/docs/common-sounds-pixhawkpx4.rst
common/source/docs/common-tarot-gimbal.rst
common/source/docs/common-ublox-gps.rst
copter/source/docs/safety-multicopter.rst

placing files on their correct locations...

Major fix for download links 

---

dev/source/index.rst

fix broken link

---

common/source/docs/common-autopilots.rst

Fix to PR #398
Add PXF mini to autopilots list

Common autopilots: Add PXFMini board

---

common/source/docs/common-autopilots.rst

Besides the changes proposed here, @rmackay9 , @magicrub, @hamishwillee, what do you think about ordering solutions alphabetically?

Common autopilots: separate open from close

---

plane/source/docs/fbwa-mode.rst

fixed typo

---

plane/source/docs/quadplane-overview.rst

"ddefault" changed to "default"

small typo in documentation

---

copter/source/docs/what-is-a-multicopter-and-how-does-it-work.rst

Apostrophes are only required for it has or it is.  See: http://www.its-not-its.info/

improved grammar

---

common/source/docs/common-geotagging-images-with-mission-planner.rst

Fix the left alignment issue introduced by #481

fix left aligned images

---

common/source/docs/common-electro-permanent-magnet-V3.rst
common/source/docs/common-optional-hardware.rst

Fix lots of minor typos. Small reorg of content. Make video from link to embed.

Tidy up opengrab docs

---

common/source/docs/common-choosing-a-ground-station.rst

Added UgCS ground control software to the list with a description and an image because UgCS also supports Ardupilot.

Added UgCS ground control software

---

dev/source/docs/testing-with-replay.rst

Fixes to Replay Instructions (MAVProxy)

---

dev/source/docs/learning-ardupilot-uarts-and-the-console.rst

HAVE_OS_POSIX_IO became HAL_OS_POSIX_IO

Update on Learning ArduPilot - UARTs and the Console

---

dev/source/docs/building-px4-with-make-on-mac.rst

Add additional MacOS install env step for xcode

Mac OS install step

---

planner2/source/docs/installation-for-linux.rst

Updated Linux version to 16.04 LTS for pre-built binaries. but older versions are supported with correctly updated dependencies.

Update Linux Version to 16.04 LTS

---

copter/source/docs/introduction.rst

Some general ammendments are suggested, largely related to removal of Dronecode references and some minor terminology tweaks.

General update / review post Dronecode split

---

common/source/docs/common-stores.rst

Hey guys,
Just adding my store to the list.
Cheers!

Added Bask Aerospace to stores list

---

common/source/docs/common-mauch-power-modules.rst

Space in markup was missing for proper display of link

Markup fix for link

---

common/source/docs/common-accelerometer-calibration.rst

Spoke with Randy, and the warning is no longer valid

Remove deprecated warning

---

dev/source/docs/plane-sitlmavproxy-tutorial.rst

In new version of ArduPlane code the parameter path has changed.

update param load path

---

common/source/docs/common-stores.rst

Might help people looking for these products.

include a brief description of what we sell

---

copter/source/docs/indoor-flying.rst

This is a follow up to https://github.com/ArduPilot/ardupilot_wiki/pull/625 by adding links to params and values. @rmackay9 and @FabianL77 please confirm this is correct

added links to params and values

---

dev/source/docs/sitl-native-on-windows.rst

Minor update to cygwin installation instructions.

procps selection in cygwin installer is procps-ng

---

common/source/docs/common-mission-planner-bluetooth-connectivity.rst
planner/source/docs/mission-planner-language-translations.rst

Correction Guy (http://knowyourmeme.com/memes/correction-guy) says
"you're".

fix a couple of grammar mistakes

---

common/source/docs/common-stores.rst

Added unmanned tech link to list of stores as it a good UK shop for supplies

Added UnmannedTech Shop Link

---

common/source/docs/common-frsky-mavlink.rst

Up to date info on open source projects

Up to date info on open source projects

---

plane/source/docs/loiter-mode.rst

Plane: fix link and syntax in Loiter Mode

Plane: fix link and syntax in Loiter Mode

---

dev/source/docs/code-overview-adding-a-new-parameter.rst

Dev: add parameter fix/add link

Dev: add parameter fix/add link

---

dev/source/docs/apmcopter-programming-libraries.rst

added missing description of AC_AttitudeControl library.

AC_AttitudeControl Missing Description

---

common/source/docs/common-beagle-bone-blue.rst

fixed 2 typos

---

dev/source/docs/using-gazebo-simulator-with-sitl.rst

re-positioned description of a common (install and build from source/ install from pre-built packages) requirement up and fixed typos.

SITL Gazebo Description re-position & few small changes

---

dev/source/docs/using-gazebo-simulator-with-sitl.rst

fixed un-aligned code for note 2nd from end.

fixed Note not showing up properly

---

dev/source/docs/using-gazebo-simulator-with-sitl.rst

sorry about the small commits. as i see it is on wiki page there was some glitch.
so this is quick fix.

More spacing and hyperlink error fix

---

dev/source/docs/sitl-simulator-software-in-the-loop.rst
dev/source/docs/soaring-sitl-with-xplane.rst

... including tying it into the rest of the ArduPilot documentation tree!

small tweaks to the soaring SITL documentation

---

common/source/docs/common-piksi-multi-rtk-receiver.rst

Common: Fixed typo in Piksi GPS page

---

dev/source/docs/making-a-mavlink-wifi-bridge-using-the-raspberry-pi.rst

For those blindly copying and pasting

Fix errors on L#660 (Change Dir) and 669 (Need Privs)

---

copter/source/docs/introduction.rst

Typo, Key features Flexble and customizable

---

dev/source/docs/raspberry-pi-via-mavlink.rst

sudo pip install pymavlink #fails without future
https://github.com/ArduPilot/pymavlink/issues/25

add future to install instructions

---

plane/source/docs/automatic-takeoff.rst

Update Plane: automatic-takeoff.rst

---

common/source/docs/common-positioning-landing-page.rst
common/source/docs/common-uavcan-escs.rst
common/source/docs/common-zubax-gnss-positioning-module-gps-compass-and-barometer.rst

Actualized the documentation entries pertaining to UAVCAN ESC and Zubax GNSS.

ESC and GNSS doc update

---

plane/source/docs/advanced-failsafe-configuration.rst

Fixed some minor spelling/grammar errors

Fixed some minor spelling/grammar errors

---

common/source/docs/common-rc-transmitter-flight-mode-configuration.rst

Removed wrong entries not pointing to specific articles on dyd
https://github.com/ArduPilot/ardupilot_wiki/issues/673

Removed wrong entries

---

common/source/docs/common-frsky-repurposed.rst
common/source/docs/common-frsky-telemetry.rst

this commit fixes a number of spelling errors, several of which were
initially reported by Robin Silk.

correct a number of spelling errors

---

dev/source/docs/using-sitl-for-ardupilot-testing.rst

Tested wind on copter and is working

Tested Wind on Copter

---

common/source/docs/common-commercial-support.rst

Updated the information for my company

Updated Element Aero company Info

---

common/source/docs/common-zubax-gnss-positioning-module-gps-compass-and-barometer.rst

We're overhauling our web infrastructure, hence some external links need updating. Thanks!

Updated links to Zubax GNSS

---

copter/source/docs/solo_arducopter_upgrade.rst
copter/source/index.rst

Updated links for purchasing the Green Cube and and updated the nav per Randy's suggestion.

SOLO WIKI: Updates to links

---

common/source/docs/common-stores.rst

3DXR - Pixhawk 2.1 Distributor in UK and a great source for 18650 Battery Pack

Added 3DXR - Pixhawk 2.1 Distributor in UK

---

plane/source/docs/channel-output-functions.rst

this is a PR as a demo for how to edit ArduPilot documentation

Plane: added docs on per-channel rc pass-thru mapping

---

dev/source/docs/building-px4-with-make.rst

Updated the GitHub for Windows to the new Github Desktop, updating name and URL.

Updated the GitHub for Windows

---

dev/source/docs/building-for-bebop-on-linux.rst

Update "make bebop" to waf
closes https://github.com/ArduPilot/ardupilot/issues/7093

Update "make bebop" to waf

---

common/source/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.rst

The ATT message details were outdated. I changed the names of the parameters, fixed some typos and added ErrRP and ErrYaw.

Update ATT message details for Copter

---

dev/source/docs/building-ardupilot-onwindows10.rst

added a few additional tips from my install

added a few additional tips from my install

---

dev/source/docs/where-to-get-the-code.rst

fixed double word typo and replaced with a more contextually accurate word.

Minor grammatical update

---

plane/source/docs/plane-3-7-to-3-8-migration.rst

Intended to resolve https://github.com/ArduPilot/ardupilot_wiki/issues/999
Haven't tested to check that the warning renders (can someone do this please).

3.8 downgrade warning

---

common/source/docs/common-gps-septentrio.rst

Add link to M2
Setup parameters
Warning about a mission planer issue

Update Septentrio setup instructions

---

dev/source/docs/building-for-navio2-on-rpi3.rst

Add one required dependency to build on RPI3 on Stretch

Add one required dependency

---

common/source/docs/common-stores.rst

Added Jester Drones webshop

---

dev/source/docs/building-ardupilot-onwindows10.rst

In the original page, the command is outside the code area because of some unexpected spaces in the code.
I'm so sorry for not previewing the page in the previous pull request. This time is good.

delete the unnecessary spaces

---

dev/source/docs/code-overview-scheduling-your-new-code-to-run-intermittently.rst

The Hertz notation is Hz.
I changed hz to Hz according to the notation.

Dev: Change unit notation of Hertz to Hz

---

common/source/docs/common-frsky-passthrough.rst

FlightDeck is not free, I am proposing the inclusion of a free alternative.

Include a free lua script alternative

---

dev/source/docs/making-a-mavlink-wifi-bridge-using-the-raspberry-pi.rst

Update isc-dhcp-server file contents to edit from "interfaces" to "interfacesV4"

Update isc-dhcp-server file contents to edit

---

plane/source/docs/flight-modes.rst

Links didn't work in tables, and bulleted list below arranged in alphabetical order.

Flight mode chart correction

---

dev/source/docs/solo.rst

Source: https://dev.3dr.com/starting-network.html

solo.rst Update note on default root password

---

dev/source/docs/code-overview-adding-a-new-mavlink-message.rst

Add explanation of how to extend mavproxy to make use of a custom message.

Update new mavlink message description

---

dev/source/docs/job-openings.rst

up-to-date on positions

---

ardupilot/source/index.rst

Some organizational clarifications and updates to help new users understand what Ardupilot is.

Wiki Home Page Update

---

ardupilot/source/index.rst

Attempting to fix the 2nd column - firmware that isn't displaying properly.

Home Page Quick Format Change

---

common/source/docs/common-emlid-edge.rst

- add flight video
- add links to the docs and shop

Update Emlid Edge docs

---

plane/source/docs/guide-tailsitter.rst

Fixed Link in Tailsitter Page

---

dev/source/docs/plane-sitlmavproxy-tutorial.rst

* fix link
* fix param show sim* format

plane-sitlmavproxy-tutorial.rst: fix link

---

copter/source/docs/skyrocket.rst

hopefully? I bascially rolled back what rmackay9 had before

skyrocket.rst: Fix sidebar links.

---

common/source/docs/common-mounting-the-flight-controller.rst
common/source/docs/common-stores.rst
common/source/docs/common-thecube-overview.rst
common/source/docs/common-wiki_editing_guide.rst
dev/source/docs/events.rst

* Include Cube in flight controller mounting
* Remove defunct online stores
* Add Cube overview page
* Grammatical change in the wiki editing page
* Updated events page

Small grammatical changes

---

copter/source/docs/traditional-heli-parts-list.rst

Revising requirements for TradHeli

Revising requirements

---

common/source/docs/common-rangefinder-maxbotixi2c.rst

Part of addressing https://github.com/ArduPilot/ardupilot_wiki/issues/1097

wiki-Update common-rangefinder-maxbotixi2c.rst

---

dev/source/docs/style-guide.rst

Reverts ArduPilot/ardupilot_wiki#1066

Revert "Added note for UTF-8 encode."

---

dev/source/docs/building-px4-with-make.rst
dev/source/docs/building-setup-windows.rst
dev/source/docs/building-setup-windows10.rst
dev/source/docs/building-the-code.rst
dev/source/docs/code-overview-adding-a-new-log-message.rst
dev/source/docs/copter-sitl-mavproxy-tutorial.rst
dev/source/docs/git-install.rst
dev/source/docs/git-rebase.rst
dev/source/docs/plane-sitlmavproxy-tutorial.rst
dev/source/docs/porting.rst
dev/source/docs/roadmap.rst
dev/source/docs/rover-sitlmavproxy-tutorial.rst
dev/source/docs/setting-up-sitl-on-linux.rst
dev/source/docs/sitl-native-on-windows.rst
dev/source/docs/sitl-with-xplane.rst
dev/source/docs/using-sitl-for-ardupilot-testing.rst

Change sitl setting to use install script and switch to arducopter by default instead of plane (that need jsbsim)

Fix for dev style, and rewrite sitl setting on linux

---

copter/source/docs/smart-rtl.rst

Answering rmackay9's request
https://github.com/ArduPilot/ardupilot_wiki/issues/1215

Update SmartRTL wiki for max_points handling and failsafes

---

common/source/docs/common-wiki_editing_guide.rst

Move the "preamble" back to the top.

common-wiki_editing_guide.rst:Update based on feedback

---

dev/source/docs/apmcopter-adding-a-new-flight-mode.rst

I think that wiki information is old. Please ignore otherwise.

update source code sample of Copter.h

---

copter/source/docs/esc-calibration.rst

Fixed DShot Link in ESC Calibration Page

---

plane/source/index.rst

Removed outdated announcements and directed users to the discuss forums.
Added a touch of VTOL info.

Update Plane Landing Page

---

copter/source/docs/prearm_safety_check.rst

I THINK...
RC minimum value includes 1300.
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Arming/AP_Arming.cpp#L678
RC maximum value includes 1700.
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Arming/AP_Arming.cpp#L684

Copter: Change effective range of RC

---

plane/source/docs/guide-vtail-plane.rst

Fixed Broken Table
Condensed a few spaces
Removed "your" ownership from just about everything to make it gramatically neutral.

Fixed V-Tail setup page

---

copter/source/docs/ac2_followme.rst

Added appropriate warnings for safety due to altitude mechanism.

Follow Me Mode altitude clarification and warning

---

common/source/docs/common-partners.rst

Update Partners list. Replaces  [#1277](https://github.com/ArduPilot/ardupilot_wiki/pull/1277)

Update partners list

---

copter/source/docs/flight-modes.rst

Added a table with a quick summary of modes.

Flight Mode Overview Table

---

common/source/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.rst

Per this forum post, the step-by-step process might be useful for new users: https://discuss.ardupilot.org/t/downloading-and-reviewing-logs-from-dropbox-or-google/29194/7?u=hunt0r

Add detailed step-by-step

---

common/source/docs/common-dshot.rst

Added correct parameters for plane users to use telemetry ESC's.
Consolidated telemetry section to not repeat topics.
May want additional notes on OneShot and DShot600 from @WickedShell.

Update DShot and Telemetry ESC documentation

---

plane/source/docs/guide-vtail-plane.rst

Sorry for all the PR's - I keep finding little things to correct on the V-Tail page.
Fixed FBWA yaw command to be a roll command - the V-Tail would only work with a yaw damper.
More grammar fixes and consistency.

V-tail improvements

---

dev/source/docs/sitl-simulator-software-in-the-loop.rst

Add underwater vehicle in SITL list.

SITL: Add underwater vehicle item

---

common/source/docs/common-web-apps.rst

DroneDeploy no longer supports Mavlink vehicles

Update of web apps that support ArduPilot

---

common/source/docs/common-web-apps.rst

Updated link to new logo

---

dev/source/docs/building-setup-mac.rst

Update build instructions to reflect using waf. Also point to the automated script.

Tools: Update build instructions

---

dev/source/docs/building-the-code.rst
dev/source/docs/pre-built-binaries.rst

this will be linked from firmware.ardupilot.org

added page on pre-built binaries

---

dev/source/docs/porting.rst

This stumped me while working on my first hwdef file for a new board...until someone told me about it...

added note about cleaning anytime a hwdef file is changed before rebuilding

---

common/source/docs/common-ads-b-receiver.rst
common/source/docs/common-gripper-servo.rst
common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst
common/source/docs/common-telemetry-port-setup-for-apm-px4-and-pixhawk.rst
copter/source/docs/ac2_guidedmode.rst
dev/source/docs/code-overview-adding-a-new-mavlink-message.rst
dev/source/docs/code-overview-adding-support-for-a-new-mavlink-gimbal.rst
dev/source/docs/code-overview-object-avoidance.rst
dev/source/docs/copter-commands-in-guided-mode.rst
dev/source/docs/copter-sitl-mavproxy-tutorial.rst
dev/source/docs/gsoc-ideas-list.rst
dev/source/docs/ros-distance-sensors.rst
rover/source/docs/guided-mode.rst
rover/source/docs/rover-failsafes.rst

As requested by project owners.

Revert mavlink links

---

common/source/docs/common-benewake-tf02-lidar.rst

Added unmannedtech as they sell alot of other ardupilot related stuff too and are a useful resource for supplies (and a ardupilot partner)

Updated Links

---

dev/source/docs/building-for-navio2-on-rpi3.rst
dev/source/docs/building-setup-linux.rst
dev/source/docs/copter-sitl-mavproxy-tutorial.rst
dev/source/docs/git-clone.rst
dev/source/docs/plane-sitlmavproxy-tutorial.rst
dev/source/docs/setting-up-sitl-on-linux.rst

I am lazy, so code once and copy everywhere else ! This should prevent contradiction on different pages.

make linux instruction more common

---

common/source/docs/common-omnibusf4pro.rst

- Add picture to remove diode
- Add note on PPM / SBUS PADS
- Add wiring schema
- Add zadig for windows user otherwise in dfu mode, board could not be detected

Complete documentation of Omnibus F4 V3 pro

---

plane/source/docs/automatic-landing.rst

Fix typo in Automatic Landing documentation

---

common/source/docs/common-partners.rst

Add Hexsoon to partner  page

---

copter/source/docs/parachute.rst

Just one link that was broken here. I think this is correct replacement.

Fix broken link in parachute

---

common/source/docs/common-archived-topics.rst
common/source/docs/common-common-airframe-builds.rst
copter/source/docs/hoverthings-flip-sport-quadcopter.rst

This build would probably work but airframe is no longer available and it  uses both Pixhawk 1 and PX4FMU/PX4IO (no longer supported). 
This does mean we don't have many detailed airframe builds. Would be good to encourage some more?

Archive the Hoverthings Flip Sport detailed build

---

copter/source/docs/introduction.rst

Fixed typo: wapoints => waypoints

Fixed typo in intro: wapoints => waypoints

---

dev/source/docs/google-code-in-task-list.rst

Added new wiki page for the Code-In tasks

Created page for Code-in Tasks

---

common/source/docs/common-partners.rst

I couldn't find a website other than Alibaba, so used that.

added Hangzhou QiFei Intelligence

---

common/source/docs/common-radio-control-calibration.rst

Closes https://github.com/ArduPilot/ardupilot_wiki/issues/1160

Fix parameter name (ArduPlane)

---

common/source/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.rst

Also used input from this thread:
https://discuss.ardupilot.org/t/ctun-dalt-question/14863

Matched CTUN to what is visible in Mission Planner

---

common/source/docs/common-omnibusf4pro.rst

Camera trigger parameter for Omnibus F4 pro

Add how to trigger a camera

---

common/source/docs/common-dshot.rst

https://github.com/ArduPilot/ardupilot/commit/83f4f5c347007c4ec9068497fdc5f913b319d72b

add SERVO_BLH_POLES parameter documentation to common-dshot.rst

---

planner2/source/docs/installation-for-linux.rst

Fixes https://github.com/ArduPilot/ardupilot_wiki/issues/1139

Update link for APMPlanner "Create a desktop icon"

---

dev/source/docs/trademark.rst

words to indicate an application is underway.  Need to remember to update this when the process is complete.

wiki: update trademark.rst

---

dev/source/docs/turnkey-companion-computer-solutions.rst

I have added UAVcast-Pro to the Companion Turn Key soltion page. 
http://ardupilot.org/dev/docs/turnkey-companion-computer-solutions.html

Added UAVcast-Pro Turnkey solution

---

common/source/docs/common-omnibusf4pro.rst

Someone blew up their board trying to apply power to this pin.

Add info about VCC pin next to RXin

---

dev/source/docs/using-sitl-for-ardupilot-testing.rst

Fixed spelling on dev sitl page

Dev: fix spelling

---

dev/source/docs/building-setup-windows-cygwin.rst

wiki: small command fix

---

dev/source/docs/ros-cartographer-slam.rst

I'm trying to follow the wiki to do SLAM with Cartographer.
I think that it would be better if you changed your home directory to $ HOME.

wiki: small fix spelling on ros-cartographer-slam

---

dev/source/docs/turnkey-companion-computer-solutions.rst

I've added the turnkey Companion Computer I produce
Thanks a lot for your work on Ardupilot

Added Alfonce Remote Gateway By Dronotique

---

dev/source/docs/how-the-team-works-development-fund.rst

Update "How the team works" funding date

---

common/source/docs/common-ice.rst

Correct Typos on ICE page

---

common/source/docs/common-wiki-editing-setup.rst

This is mostly a test of the workflow for submitting PRs from my own repo

Common: fix wiki-editing-setup links for view results

---

dev/source/docs/sitl-with-realflight.rst

sitl-with-realflight: Update FlightAxis Link setup instructions

---

Vagrantfile
antennatracker/source/conf.py
ardupilot/source/conf.py
copter/source/conf.py
dev/source/conf.py
plane/source/conf.py
planner/source/conf.py
planner2/source/conf.py
rover/source/conf.py

update sphinx to lastest
update youtube plugin repo and plugin
replace pngmath with imgmath because of deprecation
update copyright date to 2019

General update

---

common/source/docs/common-diagnosing-problems-using-logs.rst
common/source/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.rst
common/source/docs/common-optitrack.rst
dev/source/docs/building-setup-linux.rst
dev/source/docs/git-install.rst

include git install
fix some warning in common

Include git install in linux instruction

---

common/source/docs/common-pixhackV5-overview.rst

Updated info for release CUAVv5

Updated info for release CUAVv5

---

common/source/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.rst

Removed few outdated fields and added the ones currently seen when reviewing log data, basing on what can be seen in the code and peterbarker's explanations: https://discuss.ardupilot.org/t/help-understanding-a-pm-performance-monitoring-log-data/37100 . Also removed any fixed numbers that depend on scheduler loop rate.

Updated "PM (performance monitoring)" message details

---

planner/source/docs/mission-planner-ground-control-station.rst

for reference:
https://discuss.ardupilot.org/t/what-does-wireless-telemetry-connection-actually-indicate/37310
and
https://github.com/ArduPilot/MissionPlanner/blob/ebb2745dda9113aa5616d6e99cbc64441da3e355/Controls/ConnectionStats.cs#L70

mission-planner-ground-control-station.rst: fix link quality

---

planner/source/docs/mission-planner-installation.rst

I did a screen capture video showing how to install Mission Planner.  This also shows how to install older or multiple versions of Mission Planner.  Finally, it shows how to set the log path so that tlogs and dataflash logs are saved appropriately.

Add video showing how to install Mission Planner.

---

dev/source/docs/plane-commands-in-guided-mode.rst

left over from https://github.com/ArduPilot/ardupilot_wiki/pull/1580

Dev: remove mention of MAV_CMD_CONDITION_CHANGE_ALT in plane section

---

common/source/docs/common-partners.rst

common-partners.rst: fix holybro URL

---

common/source/docs/common-holybro-kakutef7aio.rst
plane/source/docs/automatic-landing.rst

close https://github.com/ArduPilot/ardupilot_wiki/issues/1347

warning fix on plane and common

---

dev/source/docs/setting-up-sitl-using-vagrant.rst

Signed-off-by: Dr Nic Williams <drnicwilliams@gmail.com>

sim_vehicle.py -v ArduCopter flag is not optional

---

common_conf.py
update.py

Tiny cleanup of two python scripts to remove whitespace from ends of lines.

remove invisible trailing whitespace

---

common/source/docs/common-pixhawk-and-px4-compatible-rc-transmitter-and-receiver-systems.rst

Signed-off-by: Dr Nic Williams <drnicwilliams@gmail.com>

update links to frsky-rc.com transmitter/receiver products

---

dev/source/docs/ros-slam.rst

Giving the advice to run Hector SLAM on a different more powerful machine and not on the Pi.

Update ros-slam.rst for RaspberryPi

---

dev/source/docs/building-setup-mac.rst

Added instruction to install the headers on Mojave

Added instruction to install the headers on Mojave

---

copter/source/index.rst

Adding link to simplified Chinese doc

Adding link to simplified Chinese doc

---

plane/source/index.rst

Adding link to simplified Chinese docs

Adding link to simplified Chinese docs

---

dev/source/docs/building-setup-windows-cygwin.rst
dev/source/docs/building-setup-windows.rst
dev/source/docs/setting-up-sitl-on-linux.rst

Based on comments in https://github.com/ArduPilot/ardupilot/issues/10717, I've made some small tweaks to the install instructions to make them clearer.

Dev: Cleaned up environment install instructions

---

dev/source/docs/ros-aruco-detection.rst
dev/source/docs/ros-slam.rst

Style fixs

---

plane/source/docs/guide-tailsitter.rst
plane/source/docs/qacro-mode.rst
plane/source/docs/quadplane-flight-modes.rst

still needs additions for the new tailsitter class and control mode

Plane wiki: add QACRO mode and "copter" tailsitters and bodyframe-roll mode

---

common/source/docs/common-rtf.rst

Added new French DGAC Certified drone Alfonce H960 from Dronotique

Add new drone

---

dev/source/docs/building-setup-linux.rst
dev/source/docs/building-setup-mac.rst
dev/source/docs/building-setup-windows-cygwin.rst
dev/source/docs/building-setup-windows10.rst

Updated pre-install script links as per https://github.com/ArduPilot/ardupilot/pull/10759 (will need to wait for this PR to go in first)

Dev: Updated links to pre-req install scripts

---

plane/source/docs/differential-spoilers.rst
plane/source/docs/plane-configuration-landing-page.rst

Corrects typo, @tridge I think I have corrected it the right way? Thanks

Plane: update d-spoiler page

---

dev/source/docs/building-setup-windows-cygwin.rst
dev/source/docs/building-setup-windows10.rst

Based on the comments from here: https://discuss.ardupilot.org/t/cygwin-eclipse-build-issues/41753
I've updated the list of Cygwin packages to match the once in the Ardupilot Tools/environment_install and added a section to how to clone the git repo.

Cywin install updates

---

dev/source/docs/building-setup-windows10.rst

follow-up Ardupilot script PR https://github.com/ArduPilot/ardupilot/pull/11240

update WSL install

---

planner/source/index.rst

remove "Tip" about the exit from dronecode - old news, no longer relevant.

MissionPlanner: Update index.rst

---

common/source/docs/common-rtf.rst

Added Bask Aerospace Vehicles

---

common/source/docs/common-furiousfpv-f35.rst
common/source/docs/common-matekf405-wing.rst
common/source/docs/common-omnibusf4pro.rst
common/source/docs/common-omnibusnanov6.rst

Adding comment about using Dshot on the more popular OSD integrated FC boards. This has been coming up in the RCG support forums.

Add comments about Dshot capability

---

common/source/docs/common-cameras-and-gimbals.rst

tarot website down, linked hardware item outdated

common-cameras-and-gimbals.rst: remove dead link

---

dev/source/docs/using-sitl-for-ardupilot-testing.rst

implements #1428 ping @khancyr

dev using-sitl-for-ardupilot-testing.rst: add link to param table

---

common/source/docs/common-osd-overview.rst

common-osd-overview.rst: add fw version ref

---

copter/source/docs/acro-mode.rst
copter/source/docs/rtl-mode.rst
copter/source/docs/stabilize-mode.rst

implement #1461

---

common/source/docs/common-logs.rst

common-logs.rst: implement issue #1469

---

common/source/docs/common-esp8266-telemetry.rst

common-esp8266-telemetry: add SSID / pwd

---

dev/source/docs/using-gazebo-simulator-with-sitl.rst

Adding sim_vechicle.py path due questions as in the issue #1714

[minor enhance] Adding path to the example

---

common/source/docs/common-tarot-gimbal.rst

https://github.com/ArduPilot/ardupilot_wiki/pull/1767 ping @rmackay9

common-tarot-gimbal.rst: add retired note and remove dead reference

---

copter/source/docs/failsafe-battery.rst

Solves https://github.com/ArduPilot/ardupilot_wiki/issues/1742

Failsafe clarification during land or RTL.

---

common/source/docs/common-logs.rst

common-logs.rst: fix the links

---

common/source/docs/common-3dr-radio-advanced-configuration-and-technical-information.rst

Due to issue #1657, I checked Sik support for MAVLINK versions[1].
So, I am updating the information.
[1] https://discuss.ardupilot.org/t/sik-radios-vs-mavlink-versions/43282/2?u=brunoolivieri
regards,

[update] Sik support for MAVLINK versions.

---

common/source/docs/common-logs.rst

this fixes link appearance, toctree and menu references
https://github.com/ArduPilot/ardupilot_wiki/pull/1777 for reference

common-logs.rst: fix toctree and headline permalinks

---

dev/source/docs/apsync-intro.rst

APsync IP and port for connections as informed in issue #1147 and argued in issue #1710 item 2.
Render verified on Vagrant.

[minor add] Simple information insertion due to issue #1147 and issue1710 part.2

---

common/source/docs/common-history-of-ardupilot.rst
dev/source/docs/code-overview-scheduling-your-new-code-to-run-intermittently.rst
dev/source/docs/code-overview-sensor-drivers.rst

ArduCopter.cpp has been merged into Copter.cpp
Also fixed a few line numbers related to scheduler

All: Rename ArduCopter.cpp to Copter.cpp

---

dev/source/docs/lua-scripts.rst

A rough first pass, will need to create a generator for the API docs in the future, but this should at least be more complete then the current docs.

Update scripting documentation to be more current

---

dev/source/docs/setting-up-sitl-on-linux.rst

This fix to remove the warning message appear when you upgrade

Replacing sudo with --user

---

common/source/docs/common-autopilots.rst

Simple correction from PR #1809  and wiki meeting.

[fix] Rover last version of firmware for APM2

---

common/source/docs/common-wiki-editing-submitting-changes.rst

I had problems with the provided command parameters. So, as I am using the updated Git version, I am suggesting some adjusting for the command that works for me in may PRs.

[minor fix] Wiki edit guide command

---

common/source/docs/common-wiki-editing-setup.rst

a little more detail to help linux/sphinx/python newbies when setting up the environment in a native Linux machine (which caused me some issues  when installing it)

Added some helpful comments to Linux setup for newbies.

---

common/source/docs/common-rangefinder-objectavoidance.rst

I found that the URL link was broken.

Copter: Change URL link

---

plane/source/docs/channel-output-functions.rst

channel-output-functions: fix flaperon references

---

plane/source/docs/apms-failsafe-function.rst

Also updating Flying a Quadplane section

Update failsafe actions for Quadplane modes

---

plane/source/docs/quadplane-flying.rst

The Plane Failsafe Function wiki section will also be updated to include Quadplane behaviour

Update Quadplane behaviour in FS

---

common/source/docs/common-zed.rst
dev/source/docs/apsync-intro.rst

This has a few links I'm still trying to track. WIP until that is done.

[WIP] Fix broken links to Zed stereo camera

---

dev/source/docs/setting-up-sitl-on-windows.rst

changes I had to make to run this tutorial run

changes I had to make to run this tutorial run

---

plane/source/docs/flight-modes.rst

Clarifies what modes expect TX input.

Plane: Add a Need TX column and LAND mode

---

copter/source/docs/ac_tipsfornewpilots.rst

Fixing a dead link to Hobbyking's website - reported in #1643

Copter: Fix dead link to Hobbyking website

---

dev/source/docs/ros-object-avoidance.rst
dev/source/docs/ros-rviz.rst

catkin -> catkin_ws
https -> http

Cartographer: fix workspace name and protocol

---

update.sh

I'm not sure if this works since I don't know how Python packages are installed on our server, but this is the basic idea.

update.sh: install theme upgrade

---

dev/source/docs/lua-scripts.rst

Requires https://github.com/ArduPilot/ardupilot/pull/11740 for the behavior to be consistent with what's described here.

lua-scripts: Update battery docs

---

common/source/docs/common-rfd900.rst

- Updated order of information
- Added additional headings
- Updated descriptions
- Added reference to Bask Aerospace AeroLink products
*Not sure if I damaged JDrones kit image or how to add my own?

Updated radio kit information

---

common/source/docs/common-geotagging-images-with-mission-planner.rst

Added commercial solution for geotagging - Entire in file 
common-geotagging-images-with-mission-planner.rst

Updated geotagging solutions

---

common/source/docs/common-omnibusf7.rst

@rmacky9 Randy, what is the best way to approach the info about FRsky Sport connection since its not in stable releases (as far as I know) yet, and will appear at different times for different vehicles?

HWDEF: update OmnibusF7 per ninja-zx11

---

dev/source/docs/simulation-2.rst
dev/source/docs/sitl-with-airsim.rst

Adds setup & usage page for AirSim
WIP

Dev: Add page for AirSim Simulator

---

dev/source/docs/sitl-with-airsim.rst

WIP
Need to add more some more things such as demo video

SITL: Additions and fixes for Airsim

---

dev/source/docs/sitl-with-airsim.rst

Also correct instructions on running on different computers and ports
Would be better to have this go in after the Lidar, RC PR is merged in order to remove extra steps for fetching the branch.
Also, need to add a video for multi-vehicle simulation which will hopefully make it clearer how to use it

Dev: Add info about Multi-Vehicle sim with AirSim

---

dev/source/docs/sitl-with-airsim.rst

https://github.com/ArduPilot/ardupilot/pull/11835 has been merged into master, therefore removing the instructions to fetch the branch

Dev: Remove branch instructions, extra fixes

---

dev/source/docs/plane-sitlmavproxy-tutorial.rst
dev/source/docs/using-sitl-for-ardupilot-testing.rst

based on my ramp up to using quadplane SITL where I got stuck for several days...some expansion of details

Update SITL docs with guided takeoff and frame option

---

copter/source/docs/tuning-process-instructions.rst

General typo correction, no content changes

Correcting some typos

---

common/source/docs/common-simplebgc-gimbal.rst

Adjust of some lists, adding a warning and repositioning some text, etc.  Also rephrasing somethings.

SimpleBCG some formatting and layout fixies.

---

dev/source/docs/lua-scripts.rst

Minimal changes to remove build warnings

Remove build warnings

---

plane/source/docs/calibrating-an-airspeed-sensor.rst

Updating manual calibration formula

---

plane/source/docs/fixed-wing-faq.rst
plane/source/docs/fpv-plane.rst
plane/source/docs/manual-mode.rst
plane/source/docs/quadplane-esc-calibration.rst
plane/source/docs/quadplane-flying.rst
plane/source/docs/quadplane-frame-setup.rst

working on non-common plane specific build errors...all tested in Sphinx
minor rewording on a few fixes since refs dont exist any more...
other fixes in progress
will merge this tomorrow if no one objects since its minor and tested...

eliminate several wiki build errors for plane

---

plane/source/docs/inverted-flight.rst

fix inverted flight page build error and deprecated param

fix wiki build error and update

---

plane/source/docs/quadplane-building.rst

This gave me fits on my Z-84 quadplane conversion...took a few days to figure the issue out

Added tip about yaw impact of motor miss-alignment

---

plane/source/docs/automatic-flaps.rst
plane/source/docs/fixed-wing-faq.rst
plane/source/docs/flaperons-on-plane.rst

part of fixing wiki build errors
obsolete refs removed and text corrected to new params

fix flaperon and crow descriptions and build errors

---

copter/source/docs/acro-mode.rst

Fix broken parameter reference due issue #1869.

Fix broken parameter reference

---

copter/source/docs/tuning-process-instructions.rst

Fix build warning due issue #1869.

Fixing links

---

dev/source/docs/building-setup-windows-cygwin.rst

"cygwin packets" should be "cygwin packages"

Fixed typo.

---

copter/source/docs/ac2_simple_geofence.rst

Line 81: 'loose' changed to 'lose'
Line 84: 'beahviour' changed to 'behaviour'

Spelling mistake fixed

---

dev/source/docs/lua-scripts.rst

This requires https://github.com/ArduPilot/ardupilot/pull/12055 to be accurate.

Dev: Add more Lua docs

---

dev/source/docs/lua-scripts.rst

Fixes typo @rmackay9 found in #1911

dev: fix type of lua vector3f

---

common/source/docs/common-autopilots.rst
common/source/docs/durandal-overview.rst

I need to iterate and add some additional images, but this is enough to get started

Initial documentation for Holybro Durandal H7 flight controller

---

copter/source/docs/sport-mode.rst

Updating parameter references in Sport mode. (Copter)

Update parameter references

---

planner/source/docs/mission-planner-installation.rst

Fix a broke internal reference and also a build warning listed in issue #1869.

M. Planner: Fix link

---

common/source/docs/common-rpm.rst
rover/source/docs/wind-vane-rpm.rst

This links to the new RPM documentation from the RPM windvane driver page

 Rover: windvane: link to new RPM docs

---

common/source/docs/common-rpm.rst

The link to the Arduino Debug tool was previously to my personal repo.
Now that it has been merged into master, I am updating the link in the
Wiki.

COMMON-RPM-SENSOR: Updated link to debug tool.

---

copter/source/docs/traditional-helicopter-connecting-apm.rst

Copter: Fix build warning (title mark)

---

copter/source/docs/failsafe-battery.rst

Copter: Fix build warning (parameters)

---

rover/source/docs/wind-vane-MD-rev-p.rst

Rover: quick fix: Title is to short

---

common/source/docs/common-archived-topics.rst
common/source/docs/common-autopilots.rst
common/source/docs/common-baro-temp-comp.rst
common/source/docs/common-cameras-and-gimbals.rst
common/source/docs/common-cuav-v5nano-overview.rst
common/source/docs/common-cuav-v5plus-overview.rst
common/source/docs/common-non-gps-navigation.rst
dev/source/docs/lua-scripts.rst

no content change...this fixes almost all TOC errors (assuming previous PRs are merged)....the "common-partners-program" document does not fit into any TOC tree that I can find...its just a link from the "common-partners' page....suggestions on what to do with it to eliminate the error are welcomed...

fix wiki build errors: TOC issues

---

dev/source/docs/turnkey-companion-computer-solutions.rst

Add XBStation Turnkey Companion Computer Solutions to http://ardupilot.org/dev/docs/turnkey-companion-computer-solutions.html

Add XBStation Turnkey Companion Computer Solutions

---

common/source/docs/common-fpv-first-person-view.rst

Updated component availability and expanded warnings on regulations and licensing

Update FPV page

---

common/source/docs/common-gripper-servo.rst
common/source/docs/common-pxfmini-wiring-quick-start.rst
common/source/docs/common-rcoutput-mapping.rst
common/source/docs/common-simplebgc-gimbal.rst

remainder of plane wiki build errors that I can fix at this time...will advice on remaining handful from Sphinx expert since I cant get them to resolve in the same way that works elsewhere...

wiki build error corrections

---

dev/source/docs/code-overview-adding-a-new-parameter.rst

Add @rmackay9 's comments from https://github.com/ArduPilot/ardupilot/pull/11795#issuecomment-524195797 as documentation on how to migrate parameters between releases

Add description of how to migrate parameters between releases

---

dev/source/docs/rover-adding-a-new-drive-mode.rst

New mode is no longer declared in "defines.h". It is now declared it mode.h itself. This PR fixes it.

New mode is no longer declared in "defines.h"

---

common/source/docs/common-mission-planning.rst
common/source/docs/common-terrain-following.rst
common/source/docs/common-transmitter-tuning.rst
copter/source/docs/failsafe-battery.rst
copter/source/docs/flight-modes.rst
copter/source/docs/quick-start-guide.rst
copter/source/docs/terrain-following.rst
copter/source/index.rst

several TOC related errors.....starting work on copter build errors....
no content change

fix copter wiki build errors

---

dev/source/docs/learning-the-ardupilot-codebase.rst

Dev: Fix DroneKit URL

---

dev/source/docs/sitl-native-on-windows.rst

Small advice due to the conversation in issue #521.

Dev: Cygwin instalation tip

---

copter/source/docs/sport-mode.rst

Fix SportMode wiki build errors

---

copter/source/docs/loiter-mode.rst

Fix Loiter Mode page wiki build errors

---

copter/source/docs/landing-gear.rst

fix landing gear wiki build errors

---

rover/source/docs/rover-px4-quickstart.rst

fix rover wiki build error

---

copter/source/docs/tricopter.rst

fix tricopter ref to servo function

---

common/source/docs/common-rcmap.rst

Fix rc-map for rover

---

common/source/docs/common-rcoutput-mapping.rst

adding to table...expanding explanation of output type

Add differential thrust in Plane

---

rover/source/docs/rover-object-avoidance.rst

fix build error to related to multiple rangefinders upcoming delayed merge

---

rover/source/docs/rover-object-avoidance.rst

Fix build error in rover

---

common/source/docs/common-appendix.rst
common/source/docs/common-geotagging-drotagx.rst
planner/source/index.rst

final pr to make Mission Planner wiki build clean with no errors...

Planner final wiki build fixes

---

dev/source/docs/sitl-with-airsim.rst

Makes it easier to navigate in the page, which will get bigger when Rover support gets added (hopefully soon :sweat_smile: )
Also added some debugging links and instructions

Dev: Airsim page additions and improvements

---

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst
dev/source/docs/mavlink-commands.rst
dev/source/docs/the-ardupilot-autotest-framework.rst

final build error fix in Dev (that I can fix...the code block error is mystifying me still)

Fix wiki build errors in DEV

---

copter/source/docs/heliquads.rst

Note for HeliQuad

---

dev/source/docs/building-setup-linux.rst

making changes to #1394 per wiki call

Add instructions for using Docker to build ardupilot

---

dev/source/docs/sitl-with-realflight.rst

RF9 comes with a menu item to enable FlightAxis support

dev: switched to RealFlight9 for RealFlight instructions

---

rover/source/docs/acro-mode.rst
rover/source/docs/steering-mode.rst

@rmackay9  I hope I got the STEERING mode explanation correct...after our conversation, I had a few more questions but wrote this up making a few assumptions about how lat accel would be handled...let me know what I guessed wrong...

Expand explanations of ACRO and STEERING modes

---

rover/source/docs/reference-frames-vacutug.rst

Fix minor format issue in Tugboat reference design

---

plane/source/docs/ornithopter.rst
plane/source/docs/plane-configuration-landing-page.rst

split from #1151 , edited, reformatted, links fixed, etc.

Add ornithopter page to plane configurations

---

common/source/docs/common-sik-telemetry-radio.rst

split from #1151, instead of adding several DIY gain directional antennas, or ones no longer sold, just linked to general 900MHz ebay yagi page (its what I use for long range....very effective but has a broad local pattern for close in work so you dont have to rotate it all the time...just when >1.5KM out)

Update link in Sik radio page

---

common/source/docs/common-radio-control-calibration.rst

Also a note about throttle setup with non-spring loaded throttles ...for the Rover site only

Add information about setting up non-spring throttle in Rover

---

common/source/docs/common-omnibusf4pro.rst
common/source/docs/common-omnibusnanov6.rst

tested, merging....will try to update all boards over time with proper assignments

Omnibusf4pro and OmnibusNanoV6 add serial  port assignment documentation

---

common/source/docs/common-acknowledgments.rst
common/source/docs/common-commercial-support.rst
common/source/docs/common-contact-us.rst
common/source/docs/common-donation.rst
common/source/docs/common-downloads_advanced_user_tools.rst
common/source/docs/common-downloads_developer_tools.rst
common/source/docs/common-downloads_firmware.rst
common/source/docs/common-history-of-ardupilot.rst
common/source/docs/common-partners-program.rst
common/source/docs/common-partners.rst
common/source/docs/common-rtf.rst
common/source/docs/common-stores.rst
common/source/docs/common-team.rst
common/source/docs/common-wiki-editing-archiving.rst
common/source/docs/common-wiki-editing-infra-overview.rst
common/source/docs/common-wiki-editing-quick-edit.rst
common/source/docs/common-wiki-editing-setup.rst
common/source/docs/common-wiki-editing-style-guide.rst
common/source/docs/common-wiki-editing-submitting-changes.rst
common/source/docs/common-wiki_editing_guide.rst

remove pages not referenced in Ardupilot site build

Fix Wiki build errors for base index page

---

common/source/docs/common-rcoutput-mapping.rst

addresses issues #965 and #1064

Add detail to RCPassThru function

---

common/source/docs/common-lightware-lw20-lidar.rst

I found the URL link was broken.
I changed the URL.

common: Change URL broken link

---

common/source/docs/common-compass-calibration-in-mission-planner.rst
common/source/docs/common-compass-setup-advanced.rst

addresses #2071 
needs review....

Common Compass: add info on COMPASS_LEARN feature

---

dev/source/docs/apsync-intro.rst

Fix small typo

---

dev/source/docs/ekf2-estimation-system.rst

Update old google groups link to the forums

Update old google groups link to the forums

---

common/source/docs/common-oa-bendyruler.rst
common/source/docs/common-oa-dijkstras.rst

fix wiki build errors introduced with recent doc additions

---

common/source/docs/common-optitrack.rst

fix #2101
Some lines in sample code is missing. thanks @mareschn pointing it out

Optitrack: add missing sample code

---

common/source/docs/common-prearm-safety-checks.rst
copter/source/docs/ac2_simple_geofence.rst
copter/source/docs/arming_the_motors.rst
copter/source/docs/connect-escs-and-motors.rst
copter/source/docs/flying-arducopter.rst
rover/source/docs/arming-your-rover.rst

will move Plane and Rover to this new page once merged....
I guessed at some of the new pre-arm failure messages in terms of their causes...let me know and I can fix as required....

Copter: Refactor prearm to a common page, and update for 4.0

---

common/source/docs/common-web-apps.rst

Update old google groups link to GitHub - web-apps

Update old google groups link to GitHub - web-apps

---

common/source/docs/common-archived-topics.rst
common/source/docs/common-choosing-a-flight-controller.rst
common/source/docs/common-compatible-rc-transmitter-and-receiver-systems-erle-brain-2.rst
common/source/docs/common-erle-brain-linux-autopilot.rst
common/source/docs/common-erle-brain2-wiring-quick-start.rst
common/source/docs/common-pxfmini-wiring-quick-start.rst
common/source/docs/common-pxfmini.rst
common/source/docs/common-qualcomm-snapdragon-flight-kit.rst
copter/source/docs/assembly-instructions.rst
copter/source/docs/build-your-own-multicopter.rst
copter/source/docs/what-you-need.rst
dev/source/docs/building-for-erle-brain-2.rst
dev/source/docs/building-for-erle-brain.rst
dev/source/docs/building-the-code.rst
plane/source/docs/assembly-instructions.rst
rover/source/docs/rover-assembly-instructions.rst

Remove/Archive ERLE references 

---

plane/source/docs/automatic-landing.rst

Last plane specific wiki build error fix...now on to the common files used by plane..

fix wiki build error

---

common/source/docs/common-prearm-safety-checks.rst
plane/source/docs/quadplane-flying.rst

Fix a few wiki build errors that snuck in due to recent commits

---

plane/source/docs/arming-your-plane.rst
plane/source/docs/first-flight-landing-page.rst

Plane: add use of common-prearm-safety-checks file

---

update.py
update.sh

defaults to building all wikis in parallel. You can choose level of
parallism with the --parallel option. Note that this will use quite a
lot of memory

added parallel build of wiki

---

ardupilot/source/index.rst

tweak side menu of Ardupilot

---

plane/source/docs/quadplane-parameters.rst

Quadplane: add Q_OPTIONS bits explanation

---

dev/source/docs/droneapi-tutorial.rst

Update Dronekit links

---

dev/source/docs/git-install.rst

fix build error on building code for Linux page

---

common/source/docs/common-pixhawk-and-px4-compatible-rc-transmitter-and-receiver-systems.rst
common/source/docs/common-pixhawk-wiring-and-quick-start.rst

Update RC receiver information to include IBUS and other expansions

---

common/source/docs/common-advanced-configuration.rst
common/source/docs/common-lua-scripts.rst
dev/source/index.rst

Add LUA scripting as common advance config feature

---

common/source/docs/common-lua-scripts.rst
dev/source/index.rst

Fix build error

---

common/source/docs/common-rcoutput-mapping.rst

winch is Copter function not Rover

Fix Winch output in servo output functions

---

common/source/docs/common-rally-points.rst

Added an appendix documenting what's in a rally point file output by MAVProxy.

Update to common rally points.

---

copter/source/docs/traditional-helicopter-rsc-setup.rst
copter/source/docs/traditional-helicopters.rst

@Hwurzburg per our conversation. Here is a PR for the rotor speed control. As discussed, it provides links to the discuss post on the governor set up. Please format and prepare for merge. Thanks!

Heli RSC setup

---

common/source/docs/common-telemetry-landingpage.rst
common/source/docs/common-uavcast-telemetry.rst

Added SPL telemetry and re-organized telem landing page

---

dev/source/docs/ekf2-estimation-system.rst

Typo in EKF2 Estimation

---

common/source/docs/common-choosing-a-flight-controller.rst

starting update flight controllers and sensors pages in all vehicles...

Expand information on selecting flight controller

---

dev/source/docs/mavlink-requesting-data.rst

dev: add note on REQUEST_MESSAGE to requesting data document

---

plane/source/docs/guide-tailsitter.rst

some features in 4.0 were not yet documented

Update guide-tailsitter.rst for Plane 4.0

---

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst

Remove obviously incorrect wording for MAV_CMD_NAV_LOITER_TO_ALT

---

plane/source/docs/airspeed.rst

Airspeed sensor warning on light sensitivity

---

common/source/docs/common-furiousfpv-f35.rst
common/source/docs/common-holybro-kakutef4.rst
common/source/docs/common-holybro-kakutef7aio.rst
common/source/docs/common-matekf405-wing.rst
common/source/docs/common-matekf405.rst
common/source/docs/common-omnibusf4pro.rst
common/source/docs/common-omnibusf7.rst
common/source/docs/common-omnibusnanov6.rst
common/source/docs/common-speedybeef4.rst

add that PWM/Dshot groups must be same PWM rate or Dshot

---

common/source/docs/common-rally-points.rst
plane/source/docs/rtl-mode.rst

verified technical content with @tridge ...merging
addresses #1085

expand rtl mode in Plane and note in Rally points that alt is relative

---

common/source/docs/common-benewake-tfmini-lidar.rst

Add info on I2C vs UART to Benewake TFmini/Plus

---

common/source/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.rst

COPTER: update log CTUN description

---

plane/source/docs/guide-tailsitter.rst

Update tailsitter with Copter style configurations

---

common/source/docs/common-archived-topics.rst
plane/source/docs/arduplane-setup.rst
plane/source/docs/assembly-instructions.rst
plane/source/docs/first-flight-landing-page.rst
plane/source/docs/first-time-apm-setup.rst
plane/source/docs/plane-3-7-to-3-8-migration.rst
plane/source/docs/plane-configuration-landing-page.rst
plane/source/docs/rc-throw-trim.rst
plane/source/docs/reversing-servos-and-setting-normalelevon-mode.rst
plane/source/docs/servo-functions.rst

First step in Plane site clean up...

Plane: Re-organized setup like Copter...archived a few unused pages

---

dev/source/docs/companion-computers.rst

to replace #1098 since its difficult to rebase

alphabetize companion computers, add Arduino link

---

copter/source/docs/configuring-hardware.rst
copter/source/docs/flying-arducopter.rst
copter/source/docs/initial-setup.rst
plane/source/docs/plane-configuration-landing-page.rst
rover/source/docs/apmrover-setup.rst
rover/source/docs/rover-code-configuration.rst

no content change...just TOC ordering to unify all vehicles into common flow

Unify all vehicles first time setup and config page toc orders

---

common/source/docs/common-advanced-configuration.rst
common/source/docs/common-imu-notch-filtering.rst

no content change...inclusion of Quadplane and link adv config for plane

Add notch filters references in ArduPlane

---

common/source/docs/common-camera-gimbal.rst

Remove broken as discussed in #2222.

Remove link

---

dev/source/docs/buildin-mission-planner.rst

Add additional instructions that I needed to make MP 1.3.68 work on my PC. 
It's your call if you want to include them or not. 
Link to the issue I posted : https://github.com/ArduPilot/MissionPlanner/issues/2213

Add additional instructions

---

copter/source/docs/tuning-process-instructions.rst

…ctions.
Noticed a minor mistake in the post-autotune instructions.  Thus PR switches the numbers around for complete clarity.

Tuning Process Instructions: Minor correction to post-autotune instru

---

dev/source/docs/sitl-with-airsim.rst

Can be merged only after https://github.com/ArduPilot/ardupilot/pull/12930 & https://github.com/ArduPilot/ardupilot/pull/12904 have gone in

Dev: Add info about Airsim, ROS, multi-vehicle

---

planner2/source/index.rst

Update the tip as it presented in Copter and Rover.

Remove DIYdronnes link

---

plane/source/docs/guide-tailsitter.rst
plane/source/docs/quadplane-flying.rst

resubmit of 
4b454e61...41aa2a67 tailsit    -> hwurzburg/tailsit  (forced update)
from my fork

Update tailsit transition info, add note about Q_TRIM_PITCH use

---

common/source/docs/common-leds-pixhawk.rst

Added ESC calibration light sequence to LED info page.

Updated LED Meaning List

---

plane/source/docs/apms-failsafe-function.rst

add new battery failsafes...update actions on all failsafes....update formatting

Update Plane failsafes page

---

dev/source/docs/contributing.rst
dev/source/docs/editing-prs.rst

Will add info on squashing and git-subsystems-split tool to style guide next....
if there is a better way to present the command lines (?code blocks) I can change it...

Add page explaining how to edit someone else's PR

---

plane/source/docs/guide-tilt-rotor.rst

Add hotlinks to tilt-rotor page params

---

plane/source/docs/quadplane-flying.rst
plane/source/docs/quadplane-frame-setup.rst
plane/source/docs/quadplane-support.rst
plane/source/docs/servo-functions.rst

also eliminates extra left menu auto expansions when navigating to certain pages
built tested merged

Reorg tocs for better qplane navigation

---

copter/source/docs/radio-failsafe.rst

@rmackay9  and @Hwurzburg  I am submitting this PR to address an issue regarding radio failsafe with Copter 3.6 or earlier.  Looking for feedback on the warning placement and clarity.
@JoshWelsh  Any inputs on this PR would be appreciated.

Add warning regarding motor interlock for tradheli users

---

copter/source/docs/traditional-helicopter-rsc-setup.rst

So rather than pushing into your repo, Bill, since I squashed all the intervening fixs I didnt want to mess with your repo history...
so you can see the result before its merged into master...
-I squashed into one commit your preceeding stuff
-fixed formatting and broke up some paragraphs...I've built the wiki and it looks good now...
-added a little to the explanations so its clear when we are talking about throttle outputs,etc.
I think this will be a little clearer to heli newbies as well as us old timers that have been out of the loop a while...hopefully...
we can just merge this if you are okay....keeps your commit credit intact also...

Update RSC page

---

dev/source/docs/sitl-with-airsim.rst

To be merged after https://github.com/ArduPilot/ardupilot/pull/13052

Dev: Update AirSim Lidar info

---

common/source/docs/common-ice.rst
common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst

Need to add VTOL_LAND and VTOL_TAKEOFF also...on my list

Add Plane DO_ENGINE_CONTROL and Q_LAND_ICE_CUT

---

common/source/docs/common-compass-calibration-in-mission-planner.rst
common/source/docs/common-compass-setup-advanced.rst

Update compass calibration and setup pages

---

common/source/docs/common-cheerson-cxof.rst
common/source/docs/common-px4flow-overview.rst

I have no variable for FLOW_ENABLE.
I know that setting the device type to FLOW_TYPE disables and enables it.
I change the config parameter name.

common: Change FLOW_ENABLE to FLOW_TYPE

---

common/source/docs/common-zubax-gnss-positioning-module-gps-compass-and-barometer.rst

Update Zubax GNSS2 GPS page

---

dev/source/docs/code-overview-adding-a-new-parameter.rst

The link that "_`Change the delay here from 1ms to 2ms [here in AP_Param::show_all]`_" was forwarding to, needed an update.

Minor link update needed

---

build_parameters.py

Small fix due some tests on the server.

Fix versioning script

---

common/source/docs/common-history-of-ardupilot.rst

update AP History page

---

common/source/docs/common-pixhawk-and-px4-compatible-rc-transmitter-and-receiver-systems.rst

Update RC RX/TX page to fix links, minor edits

---

copter/source/docs/circle-mode.rst

got it covered, Matt....I think

Update Circle mode functional description

---

dev/source/docs/sitl-with-airsim.rst

Can be merged after https://github.com/ArduPilot/ardupilot/pull/12179

Dev: Add usage info about Rover with AirSim, plus some more fixes

---

common/source/docs/common-telemetry-landingpage.rst

Add Dragonlink to telem landing page

---

common/source/docs/common-brushed-motors.rst

update brushed motor drivers list

---

common/source/docs/common-sbus-out.rst

Update SBUS servo page re SBUS OUT enable

---

common/source/docs/common-stores.rst

added at request of the Partner

Add UAV Systems International to Stores

---

dev/source/docs/gsoc-ideas-list.rst

@rmackay9 here is my idea for GSOC for trad heli.  Let me know what you think.  Certainly not as challenging as autonomous autorotation but is a capability that would be great to have for tradheli.

adds tradheli project idea to GSOC list

---

dev/source/docs/gsoc-ideas-list.rst

Remove multiples mention of jevois camera as I don't we us to be spam with jevois on proposal without having even read the camera capabilities.
Add some more project idea

Dev: update gsoc idea2020

---

Dockerfile
Sphinxsetup.sh
common/source/docs/common-wiki-editing-setup.rst

Add support for docker
add instruction for docker
Correct Sphinxsetup for debian
add pycharm as ide for visualisation

Add docker support for building

---

plane/source/docs/calibrating-an-airspeed-sensor.rst

I did not update the case studies since any future param changes would not impact the content of those studies without a complete rewrite...

update param links plane: b*-c*.rst

---

plane/source/docs/qacro-mode.rst

@Hwurzburg I see I had also screwed up the list format. This is an attempt to fix that without losing the param hotlinks.

fix list formatting in qacro-mode.rst

---

dev/source/docs/building-setup-linux.rst

a note to avoid firewall problem

Update building-setup-linux.rst 

---

common/source/docs/common-radiolink-minipix.rst

added note per wiki call...also an expansion that page info is not to be used

Add compatibility warning on MiniPix

---

update.py

Fix an error regarding previous versions.

Fix for antennatracker parameters versioning

---

update.py

PR #2592 was not fully effective.

Fix tracker parameters

---

common/source/docs/common-tuning.rst
plane/source/docs/tuning-cruise.rst

I have had many people ask me on my thread how to adjust cruise speed and the inter-relation of these params in setting level cruise speed...

Plane:add cruise speed tuning page

---

common/source/docs/common-compass-calibration-in-mission-planner.rst

This comes as a follow-up for the closed issue:
ArduPilot/ardupilot#13663

Add a note to user about compass calibration

---

common/source/docs/common-accelerometer-calibration.rst

This comes as a follow-up for the closed issue:
https://github.com/ArduPilot/ardupilot/issues/13663

Add a note to user about Accel calibration

---

common/source/docs/common-wiki-editing-submitting-changes.rst

Minimal tip to help users to update their wiki forks.  (Built and tested)

TIP to make a sync in forked repo

---

dev/source/docs/sitl-examples.rst
dev/source/docs/sitl-simulator-software-in-the-loop.rst

@peterbarker After really reading all the docs for vehicles I realized that I had organized it incorrectly....minor reorg...
in the future, in the Using SITL document, I intend to create a smoother version of the video(maybe without narration but with graphic comments) that I mocked-up yesterday and add it to that document

Minor org change to SITL section

---

.gitignore
antennatracker/source/index.rst
common/source/docs/common-logs.rst
common/source/docs/common-measuring-vibration.rst

Integrate Peter's logmessage files into wiki

Integrate logmessage doc files into Wiki, update gitignore

---

update.py

Fix tracker/Tracker/AntennaTracker/Antennatracker/antennatracker naming issues in parameters versioning.
Tested locally, but merged delayed in order to watch the automatic build later.
(fixes PR #2623)

Fix Tracker params 

---

copter/source/docs/motor-thrust-scaling.rst

Update motor scaling calculation method

---

plane/source/docs/quadplane-flying.rst

adds info on how throttle/motors behave during transitions....and clarify some confusing language

Expand info on QuadPlane Transition behaviour

---

dev/source/docs/plane-sitlmavproxy-tutorial.rst

update SITL plane takeoff description

---

dev/source/docs/using-sitl-for-ardupilot-testing.rst

based on our conversation today...

Update Mavproxy graphing section description

---

dev/source/docs/using-sitl-for-ardupilot-testing.rst

Add frame types table to SITL doc

---

common/source/docs/common-transmitter-tuning.rst
scripts/cap_params.py

@tridge need help on what last params are for QuadPlane

Add multiparam tune table; update cap_params.py to catch Q_ params

---

update.sh

Fix the PR #2662 by using "bc" to calc.  
Applying and watching.

Fix to PR 2662 - building time

---

common/source/docs/common-partners.rst

Add Kraus Aerospace as an official partner

Add Kraus Aerospace as an official partner

---

dev/source/docs/companion-computers.rst
dev/source/docs/raspberry-pi-via-mavlink.rst

Adding in references to the Rpanion-server software and the Pi-Connect hardware.

Dev: Add Rpanion-server and Pi-Connect as options

---

dev/source/docs/roadmap.rst

Fix headers and links.
Still need validation on 2019 section.

Roadmap 2020 - update

---

build_parameters.py
rover/source/_static/parameters-Rover.json
update.py

Addresses issue #2675. The parameters will appear but only from current to future versions. 
Old versions still need correction.

Fixing parameters broken for Rover due APMRover2 renaming

---

common/source/docs/common-advanced-configuration.rst
common/source/docs/common-archived-topics.rst
common/source/docs/common-cheerson-cxof.rst
common/source/docs/common-hereflow.rst
common/source/docs/common-mouse-based-optical-flow-sensor-adns3080.rst
common/source/docs/common-openmv-optflow.rst
common/source/docs/common-optical-flow-sensor-setup.rst
common/source/docs/common-optical-flow-sensors-landingpage.rst
common/source/docs/common-px4flow-overview.rst

no content change other than making sure it applies to Quadplane for all flow sensors

Reorg Optical Flow, common setup page, archived Mouse sensor

---

copter/source/docs/loiter-mode.rst

Update copter loiter mode page

---

common/source/docs/common-beitian-gps.rst

move to EKF3 highlited this issue on several of my planes using mini-gps...

Add warning note on BN-220 re time required to pass pre-arm checks

---

dev/source/docs/simulation-2.rst
dev/source/docs/sitl-with-webots.rst

This documentation describes how to use Webots SITL based on latest update [https://github.com/ArduPilot/ardupilot/pull/14367](https://github.com/ArduPilot/ardupilot/pull/14367)

Adding  Webots SITL Simulator Doc

---

common/source/docs/common-commercial-support.rst
common/source/docs/common-rtf.rst
common/source/docs/common-stores.rst

- Added AION to various pages.
- Cleaned up/organized RTF page. Preserved alphabetical order.

Add AION, clean up RTF page.

---

planner/source/docs/mission-planner-initial-setup.rst

First update to the MP docs... @meee1 fyi, I intend to try to update them all over the next few weeks..

Update Mission Planner docs for SETUP menu item

---

antennatracker/source/conf.py
ardupilot/source/conf.py
copter/source/conf.py
dev/source/conf.py
plane/source/conf.py
planner/source/conf.py
planner2/source/conf.py
rover/source/conf.py

Update copyright to 2020

---

common/source/docs/common-3dr-radio-advanced-configuration-and-technical-information.rst

Most notably removing the suggestion that ECC is always a good thing.
It most often is not.

common: tweak SiK radio information

---

plane/source/docs/guide-tailsitter.rst

update for commit 95da094: Plane: update tailsitter speedscaling logic

update description for tailsitter gainscaling

---

common/source/docs/common-rfd900.rst

Update RFD900 Warning

---

common/source/docs/common-optional-hardware.rst
common/source/docs/common-uavcan-peripherals.rst

should make it easier for someone to find a UAVCAN peripheral

Add UAVCAN peripherals page

---

common/source/docs/common-benewake-tf02-lidar.rst
common/source/docs/common-benewake-tfmini-lidar.rst

Current information is not correct for TF03

Parameters not correct for TF03

---

common/source/docs/common-autopilots.rst

updated links to the new cube pages

Updated Links to new cube pages

---

common/source/docs/common-servo-robotis.rst

Update ROBOTIS eManual links and DYNAMIXEL Wizard 2.0 software information

Update DYNAMIXEL information

---

common/source/docs/common-connect-mission-planner-autopilot.rst
common/source/docs/common-loading-firmware-onto-pixhawk.rst
planner/source/docs/mission-planner-advanced-installation.rst
planner/source/docs/mission-planner-installation.rst
planner/source/docs/mission-planner-overview.rst

first part of a page by page update of the Mission Planner section of the wiki

Missionplanner updates

---

copter/source/docs/copter-flight-features.rst
copter/source/index.rst

makes it easier to find advance features for copters, like plane wiki

Add copter flight features page

---

common/source/docs/common-advanced-configuration.rst
copter/source/docs/terrain-following-manual-modes.rst
copter/source/docs/terrain-following.rst

as discussed...link to Understanding Altitude in ArduPilot will be active once that PR is merged

Change name to Surface Tracking instead of Terrain Following

---

antennatracker/Makefile
ardupilot/Makefile
copter/Makefile
dev/Makefile
mavproxy/Makefile
plane/Makefile
planner/Makefile
planner2/Makefile
rover/Makefile
update.py

This turns all warnings into errors.
This will allow us to keep the Wiki clean as travis will enforce everything.
This does include some cleanups to get things to build cleanly, but I was astonished at how few there were.

Build Wiki with sphinx-build's -W

---

antennatracker/source/conf.py
copter/source/conf.py
plane/source/conf.py
rover/source/conf.py

Setting limit to 15000 (tested locally)

Increasing setrecursionlimit

---

common/source/docs/common-archived-topics.rst
dev/source/docs/debugging.rst
dev/source/docs/interfacing-with-pixhawk-using-the-nsh.rst

Deprecate NSH debug page

---

common/source/docs/common-brushed-motors.rst

I have used this extensively with Rover and its fine.
I have not tested this change on a build as its small.

Added Sabertooth 2x32A Motor Controller

---

planner/source/docs/mission-planner-features.rst
planner/source/docs/mission-planner-ground-control-station.rst

Update MP Screens/Features page

---

dev/source/docs/odroid-via-mavlink.rst

I was browsing the docs and came across these dead links.

Fixing some dead links to hardkernel.com

---

dev/source/docs/making-a-mavlink-wifi-bridge-using-the-raspberry-pi.rst
dev/source/docs/odroid-via-mavlink.rst

@stephendade rpi changes deleted links in other documents...unfortunately local build will not catch these since they are cross site links in the .inv files on the server....I think...
@hamishwillee please check that the Odroid changes look right, if you can..
I need to be more careful regarding deleted cross-site-refs since they cannot be caught until merged... @peterbarker   is something we can add to the build check for local builds?

Fix link errors from previous commit

---

common/source/docs/common-matekh743-wing.rst

Fix typo in Matek F743 page

---

mavproxy/source/docs/getting_started/download_and_installation.rst

Clearer install instructions for MAVProxy. I've also tested the Linux ``apt-get``'s to ensure there's no missing packages

MAVProxy: Updated install guide

---

common/source/docs/common-rangefinder-gy-us42.rst

GY-US42v2 serial was merged into the master.
The TYPE is 31.
I change TBD to 31.

common: GY-US42v2 Serial TYPE tbd to 31

---

update.sh

Enabling tested build script flag.

Enable backups flag

---

common/source/docs/common-rangefinder-gy-us42.rst

I know that GY-US42v2 has finished its development.
I remove under development.

common: Remove Under Development

---

antennatracker/source/docs/connecting-with-gcs.rst

Hi, this is my first edit and I wanted to start with something small to get my feet wet. Please feel free to provide any feedback!

Remove eBay link and add Sik radio link

---

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst

literally, a one-character change

capitalization typo

---

common_conf.py

this fixes inventory download issue for Henry, and also makes builds
faster

fixed base URL to use https

---

common/source/docs/common-rtf.rst

Adding partner vehicles - TTRobotix

Update partners vehicles

---

common/source/docs/common-positioning-landing-page.rst

Add Holybro Micro M8N GPS Module and Holybro Pixhawk 4 GPS Module .

Add Holybro GPS

---

plane/source/docs/apms-failsafe-function.rst

Tridge, if I have THR_FAILSFE=2 understood correctly , then I think we need to expand the metadata so its a bit clearer than now

Update plane failsafe page

---

mavproxy/source/docs/getting_started/faq.rst
mavproxy/source/docs/modules/speech.rst
mavproxy/source/docs/modules/terrain.rst

A few small fixes to close off some old issues:
https://github.com/ArduPilot/MAVProxy/issues/680
https://github.com/ArduPilot/MAVProxy/issues/631
https://github.com/ArduPilot/MAVProxy/issues/523

MAVProxy: Small typos and URL updates

---

plane/source/docs/rtl-mode.rst

"Meters" is a count noun. You can climb this *number* meters or this *amount* of mass noun, e.g., "this amount of altitude." I propose changing this to "will climb that many meters," but it could equally be "will climb that number of meters."

amount -> number

---

dev/source/docs/user-alerts-developer.rst

Clarifying a few points in the User Alerts, plus spelling/formatting fixes.

Dev: Minor clarifications for User Alerts

---

plane/source/docs/quadplane-vtol-tuning-process.rst

add more detailed explanations of tuning steps

plane: improved quadplane tuning docs

---

common/source/docs/common-vicon-for-nongps-navigation.rst

key change is use of code tag so that "--" displays correctly. We need
to watch out for this in future PRs

vicon: fixed instructions

---

plane/source/docs/guide-tailsitter.rst
plane/source/docs/guide-tilt-rotor.rst

Pete, another question...does BiCopter use the Q_TILT_YAW_ANGLE param? seems like it would have to ....but I assume the other transition parameters are exactly like the tailsitter transition stuff and not the tilt rotor transition stuff?

Update tailsitter info for BiCopter

---

common/source/docs/common-mro-uavcan-adapter-node.rst
common/source/docs/common-uavcan-adapter-node.rst
common/source/docs/common-uavcan-peripherals.rst

@pkocmoud Phillip need some help on line 21 and making sure that, as delivered, it supports all discussed...

Add mro UAVCAN Adapter Node page

---

common/source/docs/common-limited-firmware.rst

Please add any other suggestions for temporary RAM savings and/or symptoms on the bench....I did not put a note about examining MEMINFO because there is no definite number to tell them if thats the problem, I believe, due to varying setups and whats not starting...

Add notes about RAM limits

---

common/source/_static/useralerts.js
common/source/docs/common-user-alerts.rst
dev/source/docs/user-alerts-developer.rst

Documentation to reflect the addition of the "criticality" field to user alerts.
Ping @auturgy

Add criticality field to user alerts

---

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst

fix links to point to ArduPilot supported cmds

---

plane/source/docs/roll-pitch-controller-tuning.rst

content corrections/changes on line 23 and 185...all others are adding links or spellings

Update plane tuning docs with links and corrections

---

dev/source/docs/building-setup-windows10.rst
dev/source/docs/git-install.rst

Co-authored-by: Jovian-Dsouza <dsouzajovian123@gmail.com>
Simplifying and updating WSL instructions

Update Windows WSL instructions

---

common/source/docs/common-realsense-depth-camera.rst

This is a little clean up of the Intel 435 documentation, along with some added instructions.

Common: add remaining intel 435 installation instructions

---

copter/source/docs/parachute.rst

Add sink rate param to parachute

---

common/source/_static/useralerts.js
dev/source/docs/user-alerts-developer.rst

Wiki changes to document recent changes to User Alerts repo.

User Alert URL and field update

---

plane/source/docs/quadplane-first-flight.rst
plane/source/docs/quadplane-setup.rst
plane/source/docs/quadplane-support.rst

First step...more hierarchy
Next ,will make selecting which type a little easier and clearer

Re-org QuadPlane section

---

copter/source/docs/motor-thrust-scaling.rst

Revised version of #3095 since pushes to that PR are restricted.

Add note about ESCs with internal curves
