ArduPilot/ardupilot_wiki

antennatracker/source/conf.py
ardupilot/source/conf.py
common_conf.py
copter/source/conf.py
dev/source/conf.py
plane/source/conf.py
planner/source/conf.py
planner2/source/conf.py
rover/source/conf.py

The conf.py for each section had some code to disable warnings on non-local images. This was what was incompatible with Sphinx 1.4 (and why we've been forced to use 1.3). This change fixes that code, and moves it into a common location.

Fix image-warn code so that it works with Sphinx 1.4+

---

dev/source/docs/supported-autopilot-controller-boards.rst

Just add **discontinued** status to Erle-Brain1

Dev boards: add discontinued status to Erle-Brain v1

---

plane/source/docs/automatic-landing.rst

The previous abort-landing instructions were convoluted. The formatting is a bit strange, what looks good/bad here in git preview is not what looks good/bad on the html version in the wiki so this is probably a first draft makeover with cosmetic changes later.
@CraigElder and @hamishwillee can you take a look please?

abort-landing instructions

---

common/source/docs/common-autopilots.rst

Closed solution might confuse users that software is closed.

Autopilot boards: change wording

---

copter/source/docs/ekf-inav-failsafe.rst

Remove ampersand from EKF/DCM failsafe page

Remove ampersand from EKF/DCM failsafe page's title

---

common/source/docs/common-wiki_editing_guide.rst

It's practical to see outputs from the RST files you're working on in a
local tool (i.e.  without the need to build them on a Vagrant machine)
during the initial stages of Wiki editing.

Added section on RST rendering on Windows and Linux

---

common/source/docs/common-ads-b-receiver.rst

just correcting a typo.  Reciever should be receiver.
Since the name of the page also has this typo, this might impact the links to the page.

correcting typo in title

---

dev/source/docs/building-px4-with-qtcreator.rst

*toolchain\msys\1.0* was changed to *toolchain\\msys\\1.0* to show the backslash properly.

Fix typo in building-px4-with-qtcreator.rst

---

common/source/docs/common-geotagging-images-with-mission-planner.rst

Airborne Projects released a geotagging
solution which might be useful for some people.
The addition is a brief description of the
board, how it connects to the APM and 3 images.
The spirit of the section is similar to the
one found on http://ardupilot.org/copter/docs/common-frsky-telemetry.html#hardware-solutions
which encouraged people to add their own alternative solution.

Added Commercial Section to Geotagging wiki.

---

dev/source/docs/building-px4-for-linux-with-make.rst

See  https://github.com/ArduPilot/ardupilot/issues/3999

Add note about including libc6-i386 for px4 on 64 bit linux

---

common/source/docs/common-wiki_editing_guide.rst

git remove does not exist. I believe the author meant to say git remote -v.

Fix typo in git command plus add text to descbribe

---

dev/source/docs/raspberry-pi-via-mavlink.rst

On newer versions of the Raspberry Pi, for some bizarre reason UART is disabled by default. This fix tells readers how to fix that in order for the RPi to talk to the Pixhawk.

Enabling serial connection on Raspberry Pi

---

dev/source/docs/setting-up-sitl-on-windows.rst

In previous code, 
./Tools/autotest/autotest.py build.Copter fly.Copter logs.Copter --map --viewerip=192.168.184.1
build.Copter, fly.Copter, logs.Copter do not work anymore. 
So I tried to make autotest.py work. 
I think 
./Tools/autotest/autotest.py build.ArduCopter fly.ArduCopter --map --viewerip=192.168.184.1
works properly.

autotest.py parameter was changed.

---

copter/source/docs/autotune.rst

comparing these two lines, I chose the top versions which seemed more verbose and therefore newer:
AUTOTUNE_AGGR...
Higher values will produce a more aggressive tune but sometimes results in gains that are too high. More specifically this parameter controls the threshold for D-term bounce back and P-term overshoot. 
vs
Controls the threshold for D-term bounce back and P-term overshoot.
AUTOTUNE_AXES ..
This is useful if the vehicle’s battery life is not long enough to complete all 3-axis).
vs
(useful if the vehicle’s battery life is not long enough to complete all 3-axis).

remove redundant and older text

---

dev/source/docs/raspberry-pi-via-mavlink.rst

Please add note about Raspberry Pi3 build-in serial.

Raspberry Pi 3 built-in serial is /dev/ttyS0

---

dev/source/docs/sitl-native-on-windows.rst

Update
sitl-native-on-windows.html
section
"Running SITL and MAVProxy"
part 3
from:
..\Tools\autotest\copter_params.parm
to
..\Tools\autotest\default_params\copter.parm

Update path to default MAVProxy params

---

planner/source/docs/using-python-scripts-in-mission-planner.rst

Python structure is defined by indents.  The indents are completely incorrect and the program would not execute.
Fixed the indents - the program should now run

Corrected the python "Roll Example" program

---

dev/source/docs/building-px4-for-linux-with-make.rst

Correct to the version provided on the page of http://firmware.ap.ardupilot.org/Tools/PX4-tools/.

Dev: Change the release version of gcc-arm cross-compiler.

---

common/source/docs/common-installing-3dr-ublox-gps-compass-module.rst
common/source/docs/common-positioning-landing-page.rst

The 3DR gps page is referenced in assembly instructions (http://ardupilot.org/copter/docs/assembly-instructions.html), so I figured it would be best to simply notify that that particular module isn't being made anymore (as I understand). Maybe a generalized gps page would be the next step?

Update 3DR gps+compass module - RE: no longer produced

---

dev/source/docs/rover-sitlmavproxy-tutorial.rst

this is unneeded as sim_vehicule.py already auto load the defaults params

Rover: sitlmavproxy remove uneeded note

---

dev/source/docs/editing-the-code-with-eclipse.rst

The java link automatically took me to the 64 bit download (which I did not catch before installing). This caused errors when trying to open eclipse (Java returned error code 13).

Update Java note to specify 32 bit

---

dev/source/docs/using-gazebo-simulator-with-sitl.rst

I've tried it on Ubuntu 14.04 LTS and raised issue on OSRF github.
pre-built packages are still working only in 16.04LTS because it is ROS-Kinetic(for 14.04 it is ROS-Indigo)
Changes are summary of what I tried and what is working.
Build and Install SDFormat & Gazebo requires some attention and fix.

Installing Gazebo for APM is outdated

---

dev/source/docs/sitl-native-on-windows.rst

Added references to an automatic script to download/install the SITL environment, plus a link to example batch files to run SITL from a single double-click of a batch file.

SITL: Added references to helper scripts for Windows

---

copter/source/docs/circle-mode.rst

the documentation on Circle mode wasn't clear about whether the
vehicle position when engaging circle mode was the center of the
circle or the edge of the circle.  This change attempts to make that
less ambiguous.

clarify where vehicle starts in circle mode

---

common/source/docs/common-intel-aero-rtf.rst

- Clarify the microcontroller model
- Add version requirement for the Aero side of the software
- Add instruction for developers to build and update the flight
controller
- Make a section for connecting the transmitter

Update Intel Aero RTF page

---

dev/source/docs/building-for-navio2-on-rpi3.rst

It is not necessary to specify the frame when building.
Therefore,
The description to be added has been deleted.

Delete addition of frame type with Build specification.

---

dev/source/docs/building-for-erle-brain-2.rst

Following a recommendation from Lucas
Lucas De Marchi @lucasdemarchi 
For sure we need to change our docs to point to our repo

Replace Erle repo with ArduPilot repo

---

common/source/docs/common-ublox-gps.rst

the ublox configuration files referenced by this document
were removed in ardupilot/ardupilot@d91f89d.
Closes #871.

remove link to obsolete ublox config files

---

copter/source/docs/arming_the_motors.rst
copter/source/docs/auto-mode.rst

This commit implements suggestions from @hamishwillee in issue #804.
Specifically, it clarifies that a copter must be armed before engaging
auto mode, and it updates the list of armable modes.
This also removes the phrase "...and the propellers will begin to spin
slowly", because the propellers when armed are still spinning fast
enough to cause injury.
I have elected not to include Guided mode in these changes, even
though it is an armable mode.
Closes #804

update docs re: auto mode and arming

---

copter/source/index.rst

Per comments in the other PR for the Solo Wiki, here's the index change to put Solo Enhancements into the left nav bar.

SOLO WIKI: Added solo to left navbar in copter index

---

dev/source/docs/building-ardupilot-onwindows10.rst

As pointed out by Lucas, --upload for linux boards uses rsync, not USB serial, so is not effected by the WSL limitation.
I've tested it, and it works.

--upload works for networked targets

---

dev/source/docs/the-ardupilot-autotest-framework.rst

Correct the test names from "Plane" to "ArduPlane"

Autotest Framework - update names of ArduPlane

---

dev/source/docs/sitl-native-on-windows.rst

Filename changed in the repo, but wasn't fixed in the docu, where the link was invalidated.

Fixed link in docu for powershell setup script

---

common/source/docs/common-parameter-reset.rst

Ever since the QuadPlane there are parameters that are common and aren't overwritten, To ensure this procedure works, it's better to use Rover

Vehicle parameter override

---

common/source/docs/common-pixhawk2-overview.rst

www.pixhawk2.com is just a redirect to proficnc, so I  made it proficnc just in case the redirect dies or is repurposed at some stage

Pixhawk 2.1 URL update

---

dev/source/docs/building-px4-with-make-on-mac.rst

The module future is required for mavlink

Add future to required python modules

---

common/source/docs/common-storm32-gimbal.rst

- I've actually never tested myself, but from the code it seems clear that the serial protocol is activated with MNT_TYPE=5
- it's STorM32 and not SToRM32 ;)

STorM32 wiki corrections

---

copter/source/docs/solo_arducopter_upgrade.rst
copter/source/docs/solo_battery_calibration.rst

This PR adds a tutorial page for calibrating the Solo Smart Battery and the link to that page from the main Solo documentation page.  I am not sure if the link is setup correctly or not, because the preview in my fork does not seem to be rendering out the links correctly.

Add Solo Smart Battery Calibration Page to Wiki and Link into Solo documentation

---

copter/source/docs/solo_arducopter_upgrade.rst

This is an attempt to fix the broken (text is there, but no hyperlink) link to the Solo Battery Calibration page ( http://ardupilot.org/copter/docs/solo_battery_calibration.html) in the resources section of this page.

fix link to solo battery calibration

---

dev/source/docs/apsync-intro.rst

installed new image to edison could not access wifi do to password changed.

AP password change for edison

---

common/source/docs/common-wiki_editing_guide.rst

The Youtube tutorial of the editing guide wasn't showing up. It was a small typo.

Fix typo that wouldn't show Youtube video

---

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst

Tested using DO_SET_ROI with a fixed camera. Traditional heli keeps nose pointed at ROI. Deleted the "probably" from the wiki.

Tested "MAV_CMD_DO_SET_ROI"

---

dev/source/docs/building-ardupilot-onwindows10.rst

added a tip to make build work in WSL with Fall Creators update, when source code files are located in a windows drive.
(Using the usual /mnt/<drive> access seems to be broken with Fall Creators update, so you must put your files on a WSL hosted directory or mount the windows directory via a share.

Add tip for putting source files in WSL Creators Fall update

---

dev/source/docs/extended-kalman-filter.rst

To clear a bad use of this parameter in combination with a rangefinder.
After discussion here : https://discuss.ardupilot.org/t/multiple-ekf-primary-change-large-pitch-roll-variation-and-hagl-reset-to-0-in-flight/23328/2?u=kiwa21

EKF_ALT_SOURCE update

---

dev/source/docs/building-ardupilot-onwindows10.rst

the pre-install script have "OPT=/opt" while WSL doesn't have it.

adding the command "mkdir opt" under the root path

---

dev/source/docs/building-ardupilot-onwindows10.rst

merge  "cd /   mkdir opt"
into "sudo mkdir /opt"
reason 1: "sudo" shall be added under the root path.
reason 2:  The user shall stay in the current ardupilot path, otherwise the command in the next step will fail.

merge the two commands into one

---

dev/source/docs/the-ardupilot-autotest-framework.rst

Fix the path of autotest.py, since the _scripts_ folder doesn't contain the autotest module

Fix path of autotest script

---

dev/source/docs/skyviper.rst

Made fixes to a few typos and extended information for logging. I also opened an issue on the information about DSMX instead of just changing it here.  In my transmitter, this function seems to be disabled because when I press that button on power on, absolutely nothing happens.  The code clearly indicates that it is being #ifdef-ed out.

Fix some types in skyviper.rst development info and add more info about the logging function

---

dev/source/docs/copter-commands-in-guided-mode.rst

Introduced in 15782b0fd6c9cdee830f825caf7ca7301b6e630b
Appeared in http://ardupilot.org/dev/docs/copter-commands-in-guided-mode.html
Apologies for the carelessness..

Fix typo in Copter-Commands-in-Guided-Mode

---

dev/source/docs/building-setup-mac.rst

Added the link to the ardupilot tap
removed reference to catkin_pkg
@rmackay9 perhaps also editing the doc title from MacOS X just to the correct name MacOS

Up-to-date on HighSierra 10.13.3

---

dev/source/docs/using-mavexplorer-for-log-analysis.rst

wxgtk2.8 is not in Ubuntu 16.04 repositories. Tested 
https://github.com/ArduPilot/MAVProxy/issues/462

Package name updated to current version

---

common/source/docs/common-pixhawk-overview.rst

There are two commits in this PR.
The first adds information about the Spektrum/DSM port on the pixhawk, based on https://discuss.ardupilot.org/t/add-spektrum-port-pinout-diagram-to-pixhawk-pinout-page/23533/3.
The second adds third-level headings to this document, which at least when rendered on github result in named anchors that can be used to link directly to the pinout for a particular port.

Spektrum pinout

---

plane/source/docs/plane-3-7-to-3-8-migration.rst

Existing text does not make it clear that downgrading really requires very careful review of RC settings and that not doing so is very likely to cause a crash due to reversed servos (this did destroy my aircraft).
https://github.com/ArduPilot/ardupilot_wiki/issues/999

Outline that downgrading is very likely to cause a crash.

---

plane/source/docs/starting-up-and-calibrating-arduplane.rst

A bit of a rework of the Plane starting-up-and-calibrating page mostly to add links to other parts of the wiki (LEDs, safety switch, flight modes, rally points) and to remove some redundancy about waiting for GPS lock.
There are some other small things we can fix on this page in follow up PRs:
- in "First Flight" it talks about "Fly By Wire" mode but we should clarify whether this is FBWA or FBWB (I suspect it's A).
- we should link in advice on calibrating the airspeed sensor.

Plane: add links and remove redundancy from starting-up-and-calibrating

---

plane/source/docs/starting-up-and-calibrating-arduplane.rst

Added a small new section to the starting-up-and-calibrating page to tell people to calibrate and test the airspeed sensor (if present)

Plane: add reference to airspeed calibration on starting-up-and-calibrating page

---

dev/source/docs/git-submodules.rst

I propose here the solution I used to keep a branch updated with a modified submodule. It was for me the cleanest solution as the switch between the appropriate submodule is really simple when you move from one branch to another. I would be interested to get a feedback about this solution or some possible improvements (for example to avoid the necessity to do the "sync" command before to update).

Update a branch with a modified submodule

---

plane/source/docs/guide-elevon-plane.rst

Emphasized correct RC input reversal prior to starting this. Use stabilization to configure rather than transmitter. Adds case-by-case instructions when to reverse or change function.
In response to https://github.com/ArduPilot/ardupilot_wiki/issues/1204

Plane: Update & Simplify Elevon Setup

---

dev/source/docs/skyviper.rst

Adding steps to load Sonix board firmware from SD card, as it was requires at certain occasions.  Discussed here https://discuss.ardupilot.org/t/lost-of-wifi-connection-to-sv-and-wont-arm/28117/19

Steps to load Sonix board firmware from SD card

---

plane/source/docs/guide-vtail-plane.rst

Numerous users haven't been able to figure it out, and the old procedure was prone to errors if transmitters were reversed.

Simplify and clarify V-Tail setup procedure

---

dev/source/docs/building-setup-windows-cygwin.rst
dev/source/docs/building-the-code.rst

Recently went through building SITL and Pixhawk/ChibiOS in Cygwin, so updated the instructions.
Also depreciated old (using make instead of waf) instructions for Windows/Cygwin.

Dev - updated build instructions for Cygwin on Windows

---

common/source/docs/common-autopilots.rst
common/source/docs/common-openpilot-revo-mini.rst

The OpenPilot Revolution and OpenPilot Revo Mini are different boards
All the images on this plane are of the Revolution, not the Mini.

Common: relabel page that deals with OpenPilot Revolution

---

plane/source/docs/guide-four-channel-plane.rst

This should save a significant number of users from double-reversing inputs and outputs to get correct behavior in manual mode. We do this by using FBWA to set up control surfaces.

Plane 4ch Servo Setup Procedure

---

copter/source/docs/skyrocket.rst

Ultimately, I'd like to see https://github.com/ArduPilot/ardupilot_wiki/pull/1190 put in, but this is a good placeholder, and should help search engine crawlers to be guided to this location for information once they start buying these.

SkyRocket Wiki: Update to introduce 2018 models

---

dev/source/docs/debugging-with-gdb-on-stm32.rst
dev/source/docs/debugging-with-gdb.rst

Added information on using gdb debugging on ST-Link v2 with OpenOCD. Provides an alternative to using the BlackMagic Probe.

Added information on GDB debugging through JTAG

---

common/source/docs/common-pixhawk-overview.rst
copter/source/docs/hoverthings-flip-sport-quadcopter.rst

@rmackay9 This fixes up broken links in this doc. 
This used Pixhawk 1 link to 3DR but that is no longer sold by them, so I updated the Pixhawk 1 overview to include link to the mRO equivalent, and then linked to that doc instead. This is model we should always use - overview doc should include purchase links, and everything links to that. That allows us to maintain stores in just one place.
BUT this is quite out of date and will doubtless break again. It covers the predecessor boards to Pixhawk 1. It uses the flip, which I think is no longer produced. 
So think we should merge this, but consider archiving doc?

Fix up links in hoverthings flip sport doc

---

copter/source/docs/precision-landing-with-irlock.rst

IR lock have updated their links from v1.0 to [v2.0](https://irlock.readme.io/v2.0/docs). The new docs do not include the instructions/tool for connecting via linux. 
I have fixed the links to point to the 1.0 docs but it is possible that this is not supported for whatever reason. @rmackay9 Any ideas how we can find out?

Irlock broken links

---

dev/source/docs/setting-up-sitl-using-vagrant.rst

This removes the Rsync information from the [Setting up SITL using Vagrant](http://ardupilot.org/dev/docs/setting-up-sitl-using-vagrant.html) doc because the referenced lines do not exist in the current vagrant structure. 
Would be better to confirm if this could be updated. Who would know?
This follows from #1412

Remove rsync info from SITL/vagrant docs

---

plane/source/docs/airframe-disco.rst

The double negative is interpreted by sphinx as a one-line I added backwards quotes to correct this.

change inline markup

---

common/source/docs/common-ads-b-receiver.rst
common/source/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.rst
common/source/docs/common-gripper-servo.rst
common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst
common/source/docs/common-telemetry-port-setup-for-apm-px4-and-pixhawk.rst
copter/source/docs/ac2_guidedmode.rst
copter/source/docs/mission-command-list.rst
dev/source/docs/code-overview-adding-a-new-mavlink-message.rst
dev/source/docs/code-overview-adding-support-for-a-new-mavlink-gimbal.rst
dev/source/docs/code-overview-object-avoidance.rst
dev/source/docs/copter-commands-in-guided-mode.rst
dev/source/docs/copter-sitl-mavproxy-tutorial.rst
dev/source/docs/gsoc-ideas-list.rst
dev/source/docs/plane-commands-in-guided-mode.rst
dev/source/docs/ros-distance-sensors.rst
dev/source/docs/using-sitl-for-ardupilot-testing.rst
plane/source/docs/flight-features.rst
rover/source/docs/guided-mode.rst
rover/source/docs/rover-failsafes.rst

The mavlink.org links are supposed to be redirected to mavlink.io (currently they are just broken). This fixes the links to point to the correct locations.

Fix up all links to mavlink.io

---

common/source/docs/common-optitrack.rst

It notes Copter-3.6 or higher and EKF2 is required for ext nav support. It also add some info about RTF frame used in the example image and video. I hope this may help people to duplicate indoor experiment.

optitrack: add required ardupilot version and frame info

---

common/source/docs/common-lightware-sf10-lidar.rst

I've discovered that lightware has changed the default baud rate for some devices (at least for the SF11/C). This PR changes the recommended parameters to work with the new default baud rate and adds a note about how to properly set the baud rate for older devices.
One note is that I haven't verified that the default baud rate was changed for devices other than the SF11/C.

Rangefinders: Correct Lightware default baud rate

---

common/source/docs/common-autopilots.rst

Add link to PH4 and PH4-mini.  Interim change - links to hwdef.dat readme for the two boards.

common-autopilots.rst Add Pixhawk4 and 4-mini

---

common/source/docs/common-baro-external.rst

Copter-3.6 has been released so "will be" becomes "was"
This is partially a test to ensure the "quick edit" instructions are ok on the wiki editing guide

Common: update external baro note

---

dev/source/docs/building-setup-linux.rst

Add a small warning about not using distribution-repo-provided gcc-arm versions. Just in case a user (like myself) goes and does exactly that.
Turns out that the gcc-arm in the Ubuntu 18.04 repo, although is a very close version to the one in http://firmware.ardupilot.org/Tools/STM32-tools/, produces bad binaries as per https://github.com/ArduPilot/ardupilot/issues/8663

Dev - add warning about different gcc-arm versions

---

dev/source/docs/setting-up-sitl-on-linux.rst

Based on https://sourceforge.net/projects/jsbsim/ project moved to the new location.

Update JSBSim repo location which moved

---

dev/source/docs/setting-up-sitl-on-linux.rst

make clear that cmake should be install (even if part of install-prereqs)
build JSBSIM as release, as most user will use it that way. The instruction is taken from JSBSIM wiki
consider to use make -j2 to speed up think a little (most computer are at least dual core now, event ARM board)
Remove sudo make install
Add mission -v ArduPIane

Dev: update JSBSIM install instruction

---

dev/source/docs/learning-ardupilot-the-example-sketches.rst

Because of this error message:
"The board target px4-v2 has been removed from ArduPilot with the removal of NuttX support and HAL_PX4."

Changing from px4-v2 to Pixhawk1

---

common/source/docs/common-archived-topics.rst
dev/source/docs/building-apm-for-flymaple.rst
dev/source/docs/building-ardupilot-apm-with-visual-studio-visual-micro.rst
dev/source/docs/building-ardupilot-with-arduino-windows.rst
dev/source/docs/building-for-navio-on-rpi2.rst
dev/source/docs/building-for-qualcomm-snapdragon-flight-kit.rst
dev/source/docs/building-px4-with-make.rst
dev/source/docs/building-px4-with-qtcreator.rst
dev/source/docs/building-the-code-on-mac.rst
dev/source/docs/building-the-code-onlinux.rst
dev/source/docs/building-the-code.rst
dev/source/docs/building_with_make.rst

As per conversation in #1599 and the Ardupilot Wiki guide (http://ardupilot.org/dev/docs/common-wiki-editing-archiving.html), I've moved the deprecated build documentation to the appendix.

Dev: move deprecated documentation to appendix

---

dev/source/docs/copter-sitl-mavproxy-tutorial.rst

The ```speed``` and  ```yaw``` commands are not recognised by Mavproxy.
The current Mavproxy command for setting speed and yaw in Guided Mode are  ```setspeed``` and ```setyaw``` respectively.

Copter: Update Mavproxy commands in Guided Mode

---

dev/source/docs/git-branch.rst

Initially the path written in doc was : Tools/GIT_Test/Git_Success.txt
Whereas actually the filename is GIT_Success.txt
This PR rectifies this mistake by renaming the path as: Tools/GIT_Test/GIT_Success.txt

source/docs/gitb-branch.rst : correctred the given file name from Git_Success.txt to GIT_Success.txt

---

dev/source/docs/setting-up-sitl-on-linux.rst
dev/source/docs/simulation-2.rst
dev/source/docs/sitl-native-on-windows.rst
dev/source/docs/sitl-with-jsbsim.rst

JSBSim is now has a dedicated page in the SITL section, making it easier to find, and keeping it consistent with all the other SITL backends.

Dev: Extracted out JSBSim as a seperate simulator page

---

dev/source/docs/git-rebase.rst

```git push origin master``` is more advisable, especially for beginners to Git for whom this is intended.
It won't push to all the branches which I think is safer, and without any warnings which just ```git push``` gives.
This anyways won't affect advanced users who know what they are doing and will know eactly what command to use

Dev: Change git push command in git-rebase.rst

---

dev/source/docs/sitl-with-jsbsim.rst

Without setting the environment variable, JSBSim doesn't start

Add JSBSim executable to PATH

---

common/source/docs/common-dshot.rst

points out that pass-through currently is supported on blheli_32 only to avoid confusion.
see https://discuss.ardupilot.org/t/blheli-s-passthrough/36346/17 for reference.

common-dshot: pass-thru support on blheli_32 only

---

ardupilot/source/index.rst

Fix on the main index.html.
(rendering checked with the recommended Vagrant environment)

[fix] Google groups link updated to forums link.

---

dev/source/index.rst

On the main Dev page, there is a list of projects. I added arduSub with repo and wiki links.
(render tested with vagrant env.)

[minor insertion] Adding ArduSub in Dev list of projects.

---

plane/source/docs/flight-modes.rst

Users are constantly posting crash logs and issues on default roll and pitch tuning. This should help them realize to autotune sooner.

Add warnings to do Autotune and TECS tuning

---

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst

Issue #1752 pointed the error and the source of correct information: https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_HOME
I tried to check it in the code. These were my findings:
The two files above refer to command 179 regarding the name MAV_CMD_DO_SET_HOME and have the comments as 1=use current location, 0=use specified location.
\Ardupilot\modules\mavlink\message_definitions\v1.0
\Ardupilot\modules\mavlink\pymavlink\generator\swift\Tests\MAVLinkTests\Testdata\common.xml 
In the file "GCS_Common.cpp" the function "handle_command_do_set_home()" expects 1 or 0 as appears on the code.
In the file "GCS_Mavlink.cpp" of expects 1 or 0 as appears on the code.
In the file "AP_Mission.cpp" the "cmd.p1 = packet.param1" expects 1 or 0 as said in comment.
In the file "commands_logic.cpp" …

[fix] MAV_CMD_DO_SET_HOME description fix.

---

common/source/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.rst

"Rsn" field was missing from the doc.
Note: there is a "ThrCrs" field mentioned in the doc but I'm not sure it's still used. Didn't want to remove it blindly though. Somebody from the team should probably take a look at it.

Common: added field "reason for mode change" to log analysis page

---

dev/source/docs/raspberry-pi-via-mavlink.rst

Due to issue #1710, I googled the information provided and checked the RPi3 command to disable BT is useful.

[minor fix] Correction of RPi3 BT disable command.

---

copter/source/docs/altholdmode.rst

AltHold parameter INAV_TC_Z from EKF1 update to EK2_ALT_M_NSE from EKF2. New range and increment also informed.
PR based on issue #1678.
Render not tested. PR from quick edit on Github.

[minor update] AltHold parameter update

---

common/source/docs/common-autopilots.rst

I discover in the forums that APM2 is no longer support newer Rover firmwares. Based on firmwares repo I beleive that the last firmware that fits on the APM2 is the 3.4.2.
PR to provide same information on the wiki.

Rover last version of firmware for APM2

---

plane/source/docs/airspeed.rst

As informed in issue #1713, in the Pixhawk v4, ARSPD_PIN should be set as 4.

ARSPD_PIN correction for Pixhawk v4

---

common/source/docs/common-optitrack.rst

Mavlink.cs, MavlinkMessage.cs, etc are actually coming from Mission Planner source code, they are not auto generated by MAVLink. I am very sorry about this mistake.
thanks @jbausano for pointing it out

optitrack: correct the source of mavlink files

---

.gitignore
antennatracker/source/conf.py
ardupilot/source/conf.py
common/source/_static/common_theme_override.css
common/source/docs/common-donation.rst
common/source/docs/common-partners-program.rst
common/source/docs/common-partners.rst
common_conf.py
copter/source/conf.py
dev/source/conf.py
plane/source/conf.py
planner/source/conf.py
planner2/source/conf.py
rover/source/conf.py
update.py

The PR might be divided into three topics:
- the split into 2 pages (started by @auturgy on #1737/#1738 that this superseeds)
- converting list of partner logos to be a table with custom CSS
- other fixes
Regarding 1st: please check the language and whether you think the split is good (the page with instructions is just linked once in the normal page; I have my doubts on the effectiveness of this, but the old end of page text didn't work either)
Regarding 2nd: note that because this is now a table, we need to be more careful when adding and removing partners since we need to keep a specific format - namely:
- this is a table of two columns so every two lines there needs to be an `*` to signal a new line
- a line can't have only one element, in that case, an empty `-` element needs to be …

Split Partners page and change logo list into table

---

plane/source/docs/plane-configuration-landing-page.rst

currently referenced arming-throttle page contains outdated version-specific information, unfortunate advice ("ARMING_CHECK parameter should probably be left at 0 when at the an airfield without a ground control station") and is a duplicate of the more up-to-date arming-your-plane page. 
i suggest to link arming-your-plane here and retire arming-throttle

plane-configuration-landing-page: link to updated arming page

---

dev/source/docs/code-overview-adding-a-new-mavlink-message.rst

Basically removing step 4.
Please, needs reviews! 
The change was done without coding knowledge. I did it only based on #354 and on #1805 request interlacing.

Remove step 4 from new MAVLINK messages.

---

copter/source/docs/ac_throttlemid.rst

Added note to the fact that parameter THR_MID changed in version 3.6 to MOT_THST_HOVER.

parameter THR_MID changed to MOT_THST_HOVER

---

dev/source/docs/raspberry-pi-via-mavlink.rst

Added a note for new Raspberry Pi users to use the new python-wxgtk3.0 version. 
Trying to use python-wxgtk2.8 is giving this error in newer releases:  
Package 'python-wxgtk2.8' has no installation candidate

Raspbian buster version to use python-wxgtk3.0

---

dev/source/docs/apmcopter-adding-a-new-flight-mode.rst

I fixed leak of change to wiki related to this commit .
https://github.com/ArduPilot/ardupilot/commit/676d75c391926ddc481b5f4d0a6a4efb95145ac8

Copter: correct namespacing of Copter modes

---

dev/source/docs/lua-scripts.rst

This adds the GPS, Notify, and Vector2f docs.
This needs https://github.com/ArduPilot/ardupilot/pull/11867 for the GPS docs to be entirely correct, but that's probably not a hard requirement for pulling this in, it's fixing the behavior on a method I'm not even fully sure we need to be exposing to scripting users.

Dev: Add more Lua docs

---

update.py

COPY_TARGET_DIR_BASE is a static path.  Instead add a `--destdir`parameter that allows this to be specified, which defaults to the existing '/var/sites/wiki/web'.  This allows the wiki to be built in other environments.

Add --destdir argument to replace static COPY_TARGET_DIR_BASE, #1223

---

plane/source/docs/guide-tailsitter.rst

Removing a single warning from Sphinx build. (WARNING: Inline strong start-string without end-string.)

Insignificant warning removal

---

copter/source/docs/tuning-process-instructions.rst

Removing two "WARNING: Title underline too short." from the list of wiki build warnings.

Build Warning Removal

---

dev/source/docs/the-ardupilot-autotest-framework.rst

The wrong directive was making some text not visible.

Wrong  directive on warning tag

---

plane/source/docs/guide-elevon-plane.rst

Added more info on mixing gain and impacts
Added explanation of Mixing Offset param
As a side note, I believe Mixing Offset to be a nearly worthless feature and should be deprecated, or, at the least marked as for advance users and not explained in the WIKI. The fact that it reduces the control range of the TX stick is undesirable in my opinion. A better way to get more roll sensitivity would be to use positive expo at the TX to avoid having stick range reduction and yet get more sensitivity around neutral.

Expand elevon mixing info, add mixing offset

---

common/source/docs/common-non-gps-navigation.rst
common/source/docs/common-optional-hardware.rst
common/source/docs/common-vio-tracking-camera.rst

For copter and rover, non-GPS navigation using the VIO tracking camera has been demonstrated successfully in [this series of blogs](https://discuss.ardupilot.org/t/gsoc-2019-integration-of-ardupilot-and-vio-tracking-camera-for-gps-less-localization-and-navigation/42394), specifically for non-ROS setup:
- [Part 4](https://discuss.ardupilot.org/t/integration-of-ardupilot-and-vio-tracking-camera-part-4-non-ros-bridge-to-mavlink-in-python/44001)
- [Part 5](https://discuss.ardupilot.org/t/integration-of-ardupilot-and-vio-tracking-camera-part-5-camera-position-offsets-compensation-scale-calibration-and-compass-north-alignment-beta/44984)
This PR attempts to document the aforementioned 2 blog posts in a more compact format. Since this is very similar to [ZED for non-GPS navigation …

Add vio tracking camera for non-GPS navigation (non-ROS)

---

copter/source/docs/solo_arducopter_upgrade.rst

For this one, I think to maintain Copter 3.5 as the default parameter would stay in compliance with the rest of the page.  So I removed the ref and added the new parameter name.

Copter: Fix build warning (parameters)

---

rover/source/docs/balance_bot-home.rst
rover/source/docs/balance_bot-testing.rst

The main page reference was duplicated. The tip enhances the pointer to the tunning page.

Rover: Duplicated ref and small tip

---

common/source/docs/common-3d-mapping.rst
common/source/docs/common-choosing-a-ground-station.rst
common/source/docs/common-multi-vehicle-flying.rst

after Peter and I have failued to figure out why the ref plane:home doesnt work linking to the plane home page, I just added direct url links to get rid of the build errors....

fix plane home wiki build errors

---

common/source/docs/common-autopilots.rst

Since CUAV no longer lists this, nor their distis, and CUAV V5plus and nano replace it....it should go in discontinued list and eliminate it as a floating document

Add CUAV V5 to discontinued list,resolving build error

---

common/source/docs/common-rcoutput-mapping.rst

Changed page to apply to ALL vehicles and to allow logical path to find needed output functions
- grouped by vehicle or function
- noted for which vehicle(s) the function applies
- added explanations to links for every function
once merged, I intend to add a DEFAULT ASSIGNMENTS table for SERVO1-8 listing every vehicle type and what it assigns as defaults to each output...

Major update to SERVOx_FUNCTION page

---

common/source/docs/common-frsky-telemetry.rst

One link wasn't going external. The other was a 404 error due to a change.

Fix broken links in FrSky Telemetry

---

dev/source/docs/rover-adding-a-new-drive-mode.rst

Mapping between the mode's number and the instance of the class for rover now done in "mode.cpp" instead of 'control_modes.cpp'. This PR fixes it.

Update in "adding a new drive mode" documentation

---

dev/source/docs/simulation-2.rst
dev/source/docs/sitl-with-scrimmage.rst

Documentation for using Scrimmage as SITL simulator. Relevant pull request: https://github.com/ArduPilot/ardupilot/pull/11887

Dev: add documentation of sitl with scrimmage

---

common/source/docs/common-advanced-configuration.rst
common/source/docs/common-non-gps-navigation-landing-page.rst
common/source/docs/common-optional-hardware.rst
common/source/docs/common-use-cases-and-applications.rst
common/source/docs/common-vicon-for-nongps-navigation.rst
copter/source/docs/ac2_guidedmode.rst

This intends to re-arrange the Non-GPS pages, as discussed in issue #1983.
ros-vio-tracking-camera and ros-cartographer-slam were removed from because in already in DEV environment.
The pages are filtered for Rover and Copter only.

Non-GPS pages re-arrange.

---

common/source/docs/common-f4by.rst

This fixes a spelling error in the F4BY FMU information.

Fix spelling of "telemetry"

---

common/source/docs/common-vio-tracking-camera.rst
dev/source/docs/ros-vio-tracking-camera.rst

It removes some warnings from building the wiki. 
Some code blocks were flagged as python, but they have linux commands.

Fix build warning

---

plane/source/docs/guide-tailsitter.rst

Added a sentence with guidance to disable Q_A_ANGLE_BOOST for vectored thrust tailsitters. Found this by crashing this weekend, and discovered this had been discussed some time ago. See tridge's advice below:
https://discuss.ardupilot.org/t/dual-motor-tailsitters/15302/500

Wiki update for vectored thrust tailsitters

---

dev/source/docs/ros-apriltag-detection.rst
dev/source/docs/ros-aruco-detection.rst
dev/source/docs/ros-timesync.rst

This PR correct issue https://github.com/ArduPilot/ardupilot_wiki/issues/1932

ros-timesync: correct rtc_types

---

copter/source/docs/traditional-helicopter-tuning.rst

This PR updates the reference to RC_FEEL parameter to the new parameter ATC_INPUT_TC for the tradheli tuning wiki.  RC_FEEL was still mentioned as a previous version of this parameter.

tradheli-Update parameter names for copter 3.6 in tuning wiki

---

dev/source/docs/ros-timesync.rst

Added clarification that BRD_RTC_TYPES is a mask for the time synchronization source.
Expands on issue #1932 
Addresses issue #2025

Dev: Added clarification around BRD_RTC_TYPES

---

common/source/docs/common-dshot.rst

this adresses the following topics:
- clarify DShot protocol setup not being necessarily related to using BLHeli_32 ESC firmware
- clarify parameter SERVO_BLH_AUTO automatically maps BLHeli_32 support for multirotor motors only
- clarify sending BLHeli_32 esc data via ardupilot telemetry requires using mavlink2, being the default on the console, but not on the telemetry ports as for now.
- trying to rearrange the instructions in order of specifity
see https://github.com/ArduPilot/ardupilot_wiki/issues/2047 for reference

common-dshot.rst: page rework

---

dev/source/docs/using-sitl-for-ardupilot-testing.rst

RNGFND_MIN_CM was missing. (Should be 0. Look at https://github.com/ArduPilot/ardupilot/issues/12209)
also renamed RNGFND1_* to RNGFND_*

Copter: fix parameter list for virtual rangefinder

---

dev/source/docs/release-procedures.rst

Update old google groups link to Gitter General Channel

Update old google groups link - releases page

---

common/source/docs/common-benewake-tf02-lidar.rst
common/source/docs/common-benewake-tfmini-lidar.rst
common/source/docs/common-echologger-ect400.rst
common/source/docs/common-leddar-one-lidar.rst
common/source/docs/common-lightware-lw20-lidar.rst
common/source/docs/common-lightware-sf10-lidar.rst
common/source/docs/common-rangefinder-sf02.rst
common/source/docs/common-sensor-offset-compensation.rst
common/source/docs/common-underwater-sonar-analog.rst
common/source/docs/common-vl53l0x-lidar.rst
common/source/docs/common-wasp200-lidar.rst

Eliminates rangefinder errors caused by moving to multiple rangefinders.....no content changes...

Wiki build error fix: rangefinder labels

---

common/source/docs/common-compass-setup-advanced.rst

per wiki call....adding warning not to use mode 1 or 2 in compass learn...
tridge or randy were to change param code param default to 0 from current of 1...

Update compass learn to warn against using old settings

---

copter/source/docs/failsafe-battery.rst
copter/source/docs/gcs-failsafe.rst
copter/source/docs/radio-failsafe.rst

Starting to update the copter wiki failsafe pages to follow https://github.com/ArduPilot/ardupilot/pull/7432

Copter: Failsafe refactor and FS_OPTIONS parameter documentation

---

common/source/docs/common-advanced-configuration.rst
plane/source/docs/advanced-failsafe-configuration.rst

for Plane 4.0...
added AFS_MAX_RANGE
fixed wrong param names
added hotlinks to params
added AFS_TERM_ACTION 43 for Quadplane
SHOULD THIS BE COMMON TO ROVER AND COPTER ALSO???

Plane: Update AFS with MAX_RANGE param, correct wrong param names, format edits

---

plane/source/docs/guide-tailsitter.rst
plane/source/docs/quadplane-frame-setup.rst

info on default outputs and how to setup motors in vectored tailsitter

Expand tailsitter info in qplane frame and tailsitter docs

---

README.md

The link to Wiki Editing Guide changed was broken. Changed from http://ardupilot.org/ardupilot/docs/common-wiki_editing_guide.html to http://ardupilot.org/dev/docs/common-wiki_editing_guide.html

Update the link to Wiki Editing Guide

---

copter/source/docs/polygon_fence.rst

The maximum number of GeoFence points for Copter is 70 as per https://github.com/ArduPilot/ardupilot/blob/master/libraries/StorageManager/StorageManager.cpp#L74
I tested it on a Pixhawk Cube and failed to upload anything more than 70 points

Copter: Update polygon fence docs

---

copter/source/docs/failsafe-landing-page.rst

already listed under object avoidance

Copter: remove geo-fence and adsb avoidances from failsafe page

---

dev/source/docs/sitl-with-airsim.rst

https://github.com/ArduPilot/ardupilot/pull/13060 has been merged which moves the parameters to the `default_params` folder and can be found by `sim_vehicle.py`

Remove param file argument for AirSim launch

---

common/source/docs/common-compass-calibration-in-mission-planner.rst

Small changes to clarify what happens when unhappy tones are heard.
Also gives a few more tips to help with the burden of calibrating.

Compass Calibration: Clarify Retrying in MP

---

common/source/docs/common-pixhawk-and-px4-compatible-rc-transmitter-and-receiver-systems.rst

Done primarily to stop answering forum question on why ardupilot is failing to recognize Spektrum signals from satellite receivers. https://github.com/ArduPilot/ardupilot/issues/13117
Also updated some of the FrSky stuff as the X-Lite is quite popular now. PLEASE add the image of an X-Lite to the library; I'm not sure how to include that in this PR.
Other random grammatical and accuracy fixes.

RC Receivers Update for FrSky and Spektrum

---

plane/source/docs/guide-tilt-rotor.rst

I just noticed, that Q_M_YAW_SV_ANGLE ist still missing.

guide-tilt-rotor:  Q_M_YAW_SV_ANGLE  added

---

.gitignore
antennatracker/source/_static/parameters-Antennatracker.json
antennatracker/source/_static/parameters_versioning_script.inc
antennatracker/source/conf.py
build_parameters.py
copter/source/_static/parameters-Copter.json
copter/source/_static/parameters_versioning_script.inc
copter/source/conf.py
plane/source/_static/parameters-Plane.json
plane/source/_static/parameters_versioning_script.inc
plane/source/conf.py
rover/source/_static/parameters-Rover.json
rover/source/_static/parameters_versioning_script.inc
rover/source/conf.py
update.py
update.sh

Versioning for parameters
It brings a script to maintain multiple parameters pages for vehicles. The idea is to list binaries from firmware repo and build parameters files for each one.  (observation: the original idea was to get tags from GitHub, but after a discussion on a wiki meeting, it was dropped)
To present a suggestion for the interface, I tested two mockups:
A) http://tiny.cc/wp9idz
and 
B) http://tiny.cc/3z6idz
This script is not ready yet. It is an early version to discuss some points:
1)To fetch Parameters.cpp files, I used an Ardupilot cloned repo. It is trustable and secure, but it is big and slow. 
1.1) May I trust on download GitHub raw parameters.cpp file? It would be faster and a cleanner solution.
1.2) May I transfer ardupilotRepo\Tools\autotest\param_metadata to wiki …

Versioning for paramaters page

---

update.sh

The Wiki's server always rewrites its own update.sh with the git repo, so it is necessary to update it here.
General users should not be affected if they use update.py as indicated on the Wiki.

Makes parameters versioning the default

---

build_parameters.py
update.py
update.sh

List of not critial changes:
- Forces parameters.html redirection to the latest version does not matter the build time;
- Changes some debug messages;
- Makes error msgs the same way and readable accross parallel running;
- Makes debug msgs the same way and readable accross parallel running;

Fixes on versioning for parameters

---

update.py
update.sh

Correct miss behavior regarding the order when Wiki is moved versus the parameters caching time.

Param versioning

---

common/source/docs/common-flir-vue-pro.rst
common/source/docs/common-gripper-servo.rst
copter/source/docs/autotune.rst
copter/source/docs/heliquads.rst

@rmackay9 haven't the foggiest idea why these did not appear until today's build check....a build of master an hour ago did not produce them....maybe something to do with the new parameter versioning building process?

fix wiki build errors due to retired params

---

copter/source/docs/traditional-helicopter-connecting-apm.rst

This PR updates the wiki that discusses connecting the controller to the receiver and servos.  Made some pretty big changes to bring the page up to date to include a discussion on motor interlock.

Update Tradheli connections page to include Motor Interlock

---

dev/source/docs/can-bus-driver-roadmap.rst

The docs were still referencing AP_HAL::CAN even though that class was renamed to AP_HAL::CANHal.

Dev: update docs to reflect class name change

---

dev/source/docs/building-setup-windows-cygwin.rst

Based on recent comments in the Ardupilot Gitter chat, multiple people have reported issues building the ARM-based (ie using gcc-arm) builds under Cygwin.
Adding in this small message to suggest people use WSL instead (which does work), as will cut down on the number of "why is Cygwin not working" posts in the Gitter chat.

Dev: Add note about Cygwin not wanting to do ARM builds

---

common/source/docs/common-ltm-telemetry.rst

and add link to LTM-to-MAVLink converter

common-ltm-telemetry.rst: add notes on serial port limitations

---

.gitignore
build_parameters.py
update.py

Fixes the left toctree for the latest parameters page.  (Only and just only for the latest firmware version, the previous stable versions are not supposed to appear)
Obs.: it includes minimal enhances to debug better and present comparations of os.stat() and hash comparations for the cache.

Fix toctree for parameters in versioning build

---

antennatracker/source/_static/parameters_versioning_script.inc

This typo causes 404 on Tracker previous versions of parameters.

Fix a typo in include file of Tracker

---

copter/source/docs/traditional-helicopter-tuning.rst

The parameter names have changed from TUNING to TUNE.  Also, entering the values previously listed in to the raw parameters directly (Mission Planner's Full Parameter List, for instance) would set a range from 0 to 30, wherein the actual expected params may be more like 0 to 0.1 as a max.

TradeHeli Wiki: Updating TUNE Parameter settings

---

dev/source/docs/building-mission-planner.rst
dev/source/docs/building-the-code.rst
planner/source/docs/mission-planner-building.rst
planner/source/docs/other-mission-planner-features.rst
planner/source/index.rst

Rename a page.
Add explicit link to Mission Planner building instruction on MP wiki. I struggled to build MP when we get instructions ... 
Add a warning that documentation is outdated. It will need some update to work properly, but I don't master enough C# to do it

Mission Planner

---

dev/source/docs/building-setup-windows-cygwin.rst

Required after cygwin build changes and deprecation, python future module will not be found in waf otherwise.

Change python2-future to python27-future for cygwin install

---

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst

first phase....added VTOL plane commands, unified grouping and ordering into NAV/Special/Conditional/DO for all vehicles....after this merge, will work on verifying Mission Planner actually supports all commands (apparently several plane one are not), then create individual NAV pages for each vehicle (like copter already has) with a common page for conditionals and do's linked via a landing page....and delete this one...too many vehicle differences on too many commands...

Add VTOL modes to command list and re-org into cmd types

---

dev/source/docs/code-overview-adding-a-new-parameter.rst

As part of my PR here https://github.com/ArduPilot/ardupilot/pull/13600 
SYSID_SW_MREV was changed to FORMAT_VERSION

Updating Add a new parameter page

---

common/source/docs/common-oa-dijkstras.rst

Related to: https://github.com/ArduPilot/ardupilot/issues/12691
I tested it out in SITL. The vehicle just breaches fence and does the fence breached fail-safe option. I feel we should warn the user's of this outcome until we solve this issue.

Warn users about Spline WP with Dijkstras

---

common/source/docs/common-oa-bendyruler.rst

The note part was not displaying correctly due to the minor typo.

Minor typo fix in Bendy Ruler Page

---

dev/source/docs/SITL-setup-landingpage.rst
dev/source/docs/simulation-2.rst
dev/source/docs/sitl-simulator-software-in-the-loop.rst
dev/source/docs/starting-sitl.rst
dev/source/docs/using-sitl-for-ardupilot-testing.rst

had to run SITL after not running for several months and was very hard for me to find the information I needed (some was missing, I will fix that next)....lots of duplicate TOC entries...
so this is to simplify the drill down to what someone is looking for rather than a long list of topics...
no substance changes, just re-organization...makes its quick to find what you have forgotten or easy(er) for a first time user....
next , I am going to add stuff to a couple of pages that I had to get Tridges help to run QuadPlane yesterday while its fresh in memory

Re-org Simulation section and remove duplications

---

build_parameters.py

The option of versions was presented randomly in the Listbox on parameter pages of each vehicle. This PR only sorts that.

Fix parameters order in listbox

---

common/source/docs/common-uavcan-adapter-node.rst
common/source/docs/common-uavcan-setup-advanced.rst

Quite a few users not able to get rangefinder working with AP_Periph - there's some key params not documented elsewhere.

Add more docs for UAVCAN AP_Periph rangefinder.

---

update.sh

The idea is to save the time that tasks from the build script consume. This will help to identify the pre-built caching issues.

Saving build time of wiki and its subtasks

---

dev/source/docs/roadmap.rst

I took the liberty to propose that relying on the un-conference discussion. This is a copy from the spreadsheet used during the un-conference. 
It is roughly alphabetically sorted order but pushing vehicles up and merge some sections based only in names to domain area (ie miscellaneous)
I need some help with 2019 items once I am not sure if they were finished or not.

Roadmap update

---

common/source/docs/common-gpios.rst

need to add this to DShot page also...

Add note about RCOut banner indicating output types to GPIOs page

---

common/source/docs/common-autopilots.rst
common/source/docs/common-holybro-kakutef7aio.rst
common/source/docs/common-holybro-kakutef7mini.rst
common/source/docs/common-limited-firmware.rst
common/source/docs/common-matekf405-wing.rst
common/source/docs/common-matekf405.rst
common/source/docs/common-omnibusf4pro.rst
common/source/docs/common-omnibusf7.rst
common/source/docs/common-pixhawk-overview.rst
common/source/docs/common-taulabs-sparky2.rst
copter/source/index.rst
plane/source/index.rst
rover/source/index.rst

This comes from the my research into ``HAL_MINIMIZE_FEATURES`` define in ArduPilot.
This will assist users in determining if their autopilot is missing any features that they require.

Common: Give details of minimal firmware for some autopilots

---

dev/source/docs/building-setup-windows-cygwin.rst

Updating the Cygwin install to Python3. Based on updated install script over at https://github.com/ArduPilot/ardupilot/pull/14095

Dev: Update Cygwin install instructions

---

common/source/docs/common-transmitter-tuning.rst
common/source/docs/common-tuning.rst
copter/source/docs/ac_rollpitchtuning.rst
copter/source/docs/traditional-helicopter-tuning.rst
copter/source/docs/tuning-process-instructions.rst
copter/source/docs/tuning.rst

generalize and move copter tx tuning sections into the common tx tuning page for future proofing
add TUNE value table
use references to this page wherever CH6 tuning was mentioned

Move copter tx tuning into common page and update references in copter

---

antennatracker/source/docs/loading-the-firmware.rst
common/source/docs/common-bootloader-update.rst
common/source/docs/common-connect-mission-planner-autopilot.rst
common/source/docs/common-loading-firmware-onto-chibios-only-boards.rst
common/source/docs/common-loading-firmware-onto-pixhawk.rst
copter/source/docs/initial-setup.rst
plane/source/docs/arduplane-setup.rst
planner/source/docs/mission-planner-installation.rst
planner/source/index.rst
rover/source/docs/apmrover-setup.rst
rover/source/docs/balance_bot-configure.rst

first step in clarifying the firmware load process based on comments on the forums I monitor and support (mainly RC hobbyists)...this PR removes Chibios/Pixhawk distinctions...either the board already had ArduPilot or not when determining firmware loading procedures..
no actual content change...will merge in a couple of days 
- next step is to clarify the way to actually download from firmware.ardupilot.org and add note for first time loading...there is no mention now
- then  to add to the driver install process for DFU, there are simpler methods than ZADIG... STM32CUBE loader and  ImpulseRC Driver Fixer...that should be mentioned

Renamed firmware loading page titles; updated refs in antennatracker

---

common/source/docs/common-uavcan-adapter-node.rst

Added instructions for f303-universal firmware and rangefinder setup for AP_Periph 1.1.0

Common UAVCAN: f303-universal & rangefinder instructions

---

dev/source/docs/using-sitl-for-ardupilot-testing.rst

New parameter set has numbers in RNGFND parameters. Simply updating the parameter names to the current set.

Update parameters in rangefinder example

---

dev/source/docs/building-setup-windows-cygwin.rst

This adds xterm instructions of the Cygwin wiki page. I was trying to be fancy and do this with the online editor however it turned out bigger than expected so I will do a local test build soon.

Dev: Cygwin: add xterm instructions

---

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst

Added param3 to the common mavlink mission commands.  This param allows for the camera to be triggered once, immediately, when accepting the DO command.
Needs to a Delay Merge as in Master but not yet in Beta or Stable.

Common: Added param3 to MAV_DO_SET_CAM_TRIGG_DIST

---

common/source/docs/common-navio2-overview.rst

e.g. see https://docs.emlid.com/navio2/ardupilot/hardware-setup/

Input Interface of the Navio2 is PPM not PWM

---

common/source/docs/common-autopilots.rst
common/source/docs/common-thecube-overview.rst
common/source/docs/common-thecubeorange-overview.rst
common/source/docs/common-thecubepurple-overview.rst
common/source/docs/common-thecubeyellow-overview.rst

Hi guys, I have made the changes and tested this on a local build on Plane,Copter and Rover.  
I believe I now have this correct but please give feedback as this is all new to me, on a learning curve for sure. 
I also 'think' I have quieted the commits. 
**Changes made** 
Corrected spelling errors and formatting on Cube Orange page.
Corrected formatting and spelling errors on Cube Yellow page.
Corrected  spelling and formatting errors on Cube Purple page.
Changed link to Cube Green to Cubepilot, (I will create a page for this in the future for the Solo) 
Changed links to support and docs on all pages above to be tidier and clearer.
Corrected link to Cube Purple page from common autopilot hardware as was missing first letter.

Fixed Cubepilot pages issues 

---

common/source/docs/common-lua-scripts.rst

Dependent on [this PR](https://github.com/ArduPilot/ardupilot/pull/14386).

AP_Scripting: add binding for get_output_pwm

---

common/source/docs/common-lua-scripts.rst

Adds documentation for SRV_Channels:set_output_pwm_chan_counter(). Dependent on [this PR in ardupilot](https://github.com/ArduPilot/ardupilot/pull/14366).

SRV_Channels: set_output_pwm_chan_timeout_ms()

---

build_parameters.py
update.py

It does some workaround to re-enable versioning for Rover parameters files. Tested locally.
It also inserts the ":orphan:" tag in the files in order to stop warnings for parameters files for old versions.

Fix: Rover parameters versioning

---

copter/source/docs/ac2_followme.rst
copter/source/docs/flight-modes.rst

I would change the GCS to indicate the ground control station.

copter: Change from GSC to GCS

---

common/source/docs/common-holybro-kakutef4.rst

Updated line 25, as line 123 already stated correctly, ICM20689 does not include any compass.

ICM20689 does not have compass

---

common/source/docs/common-holybro-pix32v5.rst

The wiki building did break due to file common-holybro-pix32v5.rst charset was not set to utf8.
This PR converts the file to ut8 and remove bad characters.

Fix pix32v5 file charset

---

common/source/docs/common-holybro-pix32v5.rst

This (re)insert the copyright symbol from PR #2915

Insert Trademark symbol for ARM Cortex in pix32v5

---

update.py

This PR enables the "--enablebackups" flag in the build script. When used, this keeps up to N_BACKUPS_RETAIM previous wiki builds as backups.
The default used folder is supposed to be another http site.  It will enable navigation between those versions to check for errors or make it easier to get a built copy online due to some issues.

Backup engine for wiki building.

---

plane/source/docs/guide-tilt-rotor.rst

It appears that `<th>value</th>` appears twice in the table of Tilt Servo functions & values (https://ardupilot.org/plane/docs/guide-tilt-rotor.html#tilt-servos)

removing apparently superfluous <th>value</th>

---

.gitignore
Makefile
antennatracker/source/conf.py
antennatracker/source/index.rst
common/source/_static/useralerts.js
common/source/docs/common-user-alerts.rst
copter/source/conf.py
copter/source/index.rst
dev/source/_static/common_theme_override.css
dev/source/docs/user-alerts-developer.rst
dev/source/index.rst
plane/source/conf.py
plane/source/index.rst
rover/source/conf.py
rover/source/index.rst

This PR adds:
-Developer documentation for handling and processing user alerts, based on document at https://docs.google.com/document/d/1vLX0uRuPjPImEvvol0YnI2afBFTTNbcackr2JBIw_yc/edit#
-User page for each firmware listing current user alerts. Note these are pulled directly by the client from https://firmware.ardupilot.org/userAlerts, so there is no need to process updates server-side. This did require a bunch of custom JS to perform the processing.
Note for reviewers:
To use the example user alert data, change the URL in ``useralerts.js`` to "https://firmware.ardupilot.org/userAlerts/exampleManifest.js". This will provide more useful data to test with.

Add User Alert Documentation

---

update.py

This is a follow-on to https://github.com/ArduPilot/ardupilot_wiki/pull/2926. A required js file wasn't picked up by the build system. This patch fixes this.
Tested locally and works fine.

Scripts: Ensure js files are picked up

---

Sphinxsetup.sh

This is RFC.
It removed mercurial dependency to save some space and bandwidth on setup. It change the target to a clone of the original vimeo plugin on github. The plugin hasn't been updated from long time. Ideally we should put the plugin on ArduPilot github
It works as previously no issue spotted. We gain 40Mo of space and some second on environment setting. We also remove dependency to mercurial and bitbucket to have only git and github.

Sphinx: remove mercurial and change vimeo plugin location

---

mavproxy/source/docs/development/mavcustmod.rst

The ``init`` function should be at module scope, but it was nested in the ``TestModule`` class.

Fixed incorrect indentation

---

common/source/docs/common-user-alerts.rst
dev/source/docs/user-alerts-developer.rst

This PR adds a small note to the User Alert pages explaining that the User Alerts don't 100% cover the time period before 16/09/2020.

Add start date for User Alerts

---

common/source/docs/common-advanced-configuration.rst

unify to "GeoFencing Failsafe"

common: remove duplicate link

---

common/source/docs/common-ads-b-receiver.rst

I found a link error.
I could not find the ADS-B receiver on the Japan Drones web site.
I am removing this link.

common: Removing Broken Links

---

common/source/docs/common-user-alerts.rst
mavproxy/source/docs/modules/index.rst
mavproxy/source/docs/modules/useralerts.rst

A few more User Alerts changes:
- Documentation for running the MAVProxy User Alerts module
- Link to the User Alerts Database

User Alerts - more documentation

---

common/source/docs/common-ppm-encoder.rst

Changed Ext Fuse Settings from 0xFD to 0x07 
Resolves : #3038

Rover: Updated Ext Fuse Settings for common-ppm-encoder

---

common/source/docs/common-lua-scripts.rst

I believe the description for adding Lua bindings is quite outdated. Especially, there isn't no need anymore for doing the make thing. Cleaning the distro does do it now, which is IMHO a much simpler approach. I wonder if the first sentence in the 3rd bullet should be removed altogether.
By virtue of that I also believe that the reference to the PR is inapproriate since all one has to do now is to PR the additions to the bindings.desc. I thus removed it.

Lua scripts: Update how to add bindings

---

common/source/docs/common-vio-tracking-camera.rst

I looked at the images on this page and saw the description of connecting to the GPIO connector on the Raspberry Pi.
I have users who do not check the connector specifications of Pi-Connect Lite.
I will specify which signal to use.
I hope this page will help users to connect to their Raspberry Pi.

Pi-Connect Lite: Add the name of the signal being used.

---

mavproxy/source/docs/development/mavdevenvwindows.rst

Fixes error `ModuleNotFoundError: No module named 'prompt_toolkit'` when launching mavproxy.py
I guess it is already [fixed in setup.py](https://github.com/ArduPilot/MAVProxy/blob/b1da24d62a25e075dd6202b15ea03698e304338c/setup.py#L45), but installation with setup.py script fails for me on Windows, so this documentation is relevant.
Tested on Windows 10, Python 3.8.5, pip 20.1.1

Add prompt-toolkit to windows dev install commands

---

common/source/docs/common-vio-tracking-camera.rst

I updated the Jetson tutorial link, because the old link can only get the librealsense.so. Jetson can not install pyrealsense2 with pip. In order to get the Python wrapper, compiling from source is a must. The updated link contains the compiling tutorials that leads to both ``librealsense`` and ``pyrealsense2``.

Changed to a better tutorial link for Jetson users

---

common/source/docs/common-autopilots.rst

Update last APM2 firmware version in common-autopilots.rst based on firmware available from https://firmware.ardupilot.org/Plane/

Update last APM2 firmware version in common-autopilots.rst

---

common/source/docs/common-lua-scripts.rst

I would prefer not to have the user create the script folder directly.
I found the LUA scripting class's init method to create the folder.
I enable the LUA script and restart it.

LUA: Add a method for generating scripted folders

---

dev/source/docs/droneapi-tutorial.rst

When I click on the title of dronekit-python, it will take me to dronekit-android.
I change the URI.

Changing the URI of dronekit-python

---

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst

Copters support rotational speed.
I would remove the description of PARAM2.

MAV_CMD_CONDITION_YAW: Enable rotation speed

---

dev/source/docs/apsync-intro.rst

I'm using the latest APSync for Raspberry Pi. 
If SEREAL2_PROTOCOL = 1, below error occurs in APWeb and nothing is displayed.
If SEREAL2_PROTOCOL = 2, the error does not occur, and APWeb is displayed normally.
Shouldn't this parameter value be changed?

 Update SERIAL2_PROTOCOL value for APSync/APWeb

---

common/source/docs/common-FPort-receivers.rst

I spent a lot of time confused why the sensors don't show up in OpenTX even though they worked in s.port mode.. Added a blurb to hopefully clarify the point that Yaapu script has to be enabled for the sensors to appear.

Clarify F.Port setup steps required on OpenTX side

---

plane/source/docs/apms-failsafe-function.rst

We can point users here to help with their diagnosis. Random numbers mean nothing to users, and I can't find this table anywhere else. I hope I've pulled it correctly from ModeResason.h and defines.h

Plane: Falisafe TYPE=X REASON=X enum references

---

common/source/docs/common-downloads_firmware.rst

There was no link to the submarine.
I will add the submarine firmware link.

Add a submarine link

---

dev/source/docs/learning-ardupilot-threading.rst

Fixed some typos that I found [here ](https://ardupilot.org/dev/docs/learning-ardupilot-threading.html#hal-specific-threads)

Wiki:Dev:Fixed some typos

---

plane/source/docs/soaring.rst

@Hwurzburg I haven't been able to reproduce the behaviour described in the warning - this removes it and fixes the description to match the behaviour.

Soaring: Improve MAX_RADIUS doc and remove unnecessary warning.

---

common/source/docs/common-3d-mapping.rst
common/source/docs/common-lightware-sf10-lidar.rst
common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst
common/source/docs/common-px4flow-overview.rst
common/source/docs/common-rangefinder-lidarlite.rst
common/source/docs/common-rangefinder-maxbotixi2c.rst
common/source/docs/common-rangefinder-sf02.rst
common/source/docs/common-rc-transmitter-flight-mode-configuration.rst
common/source/docs/common-rcmap.rst
common/source/docs/common-simplebgc-gimbal.rst
common/source/docs/common-storm32-gimbal.rst
copter/source/docs/ac2_positionmode.rst
copter/source/docs/acro-mode.rst
copter/source/docs/altholdmode.rst
copter/source/docs/boat-mode.rst
copter/source/docs/brake-mode.rst
copter/source/docs/channel-7-and-8-options.rst
copter/source/docs/ekf-inav-failsafe.rst
copter/source/docs/gps-failsafe-glitch-protection.rst
copter/source/docs/ground-effect-compensation.rst
copter/source/docs/poshold-mode.rst
copter/source/docs/precision-landing-with-irlock.rst
copter/source/docs/throw-mode.rst
copter/source/docs/traditional-helicopter-tuning.rst
dev/source/docs/ros-distance-sensors.rst

Start of wiki cleanup of outdated firmware reference. Per previous agreements only references to last two releases in a vehicle will be retained. Archived topics are exempt. And where large pieces of information would be removed, they will be archived in some manner instead of deleted.

Cleanup of out of date firmware references

---

mavproxy/source/docs/getting_started/starting.rst

Made some changes in the alignment of MavProxy wiki about [Startup Options ](https://ardupilot.org/mavproxy/docs/getting_started/starting.html#default-modules)
The comma-separated list of values defined in the default-module section seems to have an alignment issue :-
After the fix :-
Note- the above fix was tested on [rst online editor](http://rst.ninjs.org/)
THANKS !!!

starting.rst: Fix alignment issue

---

common/source/docs/common-gpios.rst

Requires #3305 to be merged first since it uses one of its images.

Expand info on determined GPIO pin number

---

dev/source/docs/building-setup-windows-cygwin.rst

I add XTERM in the setup list as a parameter.

Add Xterm to Cygwin's setup parameters

---

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst

@rmackay9 in addition to reviewing this, why do we have https://ardupilot.org/copter/docs/mission-command-list.html and this page? I see you have mission planner shots which are nice but outdated and some incorrect now, but this is duplication and a maintenance issue...
I think it might be better to expand the copter section of the common page with any missing information (if any) for commands, put a couple of mission planner shots showing a few waypoint type shots for commands at the top of the common page to give someone the info on where/how to change in mission planner and eliminate that page....lets discuss when you get time soon...

correct DO_CHANGE_SPEED descriptions

---

common/source/docs/common-simple-object-avoidance.rst

PRX_TYPE configuration on "Configuring Simple Avoidance for Copter" was on the loiter segment making it confiusing. Solves #2431

Changed PRX_TYPE configuration to common part

---

plane/source/docs/automatic-tuning-with-autotune.rst

Linked to issue https://github.com/ArduPilot/ardupilot/issues/16856 , autotune can fail if the maximum angular rates are larger than the aircraft can achieve. Add a note to the wiki page to check the rates are appropriate.

Autotune: Check maximum angular rate parameters

---

dev/source/docs/building-setup-windows-eclipse.rst

Python 2.7 does not get installed by following https://ardupilot.org/dev/docs/building-setup-windows-cygwin.html or running the https://github.com/ArduPilot/ardupilot/blob/master/Tools/environment_install/install-prereqs-windows.ps1 script, but Python 3.6 does.

Eclipse build under Windows lists python2.7 that is although not installed by prerequisites

---

plane/source/docs/guide-vtail-plane.rst

The RIGHT_VTAIL mixing equation in the documenation does not match the ArduPlane code. The [relevant code](https://github.com/ArduPilot/ardupilot/blob/29775f310e62f5a22d0af23a2d6541ad0b899c38/libraries/AP_IOMCU/iofirmware/mixer.cpp#L110-L116) is:
```cpp
int16_t AP_IOMCU_FW::mix_elevon_vtail(int16_t angle1, int16_t angle2, bool first_output) const
{
if (first_output) {
return (angle2 - angle1) * mixing.mixing_gain / 1000;
}
return (angle1 + angle2) * mixing.mixing_gain / 1000;
}
```
This function is called by the [following code](https://github.com/ArduPilot/ardupilot/blob/29775f310e62f5a22d0af23a2d6541ad0b899c38/libraries/AP_IOMCU/iofirmware/mixer.cpp#L209-L215):
```cpp
case SRV_Channel::k_vtail_left:
pwm = mix_output_angle(i, mix_elevon_vtail(rudder, pitch, false));
break;
case …
```

Corrects signs on the mixing equation

---

Sphinxsetup.sh
Vagrantfile
scripts/initvagrant.sh

This now makes a focal64 VM rather than a bionic VM.
The actual server is xenial64 and it runs Python2.  The  setup stuff here is all based around get-pip.py which is now Python3-only.
So we may as well move it forward to the current Ubuntu LTS.

Fixes for Vagrant VM

---

dev/source/docs/unit-tests.rst

@peterbarker : Thank you for pointing me to the right documentation. Small change to make the GTest link routable.

Unit tests: Correcting URL syntax

---

common/source/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.rst

The previous link ([https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/defines.h#L281](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/defines.h#L281)) No longer contains this information. It is now found at the corrected link ([https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Logger/AP_Logger.h#L94](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Logger/AP_Logger.h#L94)).

Corrects link for EV ID definitions

---

.gitignore
dev/source/docs/ap-peripheral-landing-page.rst

@peterbarker need params I mentioned to be emitted and captured in AP_Periph-Paramaters.rst file, then will add descriptions to them in this document...

Add params list to AP_Periph wiki

---

update.sh

Wiki is build when something is updated.
Inserting AP_Periph check as in the others vehicles.

Add AP_Periph updates in checks to update it on the Wiki

---

dev/source/docs/apmcopter-programming-attitude-control-2.rst

Flight modes used to be named control_<name>.cpp but appear to have been changed to the convention of mode_<name>.cpp. Changed docs to reflect this and fixed broken links to the source.

Fix flight mode names and links

---

dev/source/docs/the-ardupilot-autotest-framework.rst

This fixes a previous change of mine that had the build test steps going off the edge of the page. 
If there is a better way to fix it let me know?

Dev: autotest-framework fix text off page

---

common/source/docs/common-ads-b-receiver.rst
common/source/docs/common-oa-bendyruler.rst
common/source/docs/common-oa-dijkstrabendyruler.rst
common/source/docs/common-object-avoidance-landing-page.rst
common/source/docs/common-proximity-landingpage.rst
common/source/docs/common-rangefinder-landingpage.rst
common/source/docs/common-rangefinder-setup.rst
common/source/docs/common-simple-object-avoidance.rst

This updates Path Planning libraries documentation to Copter/Rover 4.1. This also sets up a new "proximity" hardware page, so that it can be removed from the rangefinder setup and have its own identity. I have also done some rearrangement to the main OA landing page.. hope it is fine. 
The only thing remaining from OA point of view is simple avoidance which is next on my list..  
I am really sorry @Hwurzburg for the huge delay despite the constant reminders from you. I had a branch ready, but needed videos or something else to complete it and hence did not push..

Update Obstacle Avoidance docs for Copter/Rover 4.1

---

copter/source/docs/failsafe-battery.rst

There are a maximum of  9 battery monitor instances currently.  [See here](https://github.com/ArduPilot/ardupilot/blob/7e79999b86855f91efcb12882d6f54aeebf49a9a/libraries/AP_BattMonitor/AP_BattMonitor.h#L10)

failsafe-battery: max. 9 battmontiors and minor fixes

---

dev/source/docs/using-gazebo-simulator-with-sitl.rst

fix typo "exaplation" to explanation

Wiki:Dev: fixed typo

---

copter/source/docs/sprayer.rst

Japanese drone manufacturer enRoute has transferred this vehicle maintenance to NTT e-Drone Technology.

copter: Change to the URL of the maintenance company

---

plane/source/docs/cruise-mode.rst

I added this note after reviewing a flight log where a user flew a large quadplane too close to the ground in CRUISE mode

plane: added a note on CRUISE mode

---

plane/source/docs/airspeed.rst
plane/source/docs/analog-airspeed-sensors.rst

SInce analog sensors are almost totally unavailable, moved to separate page (to allow future archiving) and added UAVCAN sensors.
also added links to partner's offerings for airspeed sensors page

Update airspeed sensor page

---

common/source/docs/common-prearm-safety-checks.rst

The judgment value of the source is 1m. However, in the WIKI, it is 2m.
I think it is better to match the source value.
judgment
https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/AP_Arming.cpp#L84

prearm: Match the distance to the source

---

plane/source/docs/starting-up-and-calibrating-arduplane.rst

I'm not sure how much this section of the docs is actually useful. FBWA should be for maintaining attitude and FBWB should for be height. This change at least makes it clearer that FBWA is for attitude.

Plane: Change verbage for FBWA attitude holding

---

dev/source/docs/static-analysis.rst

I also had to install clang tools, set both to version 7 to match CI

Dev: Static Analysis: add clang tools to Ubuntu install instructions

---

dev/source/docs/building-setup-windows-cygwin.rst

Saw this one on the site. Quick fix to have a Windows path show up correctly with escaping the escape character.

Fix backslash escape charaters

---

Sphinxsetup.sh

The install script was warning about unexpected...something. No warnings with this change because bash expects single square bracket operations to have single equal signs. Makes it easier to determine if an actual install error has happened.

Fix install script bash syntax

---

dev/source/docs/using-sitl-for-ardupilot-testing.rst

Parameter wind direction sets **from where** the wind is blowing
Tested by doing ALT_HOLD on 3m altitude, the copter is drifting north for these params:
- SIM_WIND_DIR 180
- SIM_WIND_SPD 3
- SIM_WIND_T_ALT 2
Just in case: drifts west for SIM_WIND_DIR 90

SiTL: Fix SIM_WIND_DIR explanation error

---

Sphinxsetup.sh
antennatracker/source/conf.py
ardupilot/source/conf.py
copter/source/conf.py
dev/source/conf.py
mavproxy/source/conf.py
plane/source/conf.py
planner/source/conf.py
planner2/source/conf.py
rover/source/conf.py

The sphinxcontrib.youtube plugin supports embedding Vimeo videos now. I did some spot checking to make sure that the video still worked as expected. The issue with using the current Vimeo plugin from our forked repo is that it does not support the latexpdf builder. The upstream repo is gone now.
One other option would be to add an `.. only:: html` block around each Vimeo video, but that creates an issue for when new Vimeo videos are added to the wiki.

Remove sphinxcontrib.vimeo plugin

---

common/source/docs/common-pixhawk-camera-trigger-setup.rst

From ArduPilot Facebook report
Aux6 should be Pin 55 not Pin 56 see picture above here,
https://ardupilot.org/copter/docs/common-pixhawk-overview.html

Copter: common-pixhawk-camera-setup AUX6 is Pin 55

---

plane/source/docs/apms-failsafe-function.rst

Bat FS reason was missing from the list and made the numbering incorrect from 3 up.

corrected FS "reason" 5 to GCS Failsafe

---

dev/source/docs/the-ardupilot-autotest-framework.rst

This helps the reader to directly jump to the commit being referred instead of putting efforts to search for the same first.

Added hyperlink to the commit being referred

---

dev/source/docs/copter-sitl-mavproxy-tutorial.rst

fixed a broken link that referenced to using-sitl-for-ardupilot-testing

fix broken link

---

dev/source/docs/learning-ardupilot-introduction.rst

We have already listed all vehicles in vehicle code section. Listing them in library section again is unnecessary and makes it less maintainable.

remove naming vehicle types in libraries section

---

dev/source/docs/gsoc.rst
dev/source/index.rst

in prep to add GSOC as a main bar menu subitem in new  non concrete web page

Re-org GSOC and add base page

---

dev/source/docs/building-setup-windows-cygwin.rst

This adds the toolchain option required to build custom binaries for mission planner's sitl.
From discord, @stephendade,
"Mission Planner needs a 32bit build of ArduPilot. Issue is that cygwin64 gcc builds a 64bit by default. Changing the toolchain to i686-pc-cygwin tells Cygwin to use the 32bit toolchain. See https://stackoverflow.com/questions/27344540/what-do-the-c-compilers-on-cygwin-generate for details of the Cygwin64 toolchains.
To be precise, the supplied dlls in the Mission Planner sitl folder are all 32bit, so the sitl exe needs to be 32bit as well"

Dev: update SITL Binaries Install Instructions

---

update.sh

In wiki server "python" is pyhton2.7 and it have PIP working correctaly.
For some reason calling PIP is now calling pip3 but server`s python3 is python3.5 without pip3.
The idea here is force the use of python2.7 because it is the default python on server.

Fixing wiki build script

---

dev/source/docs/using-sitl-for-ardupilot-testing.rst

Problem: param load command was having backslashes ' \ ' instead of forward slashes ' / ' . causing error in parameters loading.
Changes: Changed Backslashes to forward slashes

Wiki:Doc error: param load cmd, changed '\' to '/'

---

dev/source/docs/editing-the-code-with-vscode.rst

The existing link was not working. Added another working link.

Fixed: Page Not found error, Vscode WSL link

---

common/source/docs/common-wiki-editing-setup.rst

changed "ardupilo_wiki" to "ardupilot_wiki"

wiki: fixed a typo

---

dev/source/docs/code-overview-adding-a-new-parameter.rst

This PR adds some details around a new process to be implimented when adding parameter conversions.  It also updates the steps to perform a parameter conversion.
The process is simple: add a standard expression: PARAMETER_CONVERSION that we can grep for.  And detail the date and version when the conversion can be removed.  This is based on what has been disscussed on Discord and the dev call.  Happy to modify the process as maintainers think is appropriate. 
Once, we are happy with the process, I am happy to go on a hunt to find the already added conversions to add the comments appropriatley.

Dev: Add param conversion removal process

---

dev/source/docs/copter-commands-in-guided-mode.rst
dev/source/docs/mavlink-commands.rst
dev/source/docs/mavlink-get-set-home-and-origin.rst
dev/source/docs/mavlink-other-commands.rst

This PR attempts to make it easier for developers to find the mavlink interface messages they are looking for by splitting upC Copter's commands page into two pages.  One for movement related commands (which is what most devs want) and non-movement related commands (which actually apply to all vehicles I think)
I have tested these changes on my local WSL machine and they seem OK.

Dev: small update to mavlink interface section

---

common/source/docs/common-autopilots.rst

This adds a link to find schematics for **some** of the open hardware boards
I have tested this change on my local WSL machine and it seems OK.

Common: autopilots page gets link to schematics

---

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst
dev/source/docs/copter-commands-in-guided-mode.rst
dev/source/docs/mavlink-other-commands.rst
dev/source/docs/plane-commands-in-guided-mode.rst

This PR improves the "MAVLink Interface" page for Plane by:
- Reducing the scope of the page so it only covers movement commands.  Non-movement commands are mostly consistent across vehicles so we have new pages for these.  All commands removed from the Plane page have been added to other pages (if they weren't there already)
- clarifies that the MAV_CMD_NAV_WAYPOINT must be within a MISSION_ITEM_INT and provides details on what fields to set and even gives 3 examples that can be copy-pasted into SITL/MAVProxy
- adds DO_REPOSITION message to the list of MAV_CMDs supported
This PR also includes a couple of drive-by improvement:
- Improved formatting of the mavlink-mission-command-messages page by removing the blank lines between each command.  This makes it easier for readers to scan the …

Dev: mavlink interface for Plane

---

dev/source/docs/mavlink-commands.rst
dev/source/docs/mavlink-move-servo.rst

This adds another page to our MAVLink Interface section.  This time it explains how to move a servo.
As a matter of course I uncovered an apparent bug in how we interpret one of the commands. https://github.com/ArduPilot/ardupilot/issues/19596

Dev: mavlink interface gets instructions on moving a servo

---

common/source/docs/common-holybro-rtk-f9p.rst
common/source/docs/common-holybro-rtk-m8p.rst

add "If unable to preform normal compass calibration "compass dance" for any reason, set parameter COMPASS_ORIENT=6 (Yaw270) for proper compass orientation."

update Holybro RTK wiki

---

common/source/docs/common-cheerson-cxof.rst

URL link error 404 occurred in ThoneFlow-3901U.
I will fix the URL.

Common: Fixing URL link errors in ThoneFlow-3901U

---

dev/source/docs/release-procedures.rst

This new web page makes it easier to know the state of the automatic build as part of release procedures.
I have tested this on my local machine.

Dev: add Build list page to copter release procedures

---

dev/source/docs/copter-commands-in-guided-mode.rst

At leaste one user struggled to stop the vehicle from yawing when providing body-frame velocities so this provides two specific examples (one for velocity, one for acceleration).
https://discuss.ardupilot.org/t/fly-in-circles-with-set-position-target-local-ned-command/80289/3
I've tested this locally on my machine and it looks ok.

Dev: mavlink interface copter command examples of moving right without yawing

---

common/source/docs/common-logs.rst
update.py

The log message page had the wrong case (logmessages.rst vs LogMessages.rst).
This PR restores it back to all lower-case

Fix case error with log messages

---

common/source/docs/common-vtx.rst

* Clarify CRSF setup when Vtx and RC receiver both use the protocol. I saw a thread w/ someone who was trying to use CRSF w/ both rx and Vtx and wanted to record the info here, I made the same mistake of trying to use CRSF directly from the FC for both. I ended up just using SmartAudio instead, which is working great.
* Add details to RCx_OPTION usage around PWM range and output power settings. The most important part here was PWM range for me (my tx sends 1000-2000 so a 3-position switch wasn't overlapping with the 6-position switch interpretation well). Short of copying the code for assigning vtx power levels into here as a table (which could be useful!) I figured one example would help folks figure out what's going on.

Add details in video transmitter setup.

---

common/source/docs/common-advanced-configuration.rst
common/source/docs/common-cheerson-cxof.rst
common/source/docs/common-hereflow.rst
common/source/docs/common-openmv-optflow.rst
common/source/docs/common-optical-flow-sensor-setup.rst
common/source/docs/common-upixels-upflow.rst

This adds insturctions for the inflight optical flow calibration that will be in 4.2 once this PR is merged. 
https://github.com/ArduPilot/ardupilot/pull/19874
I'm pretty confident that this will go in and it will help us get more people testing it.
I've also included a bit of a drive-by change to remove some old notes on version and the recommend that users set the FLOW_POS_XYZ parameters to improve performance.  In my testing it makes a significant difference at least at higher altitudes.
.. and finally I changed the link on the Advanced Configuration page to point to the landing page instead of jumping straight to the setup page.
I've tested this on my local machine.

Common: Optical Flow inflight calibration instructions

---

common/source/docs/common-non-gps-to-gps.rst
common/source/docs/common-optical-flow-sensor-setup.rst

This completes the wiki instructions for the new optical flow inflight calibration feature
This has been tested on my local machine.

Common: optflow setup page gets inflight cal video

---

dev/source/docs/mavlink-requesting-data.rst

This PR clarifies that stream rates are 4x slower or more if parameters and waypoints are currently being sent. If you want me to link the docs to the [source ](https://github.com/ardupilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_Common.cpp#L954) where this happens, let me know.

Stream rates are slower while sending parameters and waypoints

---

common/source/docs/common-mounting-the-flight-controller.rst
rover/source/docs/reference-frames-deset-mapping-boat.rst

This PR includes two unrelated changes:
1. the DeSET boat reference frame gets a link to a blog post I wrote with some more info on the frame
2. the mounting-the-flight-controller page gets a link to the sensor-position-offset-compensation page to resolve [this issue](https://github.com/ArduPilot/ardupilot/issues/20135)
This has been tested on my machine so I'm pretty sure it is OK.

Rover/Common: add a couple of links to a reference frame and mounting-the-flight-controller pages

---

plane/source/docs/airspeed-parameters-setup.rst
plane/source/docs/plane-configuration-landing-page.rst

ArduPlane defaults the Airspeed sensor to MS4525, which the code in ArduPlane 4.2 will flag as an error if there is no airspeed sensor or a different one. In the past this would have happened silently, but now an error will appear on the GCS, which might be confusing. 
This doc change attempts to clarify that if there is no airspeed sensor, the ARSPD_TYPE should be set to 0 otherwise an error will occur.

Clarify requirements for setting up an Airspeed sensor on a new build

---

common/source/docs/common-escs-and-motors.rst
common/source/docs/common-optional-hardware.rst
rover/source/docs/boat-configuration.rst

This moves the Torqeedo page to the ESC-and-motors landing page instead of on it's own page in the Peripheral Hardware section.
I've also updated the "boat" page:
- added torqeedo to the page
- removed mentions of ancient versions
- reordered alphabetically
This has been tested on my local machine

Rover: move torqeedo to ESCs-and-Motors

---

common/source/docs/common-connecting-sport-fport.rst

As per https://discuss.ardupilot.org/t/solved-cube-orange-and-x8r-frsky-s-port-telemetry-not-working/73556/2 and https://discuss.cubepilot.org/t/frsky-pass-through-protocol-on-serial-5/120/11
Tested and confirmed that this is required on Cube Orange.

Common: Add note about pulldown for FPort on Cube Orange

---

dev/source/docs/using-sitl-for-ardupilot-testing.rst

I found that the SITL instructions were missing some critical parameter settings so here they are.  I've tested these changes on my local machine.
FYI @peterbarker

Dev: fixup SITL preclanding setup instructions

---

dev/source/docs/mavlink-get-set-home-and-origin.rst

This PR updates the mavlink-get-set-home-and-origin page to use MAV_CMD_DO_SET_HOME instead of the deprecated SET_HOME_POSITION message.  It also adds some examples to make it easier to test the message.
This has been tested on my local machine.

Dev: mavlink interface gets update do-set-home

---

common/source/docs/common-minim-osd-quick-installation-guide.rst

As part of Copter-4.2 beta testing a user found that the MinimOSD didn't work.  This adds a note to specifying the SERIALx_PROTOCOL must be set to 1.
I've also included some minor fixes to remove dead links and make it less APM and pixhawk specific
This has been tested on my local machine

Common: minimosd gets serial-protocol note

---

plane/source/docs/automatic-tuning-with-autotune.rst

AUTOTUNE can be done in any stabilized flight mode from 4.1.3, not 4.2. I had a discussion with @tridge to confirm, and these changes were already merged to 4.1.3 in November last year.

AUTOTUNE available in stabilized modes from 4.1.3 not 4.2

---

common/source/docs/common-dshot-escs.rst
common/source/docs/common-flywoo-f745.rst
common/source/docs/common-imu-notch-filtering.rst
common/source/docs/common-omnibusnanov6.rst
common/source/docs/common-power-module-configuration-in-mission-planner.rst
common/source/docs/common-rpm.rst
common/source/docs/common-serial-options.rst

This PR fixes a number of broken links that appeared with the recent update to the DShot and BLHeli pages.
- Fixed small typo affecting a link on the new dshot wiki page.
- Fixed various links to ESC telemetry.  One page had two links, one to the DShot page and another to the BLHeli page.. these have now been combined together so I removed one of the links.  It's possible that we could have instead provided a link to the Bi-directional dshot section that can also provide RPM but without the need for a separate telemetry wire.
This has been tested on my local PC.

Common: fix links on or to dshot and BLHeli pages

---

common/source/docs/common-torqeedo.rst

This adds links to where people can purchase a ready-to-use interface board.  The linked site is my company's web site and sadly it's all in Japanese but it's better than the link it replaces which was also only in Japanese and there was no actually way to buy the product from the site.
I've tested this on my local machine.

Common: update Torqeedo links to adapter board from Japan Drones

---

common/source/docs/common-dshot-escs.rst

This makes the DShot Commands section slightly more clear (I think) by putting the relevant parameters in a list.
I've tested this on my local machine and after this PR it looks like this
It's still not great because this section starts with the "how" (e.g. dshot commands) instead of the "what" or "why" (e.g. "Using DShot to reverse the direction of the motors, use the ESCs LEDs for autopilot status, use the motors as buzzers".

Common: dshot command parameters put in list

---

common/source/docs/common-auxiliary-functions.rst
common/source/docs/common-buttons.rst

This makes the setup of buttons easier to follow at the cost of some duplication.
I've tested this on my local PC and the output looks like below.  I've also actually tested the feature on my CubeOrange to confirm that the instructions are correct.

Common: button clarification

---

common/source/docs/common-msp-osd-overview-4.2.rst

Not bit 0, not bit 1, but bit 2.
Definitely not bit 3.

msp-osd: correct bit referenced to use BetaFlight fonts

---

dev/source/docs/ros-cartographer-slam.rst

```make uninstall``` is no longer working i have tested many times. catkin build gives error everytime until the package is removed. I solved (or ignored) this problem by just removing this package from the list everytime when i do a ```catkin build```. (Note that compiled package is still in ROS build folder i am using that from my first compilation). until anyone get a solution we should remove this Instruction.

Wiki:ROS Removed Note for protobuf removal

---

copter/source/docs/airspeed-estimation.rst

This fixes up the copter wind speed estimation's page's statement re the expected range of the EK3_DRAG_MCOEF parameter.  I had incorrectly said it was 1 to 2 but in fact it is 0.1 to 1.0 which [matches the parameter description](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_NavEKF3/AP_NavEKF3.cpp#L693) and also my findings from actually flight tests.
I have not actually tested this change on my local PC but surely it's fine.

Copter: fixup wind speed est param range

---

common/source/docs/common-dshot-escs.rst

corrected docs to clearly indicate that only bi-directional dshot is linited to aux 2-6, all other channels are usable for single directional

d-shot doc update

---

common/source/docs/common-blheli32-passthru.rst
rover/source/docs/boat-configuration.rst
rover/source/docs/thrusters.rst

This PR makes two mostly unrelated changes:
- the thrusters page is change to "BlueRobotics Thrusters" which is more specific and accurate
- Two subsections of the BLHeli page have their title underlines demoted to stop them from appearing on the "ESCs and Motors" landing page
I have tested this on my local machine.

Minor fixup for BlueRobotics Thrusters, demote title line of two of BLHeli's subsections

---

dev/source/docs/style-guide.rst

Both 'Right' examples under 'Functions and variables' were missing a blank link below :: and not being styled as code blocks.

Fixed code block styling Functions and variables.

---

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst
copter/source/docs/mission-command-list.rst

Changed implementation for radius of LOITER_TURNS at "ArduCopter: support *10 multipler when storing/retrieving radius in NAV_LOITER_TURNS" .
I would like to note in the WIKI that the radius does not change smoothly.

LOITER_TURNS: Add a radius item

---

copter/source/docs/mission-command-list.rst

This renames a title on the Copter specific mission command list from Package Place to Payload Place to better match the command's actual name.  I've also removed a couple of old version related comments that shouldn't be needed any more.
I have tested this locally

Copter: rename Package Place to Payload Place

---

copter/source/docs/esc-calibration.rst

Updates the ESC calibration page to clarify that digital protocols like DShot don't need to be calibrated.
Also the difference between brake on stop and active braking in ESC settings as current settings are unclear as to which is referred to.
Also removed some references to the APMs.
@tridge I've added CAN ESCs in here as well as you suggested, though it seems like this would only apply to integrated CAN ESCs - ESCs that use PWM but via a CAN adapter would still need to be calibrated somehow, right? Not sure if we need to mention this on the page or if it's clear enough?

Update ESC calibration page for DShot and active braking

---

common/source/docs/common-ice.rst

Added a section of the idle and redline governors. Also removed an exclusion tag that had some information that might be useful for plane operators.
Part of #4274

Common ICE: Add Idle and redline governor sections

---

Sphinxsetup.sh

Ran into an issue where setting up the environment without firewall access for xserver on WSL 2 leads to pip not running. Haven't tracked down why that is, but disabling display output fixes the issue. So while we get the environment set up in WSL 2, just clear the variable and then return it after we are done. This will cause an issue if pip bails out at some point in the middle of installed packages. There might be a better way to handle that case in bash.
See https://stackoverflow.com/questions/33925566/pip-install-hangs

Sphinxsetup.sh: Add WSL pip DISPLAY workaround

---

dev/source/docs/ros-cartographer-slam.rst

Updated the instructions for cartographer SLAM and shifted from EKF2 to EKF3 configuration.  Added more parameters in Cartographer.lua for a much better mapping and localization using cartographer SLAM.

Cartographer SLAM: Updated instructions for Non-GPS navigation

---

common/source/docs/common-qiotek-zealoth7.rst

The CAN ports are disabled by default. It's important to note that each of the CAN ports needs to be enabled if it is going to be used.

Add CAN port description to Zealot H743

---

common/source/docs/common-omnibusf4pro.rst

current wiki is incorrect , in HWDAT it says that the pins 54 and 55 for output 5 and 6.
PA1 TIM2_CH2  TIM2 PWM(5) GPIO(54)
PA8 TIM1_CH1  TIM1 PWM(6) GPIO(55)

correcting relay pin settings for omnibusf4pro.

---

dev/source/docs/porting.rst

When a board name is sent in status messages to the ground station, the name is truncated at 13 characters. The board can be named longer than 13 characters, but only 13 are sent, so a suggestion to keep to 13 characters or less when naming the board might help prevent confusion.

Add board name tip for 13 character issue

---

common/source/docs/common-remoteid.rst

This PR makes three changes:
-  moves Dronetag Mini up into the "MAVLink enabled devices" section
- removes the "JP" label next to BlueMark's device.  [This list from the Japanese ministry of transportation](https://www.mlit.go.jp/koku/content/001484158.pdf) is the official list of devices that can be used in Japan (as expected a "giteki" is required I think).
- adds a link to the OpenDroneId list of transmitter devices
I've tested this on my local machine and it looks OK.

Common: minor fixes to Remote id page

---

common/source/docs/common-oem-customizations.rst
dev/source/docs/apjtools-intro.rst

Updates OEM customization page to reference APJ Tools. Also changed the example to use an autopilot that has more RAM to use the Lua scripting features. Added Lua scripting references. Also a quick pass on grammar.
Closes #3528

common: Update OEM customization options

---

.vscode/extensions.json
.vscode/tasks.json

A few extensions and a task to get new wiki writers using VSCode up to speed quickly. The wiki structure we have is not the greatest with the preview extension, but changing the conf.py file used for building the preview is pretty easy in the bottom left. Previewing common pages is not really possible though.

Add VSCode tasks and recommended extensions

---

common/source/docs/common-imu-fft.rst

An obvious bug has been introduced when updating the docs to include HNTC2 parameters.
I know at least one person who followed the new doc and got a mystically unflyable copter. Effectively, every input was filtered out with FREQ=1 and BW=120.
This fixes it.

Fix FFT documentation: FREQ=>REF

---

common/source/docs/common-cameras-and-gimbals.rst
common/source/docs/common-gremsy-pixyu-gimbal.rst

This PR makes two changes:
- Removes the Pixy SM and adds T3 and T7 to the list of supported gimbals
- Adds RC9_OPTION parameter setting for "lock" vs "follow"
This has been tested on my local machine

Common: Gremsy setup fixes

---

common/source/docs/common-remoteid.rst

TEAD Corporation is another company that develops and sells external remote IDs in Japan.
I have confirmed that I can receive the remote ID information reported by TEAD Corporation's Remote ID in the ANDROID application of the OPEN DRONE ID project.
TEAD CO.LTD.
https://www.tead.co.jp/product/remote-id/

RenoteID: Add external remote ID development and sales company in Japan

---

common/source/docs/common-storm32-gimbal.rst

This makes a few changes to the SToRM32 gimbal setup instructions:
1. clarifies which users should use the MAVLink vs Serial interface ([see discussion here](https://discuss.ardupilot.org/t/does-anyone-use-storm32-serial-gimbal-driver/89697))
2. adds hyperlinks to all parameters
3. replaces "pixhawk" with "autpilot"
4. other minor wording changes
this has been tested on my local machine
FYI @olliw42

Common: SToRM32 gimbal setup improvements

---

common/source/docs/common-holybro-pixhawk6C.rst

Correct BATT2_VOLT_PIN & BATT2_CURR_PIN mistake, remove "Coming Soon" on Pix32 v6, adjust main image size.

Update Pixhawk 6C Wiki

---

dev/source/docs/using-sitl-for-ardupilot-testing.rst

People may get to this page via a Google search and not realise that they need to do more than just cloning the repository in order to run sim_vehicle.py....

Add note on build environment to SITL page

---

plane/source/docs/apms-failsafe-function.rst

So far it is not made clear that a mode change during the failsafe period (RC aborts, failsafe is active, user changes mode at the transmitter) results in this mode being activated directly after the connection is restored.

Handling mode change in failsafe period

---

dev/source/docs/using-sitl-for-ardupilot-testing.rst

This slightly modifies the Using SITL page so that it adds the "--mcast" to the command line when starting multiple vehicles.
I've tested this on my local machine.
FYI @tridge

dev: SITL for multivehicles should use mcast

---

common/source/docs/common-remoteid.rst

Braveridge, a Japanese company, has developed and begun marketing a remote ID for external use.
The company's remote ID is 28,000 yen cheaper, including tax, than EAMS and TEAD.
The company also drills holes for installation with mini-drones in mind.
The price is open price.
At one dealer, it is 15180 yen including tax.
https://www.braveridge.com/product/archives/49

RemoteID: Add a Braveridge company in Japan

---

common/source/docs/common-ap-periph-usage-examples.rst
common/source/docs/common-uavcan-adapter-node.rst
common/source/docs/common-uavcan-peripherals.rst
dev/source/docs/ap-peripheral-landing-page.rst

Adds a page to hold examples of using AP_Periph for different use cases. First one up is the DShot and PWM example.
Covers one item in #3688.

Add AP_Periph DShot and PWM example

---

.github/workflows/test-Windows.yml
.github/workflows/test.yml
common/source/docs/common-choosing-a-ground-station.rst
common/source/docs/common-imu-fft-advanced-setup.rst
common/source/docs/common-transmitter-tuning.rst
dev/source/docs/opendroneid.rst
plane/source/docs/advanced-failsafe-configuration.rst
plane/source/docs/automatic-landing.rst
plane/source/docs/reverse-thrust-setup.rst
planner/source/docs/mission-planner-flight-data.rst

Also one or two grammar things I caught on a quick glance. I also realized there are there are trailing spaces after refs sometimes. Doesn't break the creation of the hyperlink though. Just looks odd.

Fix characters before ref tags causing issues and add step to Linux CI job

---

common/source/docs/common-holybro-kakutef4-mini.rst

Subj. SP soldering pad is connected to UART1/Serial1 but not to Serial2

Fix serial port number in telemetry section of Holybro KakuteF4 Mini

---

Sphinxsetup.bat
Sphinxsetup.sh
common_conf.py
update.py

There are a few thing going on here. This is to get local environments functional again after the changes yesterday. This also makes it safer to run Sphinxsetup.sh on the build server because more of the package versions match what is used locally and in CI. There might still be issues, but at least the big name ones are solved by this PR.
- Pin down sphinx to a known working version and so that the build server will match local.
- Pin down docutils so that bullet points will be rendered when using the older sphinx rtd theme. See https://stackoverflow.com/a/68685753/2578171 for details.
- Fix a build error due to destdir being None by default now.
- Add the correct package name for sphinxcontrib-youtube
- Add version checking for docuilts, sphinxcontrib-youtube, and sphinx
- Add a message …

Pin down python package versions and fix build errors

---

update.py

@peterbarker
This might be a nice touch to add. Sphinx 5.1.1 supports >3.7. We can keep it level with Ubuntu 20.04 for now though. Would this also mean that the distutils import above could be removed? In fact, I'm not sure the difference to os.mkdirs or the pathlib method.

Add minimum python version of 3.8

---

mavproxy/source/docs/getting_started/download_and_installation.rst

When adding ~/.local/bin to the path in .bashrc,
bash will first expand $PATH in the following:
echo "export PATH=$PATH:$HOME/.local/bin" >> ~/.bashrc
to something like:
export PATH="/usr/bin:/bin:/home/user/.path/to/remove/later:/home/user/.local/bin"
which nullifies future modifications to PATH made earlier in .bashrc, which can be confusing.

mavproxy: fix appending path to bashrc

---

update.py

This fixes an issue that came up in the Windows CI job. Make sure the destination exists before trying to put something there.
@tridge

update.py: Fix Windows CI copying jquery

---

.github/workflows/test.yml
update.py

Move the regex for the ref directive formatting from a Linux only command to Python in update.py. This is working on Windows and Linux in CI.

Move ref directive regex check from CI to update.py

---

copter/source/docs/deadreckoning-failsafe.rst
copter/source/docs/failsafe-landing-page.rst

This adds setup and testing instructions for Copter-4.3's dead reckoning failsafe.  In all honesty, this feature's performance is not as good as hoped but it is included in Copter-4.3 so people should know about it.
This change has been tested on my local machine.

Copter: add dead-reckoning failsafe explanation

---

copter/source/docs/input-shaping.rst

This PR updates the wiki for the new parameters introduced in Copter 4.3.  These parameters adjust the time constant for achieving steady state rate for axes that are rate command for a given mode.  
PILOT_Y_RATE_TC - yaw rate time constant for all  modes except acro
ACRO_RP_RATE_TC - acro roll/pitch rate time constant
ACRO_Y_RATE_TC  - acro yaw rate time constant
I also updated the Input shaping wiki for the max rate parameters which were updated in 4.1 ( i think).

Update copter for new RATE_TC params

---

copter/source/docs/traditional-helicopter-parameter-list.rst

This updates the trad heli Params page with the new Params in Copter 4.3.0

update heli param page with 4.3 params

---

common/source/docs/common-tbs-rc.rst

@Hwurzburg 
If you only with to use CRSF for VTX control then connect the VTX to the UART in the normal way - TX to RX and RX to TX and configure the UART connection as follows:  change to following:
If you only wish to use CRSF for VTX control then connect the VTX to the UART in the normal way - TX to RX and RX to TX and configure the UART connection as follows:

Update Wiki common-tbs-rc.rst: fix typos

---

copter/source/docs/reference-frames-hexsoon-edu450.rst
copter/source/docs/reference-frames.rst

Also add hyphen between EDU and 450 which is how CubePilot refers to the frame

Copter: reference page for edu-450 provides link to manufacturer's specifications

---

common/source/docs/common-efi.rst

Documentation for Currawong ECU set up and links to products.
https://github.com/ArduPilot/ardupilot/pull/20399

Common: Add Currawong-ECU/PiccoloCAN EFI

---

common/source/docs/common-rpm-based-notch.rst

Added a few extra words to make it clearer that the INS_HNTCH_FREQ is a lower limit constrain.

Add clarification to HNTCH_FREQ for RPM based

---

rover/source/docs/balance_bot-hardware.rst
rover/source/docs/balance_bot-home.rst
rover/source/docs/balance_bot-issues.rst
rover/source/docs/balance_bot-working.rst

This removes an out-of-date version warning and improves conciseness of the balance bot setup pages.

Rover: small balance bot fixes

---

common/source/docs/common-gremsy-pixyu-gimbal.rst

Now that AP4.3 has gone live we can move the Gremsy setup instructions for 4.3 above the 4.2 instructions.
This has been tested on my local machine and looks OK.

Common: move Gremsy setup instructions for AP4.3 above AP4.2

---

dev/source/docs/ros.rst

MAVROS is a collection of rosnodes, and a collection of rosnodes is often referred as a package

docs: small correction in terminology

---

common/source/docs/common-remoteid.rst

added in the mro remoteID that is based on the ESP32-C3

Update: remote ID compatible devices

---

plane/source/docs/arming-your-plane.rst

I understand that `RCx_OPTION` `ArmDisarm` changed from 41 to 153 in 4.2. If it's desirable to note that older versions use 41, I can amend the PR.

plane: updating ArmDisarm for 4.2 and higher

---

common/source/docs/common-cuav-v5plus-overview.rst

the official retailer link for AliExpress was broken updated to proper link that works. https://leixun.aliexpress.com/store/all-wholesale-products/1101268771.html?spm=a2g0o.store_pc_promotion.pcShopHead_7913971.1

Update: fixed broken link Aliexpress

---

common/source/docs/common-beagle-bone-blue.rst

this link or website is no longer active removed link from more links 
- `ArduPilot for beginners. Installation and configuration on BeagleBone Blue / Sudo Null IT News <https://sudonull.com/post/8513-ArduPilot-for-beginners-Installation-and-configuration-on-BeagleBone-Blue>`__

Remove: broken link on beaglebone blue page

---

rover/source/docs/balance_bot-tuning.rst

Rover wiki's balance bot tuning page updated to match PR https://github.com/ArduPilot/ardupilot/pull/22169 which will be released with Rover-4.3 in the (hopefully) near future.
I've tested this on my local machine and it looks OK.

Rover: balance bot feed forward update

---

copter/source/docs/copter-use-case-overview.rst

the link for dronekit python was broken (http://python.dronekit.io/) changed link to https://github.com/dronekit/dronekit-python is this what it should be or should we just link it to https://dronekit.io/

update: dronekit python link

---

dev/source/docs/porting.rst

Previous list used eg STM32F41x notation, which implied that certain MCUs with less than 1 MB of flash were supported.

Update the list of supported MCUs

---

common/source/docs/common-benewake-tf02-lidar.rst

I would add TF02 Pro.
http://en.benewake.com/product/detail/5c345c9de5b3a844c4723299.html
The TF02 Pro frame does not have SIG.
The TF02 Pro is at device temperature.
I have the TF02 EOL.
I removed the TF02 link.

benewake: Add TF02 Pro

---

common/source/docs/common-brushless-pwm-gimbal.rst
common/source/docs/common-cameras-and-gimbals.rst

This adds a Brushless PWM gimbal setup page which is supported in AP 4.3.
I've reused the Tarot gimbal images for now because this is all I have.  The Tarot gimbal is a decent example of this kind of setup though although sadly the one shown only provides pitch control.  Still, I think this is an improvement and will at least give me a page to point users at when they struggle to setup brushless pwm gimbals with AP-4.3.
I have tested this on my local machine and it seems ok.

Common: add brushless pwm gimbal setup

---

common/source/docs/common-telemetry-robsense-swarmlink.rst

This resolves the broken links on the AP Robsense telemetry page.  It is slightly questionable whether the RobSense stuff works anymore because their [EasySwarm software GitHub page](https://guide.robsense.com/chapter3-1/communication/easyswarm.html) lists Copter-3.3 as the version it supports... still, I guess this is an improvement.
I've tested this locally on my machine and it seems OK.
EDIT: I emailed our contact at Robsense but received a failed-to-deliver message immediately.  I think maybe we should move this page to the archive section.

Common: fixup robsense swarm link links

---

common/source/docs/common-telemetry-robsense-swarmlink.rst

This adds a warning to the Robsense telemetry page to warn users away from this product.  The reason I'm adding this warning is that I've received a complaint from a user that their order was cancelled and the email that we had on file for the CEO of the company no longer works.  There is also no longer an easy way to purchase the telemetry radio.
I've tested this on my local machine.

Common: add warning to Robsense swarm link

---

dev/source/docs/sitl-native-on-windows.rst

the cygwin project has recently dropped support for 32bit, microsoft has stopped allowing new 32bit OS installs approx two years ago, windows 7 went end-of-life in 2020.

cygwin64 needs a 64bit OS, and

---

copter/source/docs/connect-escs-and-motors.rst

Moves Y4 up to the quad section. It being down in hex is causing some confusion. 
https://github.com/ArduPilot/ardupilot/issues/22372
https://discuss.ardupilot.org/t/quadcopter-in-tricopter-formation/87121

connect-esc-and-motors: move Y4 to quad section

---

common/source/docs/common-external-ahrs.rst

Not all VectorNav units that are on the linked products page are currently supported.  Adding model number of the unit that is supported to prevent confusion.
Other VectorNav units may already work.  But I know that at least one of them doesn't (VN-100) at this time.

Add supported model number to VectorNav

---

common/source/docs/common-flight-controller-io.rst

I just fixed a small typo: "I" -> "It"

Fix typo in common-flight-controller-io.rst

---

common/source/docs/common-simplebgc-gimbal.rst

This attempts to clarify the SimpleBGC (aka AlexMos) gimbal setup.
I noticed some minor formatting issues on the page and this led me down a rabbit hole as I tried to clarify the page.  It seems that about 4 years ago the gimbal gained support for MAVLink and PR https://github.com/ArduPilot/ardupilot_wiki/pull/1505 attempted to add documentation for this.  The PR somewhat muddled up the instructions though so I've attempted to separate the two setup methods.
Maybe @elcoach85 is still out there and would like to comment on the new format of the page.
I've tested this on my local machine and the page looks OK.  I don't actually have a SimpleBGC gimbal to test the two setups.  I'm not sure many people do anymore.

Common: SimpleBGC gimbal setup clarification

---

common/source/docs/common-terrain-following.rst

this is what it was "https://terrain.ardupilot.org/data/" this gives a 404 error. this is what I believe should be the new link "https://terrain.ardupilot.org/continentsdat3/"

Update terrain tile webpage that was broken

---

common/source/docs/common-autopilots.rst

Just a few formatting fixups to the autopilot page:
- fix the bullet points on the unsupported boards section
- make the use of * consistent across categories
I've tested this on my local machine and it seems ok.

Common: minor formatting fixes to autpilots page

---

common/source/docs/common-rc-transmitter-flight-mode-configuration.rst

Currently, on Copter, the wiki states that the flight mode channel is always channel 5. But this parameter has been added since Jan 27, 2018 on commit 89674482a717bd280c594c408c6feec7d569fac9 of the main firmware repo.

Fix Copter Flight Mode Channel Description

---

common/source/docs/common-siyi-zr10-gimbal.rst

This fixes a simple and obvious bug on the siyi gimbal setup wiki page.
I have not tested this on my local machine but surely it is fine.

Common: fixup siyi yaw-max param recommendation

---

common/source/docs/common-cameras-and-gimbals.rst

This removes the AP version info from the Siyi line on the cameras and gimbals landing page.  The Siyi page itself already has a note on the required version so I think it is fine to remove it from here to reduce maintenance.
I have not tested this on my local machine but surely it is fine.

Common: remove siyi version note from gimbal landing page

---

dev/source/docs/sitl-with-webots.rst

Added a note about Webots version that is currently working and improved the instructions on how to build the controller and physics plugin. Using the updated instructions I have a basic working Webots environment.

Improved Webots simulation build instructions

---

common/source/docs/common-remoteid.rst

I would add AEROENTRY, a company that develops and sells remote ID devices to Japanese specifications.
URL
https://aeroentry.co.jp/info/product/228/

RemoteID: Add an AEROENTRY company

---

common/source/docs/common-siyi-zr10-gimbal.rst

This adds a missing parameter setting required to allow autonomous or manual control of the Siyi cameras.
I've tested this on my local machine and it seems fine.

Common: siyi gimbal param change to control camera

---

common/source/docs/common-cameras-and-gimbals.rst
common/source/docs/common-gremsy-pixyu-gimbal.rst

Gremsy's S1 (aka S1V3) gimbal also supports MAVLink it seems in their latest release.  A user reported getting it working successfully and my contact at Gremsy as well confirmed that support has been added for MAVlink to this gimbal.
I've tested this on my local machine and it looks OK.

Common: Gremsy pages get S1 model added

---

dev/source/docs/SITL_simulation_parameters.rst
dev/source/docs/adding_simulated_devices.rst
dev/source/docs/using-sitl-for-ardupilot-testing.rst
planner/source/docs/mission-planner-simulation.rst

needs a careful read, extensively re-organized into evoking the sims by sim_vehicle or in Missionplanner, separating params that control the sim to a new page, and a page on how to add simulated devices
also update the Mission Planner SIM page with new command line options that are useful

Update SITL information

---

copter/source/docs/reference-frames-hexsoon-td650.rst

This adds @andyp1per's Hexsoon 650 build video to the corresponding reference vehicle page
I've tested this on my local machine and it seem fine.

Copter: add build video to hexsoon 650 reference page

---

dev/source/docs/sitl-with-gazebo.rst

Add missing 'a' in first sentence.

Minor grammar fix on Gazebo page

---

plane/source/docs/automatic-takeoff.rst

The code and the description of the parameter refer to `TKOFF_TDRAG_SPD1` as airspeed rather than ground speed.

plane: taildragger release speed is airspeed

---

common/source/docs/common-servo.rst

Digital servos support higher update rates using the SERVO_RATE parameter, but this is only a good idea if all the servos on a vehicle are digital

Update common-servo.rst for digital servos

---

rover/source/docs/reference-frames.rst

This reference frame is actively maintained as can be seen from [this discussion](https://discuss.ardupilot.org/t/maker-boat-advanced-build-info/73585).
I've tested this on my local machine and it seems fine.

Rover: link maker boat advanced from reference frames page

---

.github/workflows/test-Windows.yml
.github/workflows/test.yml

This is a future looking CI check. Not needed now, but will be helpful to catch error users might come across when building with newer python versions. Skipped python 3.9 for no specific reason.

Add python 3.10 to Github Actions CI

---

common/source/docs/common-vio-tracking-camera.rst

This comes from a report on my YouTube channel in which a user said their vehicle's telemetry stopped working after they turned on the RPI/T265.
I've also removed some old 4.0 instructions and clarified that the GPS can be left enabled if users wish to have it there.  Leaving it enabled means users may be able to skip setting the home location.
I have tested this on my local machine and it seems ok and no build errors.

Common: T265 setup recommends setting serialx_options

---

copter/source/docs/skyrocket.rst

Probably a good idea to warn people to watch out. I myself ordered this https://www.amazon.com/Sky-Viper-Journey-Streaming-Video/dp/B07G1RJNN9/ Nov 2022 and got a Journey SE. I am a/was new to ArudPilot. The wiki currently says nothing but the forum thread https://discuss.ardupilot.org/t/is-the-sky-viper-journey-se-copter-transmitter-pair-user-upgradeable-to-ardupilot/79275 is quite clear.
Even the comment from [Matt Morton](https://discuss.ardupilot.org/u/Matt_M) (https://discuss.ardupilot.org/t/is-the-sky-viper-journey-se-copter-transmitter-pair-user-upgradeable-to-ardupilot/79275/35) seems to confirm the direction of SkyRocket. Maybe even worth removing the company from https://ardupilot.org/ardupilot/docs/common-partners.html?

Sky Viper Journey SE is not supported

---

dev/source/docs/gsoc-ideas-list.rst

This project was successfully completed during last summer. Having this here is creating confusion among potential gsoc students. Many students have been repeatedly asking to take this project for GSoC 2023. Hence, we should remove it from here to avoid any further confusion.

Remove roverauto docking from GSOC ideas list

---

dev/source/docs/mavlink-camera.rst
dev/source/docs/mavlink-commands.rst

This adds a camera control page to our mavlink interfaces section of the developer wiki.
This has been lightly tested on my local machine and seems OK.
I'm working with some DavidA on some improvements to QGC's camera controls so it is useful to have this page as a reference and I hope to add to it as we expand the flight control code's abilities.

Dev: add mavlink interface camera controls

---

dev/source/docs/gsoc-ideas-list.rst

I had attempted to remove this in the last PR but missed one line.  I think this project is too much of a moonshot

Dev: update gsoc 2023 project list to remove AI item

---

dev/source/docs/gsoc-ideas-list.rst

I've discussed this removal with other mentors and checked the page looks ok on my local machine

Dev: gsoc projects list loses custom firmware server

---

common/source/docs/common-remoteid.rst

Add Cube ID and Cube ID_CAN to the list of "OpenDroneID Compatible devices"

Cube ID and Cube ID_CAN

---

common/source/docs/common-scripting-applets.rst
copter/source/docs/deadreckoning-failsafe.rst

lua script was moved from examples directory to applets directory.
Ideally this should be merged soon after this flight code PR goes in https://github.com/ArduPilot/ardupilot/pull/23233

Copter: deadreckoning link to lua script updated

---

common/source/docs/common-siyi-zr10-gimbal.rst

It does not support zoom at 4K resolution.
Here is the [A8 mini User Manual v1.2](https://drive.google.com/drive/folders/19Hs92ClHiRWIjE9xS32Y6GToXNvGveLO)
```
Record Resolution: Switch camera record resolution between HD (720p), Full HD (1080p),
2K, and 4K (under 4K recording resolution, A8 mini camera does not zoom).
```

Common: Add Siyi A8 warning

---

mavproxy/source/docs/getting_started/download_and_installation.rst

we don't want any new installations of Python2!

mavproxy: remove Python2 instructions

---

copter/source/docs/deadreckoning-failsafe.rst

This adds a new video to the Copter dead reckoning failsafe page.  I've tested this on my local machine and it looks OK.

Copter: add another dead reckoning failsafe video

---

common/source/docs/common-marvelmind.rst

Fix "... system can be **as a** short-range substitute..." to be "... system can be a short-range substitute..."

Fix typo on doc landing page

---

.github/workflows/test-Windows.yml
.github/workflows/test.yml
Sphinxsetup.sh
antennatracker/make.bat
ardupilot/make.bat
blimp/make.bat
common/source/docs/common-uavcan-gui.rst
common/source/docs/common-wiki-editing-setup.rst
copter/make.bat
dev/make.bat
dev/source/docs/apjtools-intro.rst
dev/source/docs/code-overview-adding-a-new-mavlink-message.rst
mavproxy/make.bat
plane/make.bat
planner/make.bat
planner2/make.bat
rover/make.bat
update.py
update.sh

This updates all the docs to use python3. There were a few tutorials which are super old and still use python2, so I didn't update them. 
I also removed the `python-is-python3`. That's a hack package IMO, let's just update the calls to `python3` and deprecate python2.

Use python3

---

common/source/docs/common-storm32-gimbal.rst

This removes a very old video I made of the SToRM32 gimbal.  It's not a bad video but its very out of date now especially considering all the recent code and mission command changes.
This has been tested locally.

Common: remove storm32 gimbal video

---

copter/source/docs/mission-command-list.rst

Based on current ` ModeAuto::loc_from_cmd()` behavior, a waypoint with location (0, 0) will simply be skipped rather than initiating a loiter.

Copter: Revise lat/lng 0, 0 waypoint behavior description

---

common/source/docs/common-viewpro-gimbal.rst

This corrects the links that users should use for the ViewPro gimbal driver lua script.  This is in response to [this beta testing discussion where a user couldn't get the gimbal working](https://discuss.ardupilot.org/t/viewpro-gimbal-setting-help/100173).
This has been tested locally and looks ok.

Common: viewpro driver links for 4.4 and 4.5

---

common/source/docs/common-brushless-pwm-gimbal.rst
common/source/docs/common-camera-gimbal.rst
common/source/docs/common-djirs2-gimbal.rst
common/source/docs/common-gremsy-pixyu-gimbal.rst
common/source/docs/common-mount-targeting.rst
common/source/docs/common-simplebgc-gimbal.rst
common/source/docs/common-siyi-zr10-gimbal.rst
common/source/docs/common-storm32-gimbal.rst

This adds links to each camera gimbal/mount page linking to the control overview page
I've also added a note regarding setting the RCx_TRIM value which came up as an issue on [this discussion](https://discuss.ardupilot.org/t/ip-cameras-rtsp-mavlink-support/99893/15).
This has been tested locally and looks ok.

Common: all mount setup pages get link to mount control overview

---

dev/source/docs/sitl-with-realflight.rst

It is necessary to set "Pause Sim When in Background" to "No" for RealFlight to work with Mission Planner. Otherwise, the simulation stops as soon as you switch to MP (to arm, to set parameters or anything else) and MP cannot communicate to FlightAxis.

sim: clarify a required setting in RealFlight

---

common/source/docs/common-siyi-zr10-gimbal.rst

This fixes two of the links on the Siyi camera/gimbal setup page.
This has been tested locally and looks fine.

Common: correct Siyi ZR10 links

---

dev/source/docs/adding_simulated_devices.rst
dev/source/docs/mavlink-commands.rst
dev/source/docs/mavlink-winch.rst

This adds a new MAVLink interface page for the winch to clarify to developers how a winch can be controlled using MAVLink commands.
This also adds a section to the SITL simulated devices page to describe how to setup a simulated winch.
This has been tested on my local machine and looks OK.  This PR is in response to [this discussion](https://discuss.ardupilot.org/t/do-winch-mission-waypoints-not-working-with-daiwa-winch/98946) where a developer struggled to figure out the mavlink commands to control a real winch.

Dev: add winch SITL setup and mavlink interface controls page

---

dev/source/docs/using-DFU-to-load-bootloader.rst

dfu-util is available for most platforms, not only Linux.
The "with some versions of dfu-util you may need this instead" is nonsense, also because -s and --dfuse-address is the same option.

Update dfu-util instructions

---

common/source/docs/common-siyi-zr10-gimbal.rst

This fixes the camera setup parameter instructions to clarify that it depends upon the AP version used.
- 4.3 (and earlier) uses CAM_TRIGG_TYPE
- 4.4 (and later) use CAM1_TYPE
This PR is in response to [this discussion](https://discuss.ardupilot.org/t/zr10-2k-qhd-30x-hybrid-zoom-gimbal-camera-siyis-first-industry-gimbal-camera-and-it-wont-be-the-last/86069/404) where a user couldn't get the ZR10 camera controls to work.
This has been tested locally and seems OK.

Common: fix siyi cam param instructions

---

dev/source/docs/style-guide.rst

Recommend enum classes since they are commonly used. Provide a style recommendation for them. 
https://github.com/ArduPilot/ardupilot/pull/23877
https://github.com/ArduPilot/ardupilot/pull/23830
https://github.com/ArduPilot/ardupilot/pull/23768/files#diff-ed061f26ab421c524f35bb9112b56bc1322892589f95b77e9497345eb48eafbe
https://github.com/ArduPilot/ardupilot/pull/23119/files#diff-a98f7c976f44f4a82c8c4882b638ca053d70a95f603861216630e20243689dd2
I did not cover the aspect of using `#DEFINE` to enable/disable enums, and to be sure to pin all the numbers so they don't change value when you change your build options. Seems too advanced for the style guide.

Add style for enums and prefer enum classes

---

common/source/docs/common-siyi-zr10-gimbal.rst

Fix siyi setup instructions to specify yaw min/max to +-135 deg which matches the datasheet.
This has been tested local and seems ok.

Common: Siyi ZR10 yaw angle min/max fix

---

common/source/docs/common-efi.rst
common/source/docs/common-velocity-can-escs.rst

* Velocity ESC setup guide was missing some ESC configuration details. Adds details for PiccoloCAN and DroneCAN configuration.
* EFI guide was missing details on how to only receive telemetry, and not also send throttle commands.
Resolves: https://github.com/ArduPilot/ardupilot_wiki/issues/5104

Common: Update Currawong Velocity ESC setup guide

---

common/source/docs/common-thecubeorange-overview.rst

Looking at the schematics, it might be that the I2C port numbers for GPS1 and GPS2 are reversed https://github.com/proficnc/The-Cube/blob/master/CB_REV_C_Altium/PCB%203D%20Print%20from%20Above.PDF
It is possible the schematic is wrong, but this does align with the cube docs I am working off: https://docs.cubepilot.org/user-guides/autopilot/the-cube-module-overview

cube overview - I2C2 port might be wrong

---

dev/source/docs/building-setup-mac.rst

brew tap ardupilot/homebrew-px4 is out of date. homebrew-cask and homebrew-core now seem to have the correct versions of gcc and other relevant tools.

Update building-setup-mac.rst removing tap ardupilot/homebrew-px4

---

common/source/docs/common-telemetry-rockblock.rst

To prevent user confusion, I've added a note recommending users to use MAVProxy instead of MP or QGC with RockBLOCK telemetry.
@rmackay9

Common: Add warning about QGC and MP with RockBLOCK

---

common/source/docs/common-autopilots.rst

I updated the menu level so that when "Choosing an Autopilot" is clicked, it does not require another click to see the categories. I also reorganized the intro of the page accordingly.

updated autopilot menu order and page intro

---

common/source/docs/common-gremsy-pixyu-gimbal.rst
common/source/docs/common-siyi-zr10-gimbal.rst
dev/source/docs/mavlink-camera.rst
dev/source/docs/mavlink-gimbal-mount.rst

This PR includes camera and gimbal related updates for both the developer and user wikis.
The developer wiki gets details on new commands supported in AP-4.5.0
The user wiki gets warnings and fixes for the Siyi and Gremsy gimbals.
This has been tested locally and seems OK.

Dev/Common: camera and gimbal updates

---

mavproxy/source/docs/getting_started/starting.rst

--option renders as -option
-\\-option renders as -\-option
-\-option renders as --option
Switch from -\\-option to -\-option

mavproxy: fix startup option dashes

---

common/source/docs/common-viewpro-gimbal.rst

This adds a little section to the bottom of the ViewPro page with instructions on how images and videos can be downloaded from the gimbal over ethernet.  Eventually I'd like to add this info for all our cameras but so far this is the only one that I have confirmed can do it.
I have tested this on my local machine and it looks OK.

Common: viewpro gets image and video download instructions

---

common/source/docs/common-flir-vue-pro.rst

This PR adds a warning to the Flir Vue Pro camera setup page.  I've also adding a missing setting and removed a very old setting (the "CH8_OPT" part).
I've recently re-tested the setup and found that the MAVLink interface has somehow been broken and I strongly suspect it is due to some change on the FLIR firmware side.  [There is a discussion here](https://discuss.ardupilot.org/t/flir-vue-pro-gets-no-mavlink-info/96072) where other users are also apparently struggling.

Common: Flir vue page gets warning

---

dev/source/docs/ros.rst
dev/source/docs/ros2-gazebo.rst

I plan on adding a quick youtube video showing the gazebo world with a copter in it, it would be nice to have that before merge. 
After this PR I will add a SLAM related page to the wiki.
The technical details have been heavily based on the `ardupilot_gz` README from @srmainwaring, and is linked in the page

dev: Add ROS 2 page for Gazebo integration

---

dev/source/docs/mavlink-camera.rst

This adds details on the mavlink command to control absolute zoom.
I've added some more details about which versions support which commands but this shouldn't block this from being merged because this is all in the developer wiki and developers often develop against "latest".

Dev: mavlink camera page gets absoluite zoom info

---

dev/source/docs/sitl-serial-mapping.rst

There are still links floating out there to the old page. Redirect to the newer info and the consolidated page.

Dev: Add link to newer SITL serial info

---

.gitignore

I followed the instructions for [Setup in Windows](https://ardupilot.org/dev/docs/common-wiki-editing-setup.html#setup-in-windows) to build the wiki and noticed some files were created that seem unversioned on purpose.
I'm least certain about `build_options.py`. But as I understand it, it's also relevant to specific board configuration so it's in the same section.
_(Contribution on behalf of @FlyfocusUAV)_

Update gitignore with files downloaded during build

---

common/source/docs/common-marvelmind.rst

This slightly updates the marvelmind page to bring the EKF parameters up-to-date.
I've also removed references to very old versions of AP.
I do not have a marvel mind to test with but I've had a quick look at the driver and I think this should be correct.
FYI @karthikdesai.  I know this was a long time ago but at least FYI.

common: marvelmind parameter update

---

dev/source/docs/ros.rst
dev/source/docs/ros2-cartographer-slam.rst

Continuation of #5359.
The technical details have been heavily based on the  `ardupilot_ros` README, which is linked in the page
@Hwurzburg could you upload the video to Ardupilot's youtube channel ?

add ros2-cartographer-slam page

---

dev/source/docs/ros2-gazebo.rst

Originally, users weren't told how to install gazebo and had to google it. There's tons of ways, and a lot of stack overflow is not ideal.

Add missing installation instructions for gazebo garden

---

common/source/docs/common-holybro-pixhawk6X.rst

Add BATT_I2C_ADDR detail to Pixhawk 6X with INA228 & INA238 Power Module.

Add BATT_I2C_ADDR detail to Pixhawk 6X

---

dev/source/docs/ros2.rst

The rosdep command tried to install a binary package for `ardupilot_sitl` instead of using the package in the worskpace source directory.
Adding the flag `-i`, makes it so that rosdep doesn't try to install binaries for packages that are already in the workspace. It is present in the other pages for `ROS2`, but I missed it on this one.
It fixes the issue:

dev: fix rosdep in ros 2 page

---

copter/source/docs/ac_throttlemid.rst

Very high-powered copters have a hover throttle lower than 0.2, so I've updated it to say "usually" instead of stating it as a requirement, which may make users think something is wrong if their hover throttle is that low.
I've also changed the max of 0.8 to 0.6 since the code limits the maximum hover throttle to 0.6875

Update ac_throttlemid.rst to take into account lower hover throttles and the max hover throttle hard limit in the code.

---

mavproxy/source/docs/modules/graph.rst

There was whitespace causing the `tickresolution` line to be included in the code block above it.

modules: graph: remove whitespace to fix code blocks

---

common/source/docs/common-cameras-and-gimbals.rst
common/source/docs/common-xacti-gimbal.rst

This PR makes three changes:
1. Add a link to the Xacti page from the cameras-and-gimbals landing page.  I know this may be slightly controversial because we normally leave new features in the "Upcoming Features" area until we start beta testing the next version but I think that it would be good to have more visibility on this series of cameras.  I think these cameras could be quite popular because although slightly expensive they are high quality and very small.  I'm sure it will take time for the number of users to ramp up and I would like to get that process started as quickly as possible.
2. Add note on which models are supported
3. Add firmware update process instructions

Common: link Xacti page from cameras-and-gimbals landing page

---

plane/source/docs/quadplane-parameters.rst

It seems that 400 should be the recommended SCHED_LOOP_RATE fora aquaplane. If anyone knows more about this please add details.

Update quadplane-parameters.rst SCHED_LOOP_RATE

---

plane/source/docs/quadplane-parameters.rst

@timtuxworth maybe this will help someone setting up a Qplane....at least you wont get surprise behavior... maybe not "tuned" for distances and alts, but at least the functions are consciously being chosen

add quick setup guide for return to home behaviours

---

common/source/docs/common-uavcan-peripherals.rst
common/source/docs/common-xacti-gimbal.rst

This PR adds these Xacti related improvements
- links to where users can purchase compatible connectors and wires
- camera shutter minimum interval parameter setting
- link from the Xacti page to the Camera Controls page
- link to the Xacti page from the DroneCAN peripherals landing page
This has been tested locally and looks good to me.

Common: Xacti camera gimbal page gets links to compatible connector and wires

---

common/source/docs/common-install-sdcard.rst
common/source/docs/common-loading-firmware-onto-pixhawk.rst

Please note that https://github.com/ArduPilot/ardupilot/pull/25143 is required for the "bootloader works in latest versions" thing to actually be true!  It should be merged before this PR is!
This work sponsored by Kraus Hamdani

common: add instructions on how to flash-from-sdcard

---

dev/source/docs/apmcopter-programming-libraries.rst

This is a PR for removing AP_Buffer description and links, as it's no longer exist!

apmcopter-libraries: Remove AP_Buffer

---

dev/source/docs/setting-up-sitl-using-vagrant.rst

Seems like the Vagrant instructions are also a bit out of date?
In which case, it's probably best to add this warning to this one as well, like the Cygwin etc pages have.

Recommend WSL instead of Vagrant

---

common/source/docs/common-esp8266-telemetry.rst

The doc page should probably point to the repo in the ArduPilot organisation rather than @tridge's one.
IIUC, this is also the one that gets built for the binaries in the firmware server.

ESP8266 telemetry: change link to ArduPilot's repo rather than Tridge's

---

common/source/docs/common-external-ahrs.rst

ArduPilot software does not currently configure the MicroStrain External AHRS, yet the Wiki never told users that. Adding a link to Sensor Connect is a good way to let users know they should go configure.

Recommend Sensor Connect for configuration

---

dev/source/docs/ros2-gazebo.rst
dev/source/docs/ros2-sitl.rst
dev/source/docs/ros2.rst

This improves instructions to make sure users don't miss steps for SITL.
It also improves the build workflow by only building what's needed, instead of everything, which is good when someone's ROS workspace is huge. 
This work was sponsored by AeroVironment.

Add missing sitl setup and packages up to

---

dev/source/docs/ros2.rst

Users are trying to use deprecated ROS versions with ArduPilot. These are not supported.

Be explicit that humble is the ONLY supported version right now

---

update.py

too much whitespace on the rename line means if the file doesn't already exist we don't replace it

update.py: correct fetch-parameter-file logic

---

rover/source/docs/additional-information.rst
rover/source/docs/reference-frames-boogieboard-boat.rst

Also added a link to the reference frames landing page from the Additional-information landing page.
Tested locally and looks ok to me.

Rover: boogie board reference frame gets GPS

---

dev/source/docs/the-ardupilot-autotest-framework.rst

In rst, code blocks need double backtick or :code:`example`

Fix inline-code in `the-ardupilot-autotest-framework.rst`

---

common/source/docs/common-aocoda-h743dual.rst

Correct on-board flash size 128MB for aocoda-h743dual

Correct on-board flash size 128MB for aocoda-h743dual

---

plane/source/docs/flight-modes.rst

This suggests that Cruise does terrain following out of the box, and that FBWB cannot do terrain following. Both of which are wrong.

flight-modes.rst: remove mention of terrain following for Cruise

---

dev/source/docs/using-sitl-for-ardupilot-testing.rst

Coming out of https://github.com/ArduPilot/ardupilot/issues/20161#issuecomment-1842083930
The dev team put their heads together and we found the right commands to do it.

Add SITL swarming guide

---

dev/source/docs/ros2-cartographer-slam.rst
dev/source/docs/ros2-gazebo.rst
dev/source/docs/ros2-sitl.rst
dev/source/docs/ros2.rst

* Consistent rosdep instructions
* Add next steps to make order clearer
* Put MavProxy in the SITL tutorial
* Remove specifyinig rosdistro in rosdep call, use the environment variable instead
* Rely on colcon enabling testing by default
* Fix invalid link rendering
* Fix incorrect capitilization of tools

Improve ROS2 docs

---

common/source/docs/common-auxiliary-functions.rst

This is a format change that should still allow for easy editting and addition of new switch options. This should also keep the table to a reasonable width on the page.
I haven't had a chance to build yet. Haven't finished settting up on this new machine.

Common: Update aux switch table to be an RST simple table

---

dev/source/docs/mavlink-requesting-data.rst

... used for ignoring streamrate sets from a GCS
... bit of a run-on sentence, sorry!

dev: mavlink-requesting-data: add note about SERIALn_OPTION bit 12

---

common/source/docs/common-auxiliary-functions.rst

tedious reformat to eventually not require a horizontal slider on option description table on normal PC displays
as time permits will do more chunks

Partial table reformat to remove horz slider

---

common/source/docs/common-imu-batchsampling.rst

Peter Hall pointed out that raw IMU logging can be used on H7 processors and might be more useful.

Update guidance on IMU logging

---

common/source/docs/common-power-module-configuration-in-mission-planner.rst

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_BattMonitor/AP_BattMonitor_Sum.cpp#L63
The code skips lower instances and only sums higher instances.
This tripped up a Partner and they were getting "Battery unhealthy" pre-arm

Fix BATT3_SUM_MASK documentation

---

common/source/docs/common-prearm-safety-checks.rst

This adds a table of pre-arm checks that may be displayed to users along with a "Cause" and "Solution".
This covers pretty much all non-vehicle specfic arming checks and Copter specific checks.  I.e. Plane, Sub and Blimp specific checks are not yet covered.
I've tested this locally now and it looks OK to me.
@Hwurzburg maybe we could merge this after you move a few of the most common items to the top?  I might move a few up in a future PR.
It's hard to say if this massive table will be useful for not but I hope that if it is complete and provides enough detail for each failure that it will slightly reduce the number of support calls or at least give us a page to point newbies at when they ask what a failure message means.

common: update prearm check explanations

---

common/source/docs/common-gps-septentrio.rst

PR https://github.com/ArduPilot/ardupilot/pull/25601 adds support for GPS-for-yaw when using a single Septentrio GPS with two antennas.  This is new for 4.5.
This has been tested locally and looks OK to me.

Common: Septentrio page details dual antenna setup

---

common/source/docs/common-auxiliary-functions.rst

I thought that these were automatically generated but perhaps not.

Common: add camera and mount aux functions

---

common/source/docs/common-raw-imu-logging.rst

This includes some slight re-wording and more importantly fixes broken links on the [Raw IMU Logging for FFT analysis page](https://ardupilot.org/copter/docs/common-raw-imu-logging.html).
As a side note, I think our notch filter setup wiki pages are overly complex and are in the wrong part of the wiki.  They're under logging but I think they should be in the Tuning or Advanced Configuration sections of the wiki.
FYI @andyp1per

Common: fixup links and wording on raw-imu-logging

---

dev/source/docs/sitl-with-realflight.rst

In addition to the 'Configure RealFlight' section, there was a separate section for enabling RealFlight Link, however the instruction for RealFlight 8/9 was incorrect, and the instruction for RealFlight Evolution was repeated in the following section.
This change keeps only the 'Configure RealFlight' section, adding in the instruction for Link in RealFlight 8/9, and moving the restart instruction to the end of the bullet point list.

fixed and clarified RealFlight configuration instruction

---

copter/source/docs/reference-frames-hexsoon-td650.rst

This flight code PR changed the hexsoon edu650 parameter file name so this PR fixes the link in the wiki.
This has been tested locally and looks ok.

Common: fix hexsoon-edu650 param link

---

dev/source/docs/raspberry-pi-via-mavlink.rst

change `see see the the` to `see the`
Link: https://ardupilot.org/dev/docs/raspberry-pi-via-mavlink.html#mavproxy

Fix typo in the raspberry-pi-via-mavlink - MAVProxy subsection

---

plane/source/docs/guide-tilt-rotor.rst

Bicopter tilt type was introduced in https://github.com/ArduPilot/ardupilot/pull/10793 but the frame type required is not listed here.
Should probably include bicopter frame type here since it's used in the bicopter tilt type

Add bicopter frame type

---

plane/source/docs/quadplane-tips.rst

The existing wording regarding X vs H motor mixing for quadplanes recommend H mixing for all geometries. While it correctly outlines the effects of induced airframe twist on yaw performance for quadplanes with X mixing and fuselage-mounted motors, it omits that this effect would also occur when using H mixing with wing-mounted motors. 
This edit clarifies which geometries of quadplanes should use X or H mixing to avoid the effects of harmful airframe twist.

Clarify X vs. H frame type selection for quadplanes

---

common/source/docs/common-gps-for-yaw.rst
common/source/docs/common-gps-septentrio.rst
common/source/docs/common-positioning-landing-page.rst

This fixes an incorrect statement in the Septentrio documentation about the requirement of an RTK fix for dual-antenna heading (tested and RTK fix is not required). This also adds some information about the `GPS_RATE_MS` and `GPS_RATE_MS2` parameters which currently aren't used by the SBF driver, but are still required for correct position calculation. Some typos and unclear documentation were also fixed.

update some gps-for-yaw and Septentrio information

---

plane/source/docs/fly-by-wire-low-altitude-limit.rst

Fix warning that is no longer correct since parameter rework in 4.5.0 CRUISE_ALT_FLOOR is now in meters.

Update warning for centimeters on fly-by-wire-low-altitude-limit.rst

---

dev/source/docs/ros2-gazebo.rst
dev/source/docs/ros2.rst

Simplify clone by not needing to create `src` directory, and rely on `vcs` to clone from URL automatically.

Simplify clone by using URL method

---

common/source/docs/common-modalai-voxl.rst
dev/source/docs/adding_simulated_devices.rst

This updates the ModalAI wiki page to include changes in PR https://github.com/ArduPilot/ardupilot/pull/26277 which is included in Copter-4.5.0-beta3.  The changes include:
- explanation of the VISO_QUAL_MIN parameter
- link to a new Lua applet that automatically switches to optical flow + rangefinder if the ModalAI fails
I've also included a bit of a drive-by change to the developer wiki to remove some references to EKF2.  EKF3 has been the default for quite some time now so I don't think we need to mention EKF2 anymore.
I've tested these changes locally and they look OK to me.

Common: ModalAI VOXL page gets links to optflow+rangefinder transition applet

---

common/source/docs/common-modalai-voxl.rst

This adds a workaround to an obscure issue with the ModalAI camera's processing of the [SYSTEM_TIME message](https://mavlink.io/en/messages/common.html#SYSTEM_TIME).
It seems that the camera loses its position estimate after about a minute if sent a stream of SYSTEM_TIME messages where the "time_unix_usec" field is zero but the "time_boot_ms" field is non-zero.  The easiest workaround for now is to ensure that the SRx_EXTRA3 parameter is set to zero so the message is not sent to the camera at all.
I've also reported this to ModalAI and hopefully they can figure out the cause.

Common: modalai gets optional SR2_EXTRA3 setting

---

dev/source/docs/support_proxy_supportengineer.rst

The signing key in DroneCAN GUI refers to the password to generate the key.

Dev: Update Support Engineer DroneCAN GUI Notes

---

dev/source/docs/mavlink-camera.rst

This adds mavlink interface info for the new SET_CAMERA_SOURCE mavlink command
This shouldn't be merged until this PR is merged https://github.com/ArduPilot/ardupilot/pull/26172

dev: mavlink interface for set-camera-source

---

common/source/docs/common-rtf.rst

This updates our [RTF page](https://ardupilot.org/rover/docs/common-rtf.html) with the following changes:
- SkyRocket Journey moved to Non-partner vehicles area
- BlueRobitcs BlueBoat is added
- Swan-K1 gets "Holybro" at the beginning to clarify the company
- Removed AION R1 which is no longer available
This has been tested locally and looks OK to me.
FYI @rishabsingh3003

Common: RTF page update

---

common/source/docs/common-serial-led-neopixel.rst

This includes two changes:
1. fix a broken link for a parameter
2. mention the NTF_LED_LEN parameter must be set if multiple NeoPixel LEDs are attached
3. re-organise the wording so that the parameter changes appear in a list instead of all in a single paragraph.  I think this makes it easier to read
Maybe @andyp1per should review this because I think he knows more about these LEDs than I do.  I've actually never used them before today.

Common: Neopixel rewording and add NTF_LED_LEN explanation

---

common/source/docs/common-ads-b-receiver.rst

ADS-B Extlinks: Fixed links and removed dead link uav-store.de. 
Small fixes to other stores and removed dead uav-store.de. Domain killed.

ADS-B Extlinks: Fixed links and removed dead link uav-store.de

---

common/source/docs/common-ekf-sources.rst
common/source/docs/common-understanding-altitude.rst
copter/source/docs/additional-information.rst
copter/source/docs/terrain-following-manual-modes.rst
copter/source/docs/terrain-following.rst

This makes a few changes to our EKF source switching page in response to [this support thread](https://discuss.ardupilot.org/t/arkflow-and-z-drop/115549) in which a user ended up changing the EKF_SRC1_POSZ to RangeFinder which is pretty much never a good idea.
I've also included a couple of drive-by changes:
- updated a warning on the Surface Tracking and Terrain Following pages to remove the old EKF2 info and clarify the EKF3 source set parameter involved
- added a link to Surface Tracking from the "Understanding altitudes" page
- added a link to reference frames from the "Additional Info" page to make Copter match Rover
I've tested these locally and they look OK to me.

Common: update EKF source switching to include POSZ explanation

---

common/source/docs/common-hereflow.rst

We discovered soon after the 4.5.0 release that some users found the HereFlow sensor was not working with some autopilots and the workaround was to slow the board's boot up time.  This PR adds this advice to the HereFlow wiki page even though it will soon be resolved for at least some boards.
This has been tested locally and looks OK to me.

Common: hereflow gets brd-boot-delay setting

---

common/source/docs/common-advanced-configuration.rst
common/source/docs/common-oa-dijkstras.rst
copter/source/docs/ac2_guidedmode.rst

This PR improves the Copter Guided mode GUID_OPTIONS parameter explanation.
This is in response to [this Copter 4.5 support issue](https://discuss.ardupilot.org/t/drone-not-avoiding-obstacles/116293) in which the user was attempting to get BendyRuler working in Guided mode.  It turns out that one of the GUID_OPTIONS bits needs to be set for this to work.
Some other changes are also included:
- Guide mode links changed to the telemetry landing page instead of the SiK radio.
- Guided mode link fixed for GUID_TIMEOUT
- Dijkstra's loses mention of ver 4.0
- Dijkstra's mentions the GUID_OPTIONS parameter setting (for Copter)
- Weathervaning is added to the Advanced Configuration landing page.  It's only in the Flight Features at the moment but the Advanced Configuration page is where we should …

Copter: improve GUID_OPTIONS parameter explanation

---

dev/source/docs/ros2.rst

We've had a ton of users have problems building because they skip steps in the Wiki. 
This command will increase verbosity of logs, which makes it easier to troubleshoot.
Users knew to both ROS 2 and ArduPilot are likely not familiar with colcon.
Upstream: https://github.com/ArduPilot/ardupilot_gz/issues/50#issuecomment-2065892858

Add steps for verbose build logs

---

common/source/docs/common-external-ahrs.rst

Here's the wiki to accompany the release of GQ7 support; this lets users know how to configure the data rates.
I tested these on a 3DM-QG7 with what's merged to `master`.
In a future release of ArduPilot, these may be configured automatically by the driver.
Here's the duty usage on the serial line. 4.19mS at minimum between packet groups, with 230k baud rate.

Microstrain7 data rates

---

dev/source/docs/companion-computers.rst

Original link was specified before the base landing page existed, and is also now outdated from to the latest stable version.

dev: source: docs: companion-computers: update BlueOS landing page

---

common/source/docs/common-gremsy-pixyu-gimbal.rst

It seems like the ZIO cannot be used as a 2nd gimbal at least according to testing on [this 4.5 support thread](https://discuss.ardupilot.org/t/gremsy-zio-does-not-work-if-set-to-mount-2/116127).
I've informed Gremsy as well.

Common: gremsy gets new ZIO warning

---

copter/source/docs/auto-mode.rst

I think this may be enough info to help people figure out why the defaults for speed and radius , and intervening DO cmds seem to give a non-Scurving path

add info on scurve behavior

---

common/source/docs/common-cuav-pwlink.rst

Document the address and mavproxy command for the CUAV PW-LINK.
In theory, this should work, but it fails to connect. Perhaps something else is up.

Common: Document CUAV PW-LINK IP Address for MAVProxy usage

---

common/source/docs/common-gps-trimble-px1.rst

the parameter changes were all appearing on one line so this fixes this.
This has been tested locally and looks OK.

Common: minor fix to trimble page formatting

---

common/source/docs/common-radio-control-calibration.rst

When my brother set up a quad, he missed this. Let's make it clearer. ArduPilot has its quirks, this is one of the first a new user hits. They might crash into themselves if they stand directly behind the vehicle on intial takeoff if pitch is reversed on copter.
* https://discuss.ardupilot.org/t/opinion-on-reversed-pitch/96749/2
* https://discuss.ardupilot.org/t/parameters-missing-from-firmware-pitch-reversed-copter-3-5-rc4/16491
* https://discuss.ardupilot.org/t/reversed-pitch-yaw-roll/115658/8?u=rfriedman
The fact the devs keep having to remind users this indicates it's not clear enough, and it's not intuitive.

Common: Make it clearer that you reverse pitch

---

dev/source/docs/ros.rst
dev/source/docs/ros2-over-ethernet.rst
dev/source/index.rst

Before and After:
I want to also recommend using ROS 2. Note the ethernet changes were because it wasn't representing in the TOC correctly. Incorrect headings were used.

Dev: ROS: Split into ROS 1 and ROS 2 docs

---

dev/source/docs/debugging-with-gdb-using-vscode.rst

This automatically adds a breakpoint at AP_HAL::panic() when debugging
I normally debug ArduPilot through vscode like this without the extra step of using `sim_vehicle.py`. Recently, I had a panic in SITL that I can't reproduce and couldn't debug at the time because I hadn't enabled this breakpoint in my setup. I came up with this addition for my personal `launch.json` and figured it would be useful for others.
I tested by triggering a panic with the appropriate mav command, and this does indeed cause gdb to break there now.

Dev: update VSCode launch.json gdb args

---

dev/source/docs/ardupilot-discord-server.rst

When the timezone known by Google-maps, its shows in localtime. When the timezone is not known by Google-maps, it shows in GMT, and displays a small notice at the bottom. At first I thought it was Brave and Tor that weren't sending the timezone for privacy/tracking concerns, but even Chrome support is inconsistent.
Working Browsers:
Debian 12, Firefox 115.5.0esr (64-bit)
Android 13: Chrome 121.0.6167.143
Android 13, Firefox 122.0.1
Fallback to GMT(displayed at the bottom of page):
Debian 12, Chome Version 119.0.6045.159 (Official Build) (64-bit) Android 13, Brave 1.62.156 based on Chromium 121.0.6167.139 Android 13, TorBrowser 115.2.1-release(13.0.9)

Remove comment about Google-maps timezone.

---

common/source/docs/common-lua-scripts.rst

When adding a method to lua bindings you have to update docs.lua manually

Update common-lua-scripts.rst to include docs.lua

---

common/source/docs/common-rplidar-a2.rst

This fixes the links on the RPLidar page.  when I look at them at least using firefox the 2nd one is broken.  This seems to fix it.

Common: fix rplidar links

---

common/source/docs/common-aocoda-h743dual.rst

[26812 Aocoda-RC H743Dual motor 5-8 mis-labeled issue](https://github.com/ArduPilot/ardupilot_wiki/issues/5759)

Fix Aocoda-RC H743Dual motor 5-8 mis-labeled issue 26812

---

common/source/docs/common-aocoda-h743dual.rst

Reverts ArduPilot/ardupilot_wiki#6010
my mistake for merging this...I already had a 4.6 wiki pending PR which fixes another error on the page #5896 which wont be merged until 4.6 beta when the code is released

Revert "Fix Aocoda-RC H743Dual motor 5-8 mis-labeled issue 26812"

---

common/source/docs/common-lua-scripts.rst

Noticed that I need to change a setting in VS Code to make it use the definitions.
*(Contribution on behalf of @FlyfocusUAV)*

Common: Add editor configuration to get definitions

---

common/source/docs/common-rplidar-a2.rst

Other variants of RPLiDAR A2 like M7 or M8 supports 115200 baud but M12 variant supports 256000 baud rate.

Common: Update baud rate for M12 variant of RPLiDAR A2

---

common/source/docs/common-herelink.rst
common/source/docs/common-optional-hardware.rst

We've released QGC-4.4 including a new herelink.apk file so I've added update instructions for users.
P.S. I also included a drive-by fix for the periphals landing page

Common: update Herelink with QGC upgrade procedure

---

common/source/docs/common-3d-mapping.rst
common/source/docs/common-apm-to-chdk-camera-link-tutorial.rst
common/source/docs/common-archived-topics.rst
common/source/docs/common-camera-shutter-with-servo.rst
common/source/docs/common-cameras-and-gimbals.rst
common/source/docs/common-chdk-camera-control-tutorial.rst
common/source/docs/common-pixhawk-camera-trigger-setup.rst

This simplifies/clarifies the camera setup when using servo or relays.
I've removed a picture and perhaps that means we could remove the pic from the images directory as well, but sometimes we use images across pages.
I've tested it locally and it looks OK to me.

Common: simplify camera servo and camera relay setup instructions

---

common/source/docs/common-xacti-gimbal.rst

This adds instructions for how a companion computer can download images and videos from a Xacti camera gimbal
I've tested this locally and it seems OK to me

Common: xacti gets remote download instructions

---

common/source/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.rst

The logs represent raw magnetic field data with calibration parameters applied, not raw magnetometer values without calibration. Updated the description for clarity. (took me 2 days to figure it out)

Update COMPASS description to clarify logs as raw mag field

---

dev/source/docs/sitl-with-gazebo.rst

This includes a few changes that I've separated into different commits so that we can easily drop those that aren't acceptable to @khancyr and @srmainwaring:
1. most importantly the dependencies are updated
2. added a reference to the ardupilot_gazebo plugin's README which had the correct instructions
The next two i feel less strongly about but I thought they were improvements
3. changed the tip at the top to regular text
4. changed the recommended ardupilot_gazebo path be in the home directory which matches the [README](https://github.com/ArduPilot/ardupilot_gazebo/blob/main/README.md)

Dev: gazebo installation update

---

common/source/docs/common-SDMODELH7V2.rst

Broken link appears on this page: https://ardupilot.org/copter/docs/common-SDMODELH7V2.html

common: correct link to SDModel's we store

---

dev/source/docs/building-setup-windows-cygwin.rst

I wanted to build the latest ArduCopter by setting up CYGWIN.
However, I detected an error in dronecan_dsdlc.py.
My CYGWIN's EMPY was V4.1.
I was able to resolve the issue as follows.
I will fix the WIKI.
https://discuss.ardupilot.org/t/failed-to-build-an-old-commit-of-master-branch-15601e4-and-cannot-install-the-missing-module/112556

Cygwin: Resolve the error in dronecan_dsdlc.py

---

dev/source/docs/ros.rst
dev/source/docs/ros2-waypoint-goal-interface.rst

This PR creates a wiki for Goal Waypoint interface as described in this [PR](https://github.com/ArduPilot/ardupilot/pull/25722/) by @Ryanf55. This page describes the steps only for Plane. 
For copter, the following [PR](https://github.com/ArduPilot/ardupilot/pull/26911) is pending which contains a [test script for Copter](https://github.com/ArduPilot/ardupilot/pull/26911/files#diff-c4ceed85ee9e5debff72af479f156432940032c6b03946a5466162740ab70c1b) as well. As soon as it is also merged, I'll add steps for that too.

Dev: Added waypoint goal interface wiki

---

dev/source/docs/adding_simulated_devices.rst

Changed RPM_TYPE from 1 to 10 for normal SITL as 1 does not work. Added RPM2_TYPE which needs to be used when running flightaxis link for RealFlight

Updated the instructions for adding a simulated RPM sensor

---

copter/source/docs/traditional-helicopter-tailrotor-setup.rst

Default veules for H_DDFP_SPIN_MIN/MAX were mixed up. According to parameters doc the default for min is 0.15, default for max is 0.95

Traditional-helicopter-tailrotor-setup_corrected_default_params

---

copter/source/docs/mission-command-list.rst

This adds a note/warning about do-commands following a takeoff command.
This is created as as result of this support issue https://discuss.ardupilot.org/t/copter-4-2-x-cant-accept-do-change-speed-in-auto-mission/87509/65

Copter: warning about do commands being skipped

---

common/source/docs/common-smart-battery-landingpage.rst

It looks like this is a hangover from a while back.  The limitation that enforced smart batteries to have an address of 0x0B was removed when the address parameter was added in this PR: https://github.com/ArduPilot/ardupilot/pull/17820
Had a report of it confusing a user about to write their own smart battery driver.  Hence removing.

smart-battery-landingpage: Remove limitation

---

common/source/docs/common-rpm.rst

Two minor fixups to RPM:
- Correct param value for GPIO pin RPM type.  This was a mistake noticed by a partner.
- Add clarity to the RPM scaler calculation for eRPM.  I added the example originally, but I want to add some clarity that illustrates the difference between number of poles and pole-pairs.

common-rpm: fix GPIO pin number and clarify motor scaler calculation

---

dev/source/docs/events.rst

This adds a link to the 2024 developer conference blog post from the Events page
FYI @Ryanf55

Dev: events gets Conf 2024

---

dev/source/docs/ros2-sitl.rst
dev/source/docs/ros2.rst

* Skip duplicate installation of MicroXRCEGen
* Add context to why we can't call waf directly
* Split long lines up
I would like to change the `ros2 launch` command on the `ros2-sitl` page to have one instruction for `4.5` and one for everything later. Is there a common way that we communicate differences across versions in the wiki that would be best?

dev: Improve first time setup

---

copter/source/docs/traditional-helicopter-first-flight-tests.rst

Based on user feedback, updating the hover trim section to make it clearer for leveling the IMU using MP or QGC.  Pulled out some information that made it confusing and was unnecessary.

Tradheli-provide clarification on setting level when calibrating

---

common/source/docs/common-external-ahrs-vectornav.rst
common/source/docs/common-external-ahrs.rst

The VectorNav documentation is currently out of date, as the driver currently supports all VectorNav sensors (outside of VN-100 and VN-300).
It also should be its own page to provide more space to discuss setup.
Suggested outline:
About VectorNav
Where to buy
Hardware Setup
Firmware Configuration
1. Use sensors as inputs to ArduPilot internal filters. Configured via EAHRS_SENSORS bitmask
- No additional necessary changes. Highly recommended to raise EAHRS_RATE to 400 or 800 Hz (which requires raising baudrate to 921600) so that AP EKF has enough data
3. Use VectorNav solution. Currently only avialable on GNSS-enabled products (not vn-100 or vn-110)
- Additionally requires changing AHRS_EKF_TYPE to 11
Note: Configuration/connection of VN takes place at bootup, so must reboot AP after any …

Update VectorNav Documentation

---

common/source/docs/common-ek3-affinity-lane-switching.rst

Some FCs, such as Cube Orange Plus, have multiple barometric pressure sensors.
Please clarify the relationship between the barometric pressure sensor instances and lanes.

EKF3: Lane change of barometric pressure sensor

---

Sphinxsetup.bat
Sphinxsetup.sh
common_conf.py
dev/source/docs/ros2-sitl.rst

We introduced a breaking change after 4.5 to remove the `refs` file which changed the build command. 
I think introducing the tab extension is a nice way to handle the difference between `4.5` and `master`/`4.6`. 
Ideally, ArduPilot wikii would have a version selector at the bottom for the entire site, but this seems like a simpler solution.
FYI @srmainwaring

Add tab structure to document different version run commands for DDS

---

dev/source/docs/building-setup-linux.rst
dev/source/docs/git-clone.rst

Better documents setup on Ubuntu 24.04 and also describes new GitHub requirement for cloning using ssh and the creation of a python virtual environment by the install scripts.

Ubuntu24.04 setup

---

dev/source/docs/building-setup-linux.rst
dev/source/docs/git-clone.rst

Reverts ArduPilot/ardupilot_wiki#6056

Revert "Ubuntu24.04 setup"

---

common/source/docs/common-buzzer.rst
common/source/docs/common-camera-shutter-with-servo.rst
common/source/docs/common-gpios.rst
common/source/docs/common-parachute.rst
common/source/docs/common-relay.rst

Included a GPIO current limit warning and referenced it on associated common articles.

Add GPIO current limit warning(s)

---

blimp/source/index.rst
common/source/docs/common-abbreviations.rst
common/source/docs/common-acknowledgments.rst
common/source/docs/common-appendix.rst
common/source/docs/common-commercial-support.rst
common/source/docs/common-contact-us.rst
common/source/docs/common-donation.rst
common/source/docs/common-downloads_advanced_user_tools.rst
common/source/docs/common-downloads_developer_tools.rst
common/source/docs/common-downloads_firmware.rst
common/source/docs/common-glossary.rst
common/source/docs/common-history-of-ardupilot.rst
common/source/docs/common-makeflyeasy-fighter-hand-throw.rst
common/source/docs/common-makeflyeasy-fighter-vtol.rst
common/source/docs/common-makeflyeasy-striver-mini-hand-throw.rst
common/source/docs/common-makeflyeasy-striver-mini-vtol.rst
common/source/docs/common-partners-program.rst
common/source/docs/common-partners.rst
common/source/docs/common-rtf.rst
common/source/docs/common-stores.rst
common/source/docs/common-team.rst
common/source/docs/common-wiki-editing-archiving.rst
common/source/docs/common-wiki-editing-infra-overview.rst
common/source/docs/common-wiki-editing-quick-edit.rst
common/source/docs/common-wiki-editing-setup.rst
common/source/docs/common-wiki-editing-style-guide.rst
common/source/docs/common-wiki-editing-submitting-changes.rst
common/source/docs/common-wiki_editing_guide.rst

fix infinite recursion that show with newer sphinx versionx
```
writing output... [ 44%] docs/common-makeflyeasy-fighter-hand-throw
Extension error (sphinx.ext.mathjax):
Handler <function install_mathjax at 0x7f848975a840> for event 'html-page-context' threw an exception (exception: maximum recursion depth exceeded)
```
Recusion comes from the hidden toc on makefly rtf pages, there are two that are referencing each other.
Removing one, then trigger a not included into doctree issue, so I move up the hidden doctree to the common rtf page. This now trigger issue with missing include for blimp, thus the massive update on blimp

Common: fix infinite recursion

---

antennatracker/source/conf.py
ardupilot/source/conf.py
blimp/source/conf.py
copter/source/conf.py
dev/source/conf.py
mavproxy/source/conf.py
plane/source/conf.py
planner/source/conf.py
planner2/source/conf.py
rover/source/conf.py

Prevent to copy rst source into the build directory : 
We don't use this for the edit as we forward to github repo directory, so those copied files are useless.

all: don't copy rst sources in build directory

---

update.py

remove subprocess call for building (make things a bit faster)
use 2 cpu for inventory parsing and building. We could probably raise this more build it will collide with the parallel build. 
On rover wiki building it save 30s.

Use direct call to sphinx build for faster build

---

common/source/docs/common-archived-topics.rst
copter/source/docs/flight-modes.rst
copter/source/docs/loading-the-code.rst
copter/source/docs/throw-mode.rst
copter/source/docs/traditional-helicopter-autopilot-assembly-instructions.rst
copter/source/docs/traditional-helicopter-configuring-hardware.rst
copter/source/docs/traditional-helicopter-connecting-apm.rst
copter/source/docs/traditional-helicopter-esc-calibration.rst
copter/source/docs/traditional-helicopter-first-time-setup.rst
copter/source/docs/traditional-helicopter-rc-calibration.rst
copter/source/docs/turtle-mode.rst

This PR reworks the helicopter setup instructions to mimic the other vehicle setup wikis.  It also modifies the flight modes to indicate those not supported by tradheli and adds the inverted flight feature.  
@Hwurzburg -this is still a work in progress.  will add the inverted flight feature tomorrow

tradheli: rework of heli wiki to include flight modes and inverted flight feature

---

dev/source/docs/ros2.rst

* It causes issues with multiple SITL ports and DDS topics overlapping
Follow up to upstream: https://github.com/ArduPilot/ardupilot/pull/28024

Stop testing ROS2 in parallel

---

common/source/docs/common-wiki-editing-setup.rst
docker_update_py.sh

Bash utility script to encapsulate the lengthy `docker run` command for ease of use. Presents a brief menu of convenience options to the user if run without arguments.

dev: add bash utility script for docker

---

common/source/docs/common-wiki-editing-setup.rst

* If you aren't user 1000, this command will build with the wrong user
* Then python can't find any packages and you get a requests import error
Fixes this issue testing another PR:
https://github.com/ArduPilot/ardupilot_wiki/pull/6255#pullrequestreview-2288626098

Common: Fix incorrect user

---

dev/source/docs/ros2-cartographer-slam.rst
dev/source/docs/ros2-gazebo.rst
dev/source/docs/ros2-sitl.rst
dev/source/docs/ros2-waypoint-goal-interface.rst
dev/source/docs/ros2.rst

We want to recommend ardupilot users to create a fresh workspace instead of whatever random code that have in their first ROS2 workspace. Therefore, name it `ardu_ws`. Also, make sure the "src" folder exists before calling VCS.

Dev: Recommend a new ardu_ws instead of ros2_ws

---

.editorconfig

Extremely minor fix with no impact to build functionality or wiki content.
- Newer versions of [neovim](https://neovim.io/) complain about the trailing comment (observed in v0.10.1).
- Moving the comment to the line above the referenced settings fixes the nag warning that must be acknowledged when editing with neovim.
Nag warning that is fixed by this PR:

editorconfig: dot file fix

---

common/source/docs/common-siyi-zr10-gimbal.rst

The Siyi wiki page gets a link to a python script that allows downloading images and videos from the camera

Common: Siyi gets download script link

---

common/source/docs/common-wiki-editing-setup.rst
dev/source/docs/building-setup-linux.rst

* It's needed for both docker environments
* It's linux specific

Fix user/group

---

dev/source/docs/building-setup-linux.rst

add notes on waf build options

---

update.py

This reverts commit 9238723f7a993428032a4820a0a15002d01f4bb4.
This increased parallelisation on the Wiki server which causes it to run out of memory.
There does not seem to be an command-line option to specify the parallelisation  - just remove it.
We are memory-limited in our build, not CPU-limited.
ping @khancyr

Revert "update.py: split procs per tasks and max it out"

---

copter/source/docs/terrain-following.rst

New plugin is MP, supports terrain dat file creation based on MP's terrain data (including DEM files)

Update terrain-following.rst : Mission Planner DAT file creating

---

Sphinxsetup.bat
Sphinxsetup.sh
requirements.txt

DELAY MERGE. There are dependencies that need to be merged before this can go in. See ArduPilot/sphinxcontrib-youtube#4.
This is a change for easier maintenance between the install scripts. Also works as an added bonus to check that the build dependencies are working on the packages ArduPilot maintains.
CI will fail on this PR. I ran this change using my sphinxcontrib-youtube repo and you can see the passing CI change over here.
https://github.com/TunaLobster/ardupilot_wiki/actions/runs/3106686180
https://github.com/TunaLobster/ardupilot_wiki/actions/runs/3106686182

Move python packages to requirements.txt

---

common/source/docs/common-blheli32-passthru.rst
common/source/docs/common-dshot-escs.rst
common/source/docs/common-esc-telemetry.rst
common/source/docs/common-escs-and-motors.rst
common/source/docs/common-powermodule-landingpage.rst

add AM32 ESC protocol to ESC docs

---

dev/source/docs/sitl-with-jsbsim.rst

Discouraged older git protocol, use new one wich is more secure.

Wiki: replace old command

---

common/source/docs/common-esp32-telemetry.rst

Added links to new official Wiki and website for always up-to-date information. Restructured to be more readable.
Added information about the new ESP-NOW mode that allows for significantly more range using a non WiFi-based protocol.

Update ESP32 Telemetry

---

Dockerfile

The requirements file was not copied into the dockerfile.
I switch to bind mount so you don't have to delete the file, and this is better for cache.
```bash
docker build . -t ardupilot_wiki --build-arg USER_UID=$(id -u) --build-arg USER_GID=$(id -g) --progress=plain
```

Fix dockerfile missing requirements

---

.github/workflows/build-docker.yml

Add CI, so we don't break the dockerfile like we did in https://github.com/ArduPilot/ardupilot_wiki/pull/4642 and have to patch it.
https://github.com/ArduPilot/ardupilot_wiki/pull/6341
^ Once that's in, rebase this and the job should pass. The current failing check shows that this PR would have caught the broken dockerfile.

.github: Add CI for dockerfile

---

mavproxy/source/docs/modules/chat.rst

This updates the mavproxy chat module's page to specify that AP 4.6 must be used.  This is in response to a user in the Discord "ai" chat struggling to get the module to work.
This has been tested locally and looks OK to me

modules: chat requirements updated to spec vehicle version

---

mavproxy/source/docs/development/mavdevenvlinux.rst

* Invoking setup.py is deprecated
* https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#what-commands-should-be-used-instead
* This is a precursor to https://github.com/ArduPilot/ardupilot_wiki/pull/6371
* This is what both Peter and Tridge use nowadays

Use pip to install mavproxy

---

common/source/docs/common-temperature-sensor.rst

Written Wiki for PR -https://github.com/ArduPilot/ardupilot/pull/26886 submitted

Added wiki for MLX90614 I2C Sensor

---

common/source/docs/common-lua-scripts.rst

Includes new `readstring` and `writestring` methods, as well as new serial device simulation support.
Completes https://github.com/ArduPilot/ardupilot/pull/27219 .

common-lua-scripts: update serial binding docs

---

common/source/docs/common-auxiliary-functions.rst
common/source/docs/common-mount-targeting.rst
common/source/docs/common-simplebgc-gimbal.rst
common/source/docs/common-tarot-gimbal.rst

https://github.com/ArduPilot/ardupilot/pull/27352
AFTER

mount: Added Retract Mount2

---

dev/source/docs/how-the-team-works.rst
frontend/includes/_topbar.html

I removed the links to the Roadmap from the navigation menu, because they no longer worked.
One could replace it with the [project overviews page](https://github.com/orgs/ArduPilot/projects), but I wasn't sure what is the right choice there.

removed broken roadmap links

---

common/source/docs/common-blheli32-passthru.rst

This fixes a minor typo that breaks the am32 link on the blheli32 page

Common: fix am32 link on blheli page

---

dev/source/docs/ros.rst
dev/source/docs/ros2-interfaces.rst

Start some documentation on the ROS interface on which channels are exposed. This also corrects a few related issues in the wiki docs.
This Wiki is up to date assuming the following PR's all get merged.
* https://github.com/ArduPilot/ardupilot/pull/26911
* https://github.com/ArduPilot/ardupilot/pull/28401
* https://github.com/ArduPilot/ardupilot/pull/28434
* https://github.com/ArduPilot/ardupilot/pull/28441

Ros2 interface

---

common/source/docs/common-am32-escs.rst

This PR makes two changes:
1. add a setup video kindly provided by VimDrones
2. mention that the DroneCAN GUI should be used for setup

Common: AM32 gets setup video from VimDrones

---

copter/source/docs/reference-frames.rst
rover/source/docs/reference-frames.rst

Thanks @tpwrules for noticing this!

Copter/Rover: fix reference frame page's link to RTF page

---

common/source/docs/common-benewake-tf02-lidar.rst
common/source/docs/common-benewake-tfmini-lidar.rst

This fixes some of the links on the two Benewake lidar pages and also removes the out-of-date reference to the version that supports them

Common: benewake link fixes

---

common/source/docs/common-radio-control-calibration.rst

Primarily restores the pitch reversal language introduced in #5943 that accidentally got deleted by #6367 .
Also smooth out the notes about only reversing using the transmitter. Talked with Randy and it should be safe these days; I've done it myself for years. It's also how QGroundControl does it using the auto calibration routine.
There are still some reasons to do it in the transmitter. See also [this discussion](https://github.com/ArduPilot/ardupilot_wiki/pull/5943#discussion_r1594145357).

common: restore pitch reversal language

---

dev/source/docs/mavlink-requesting-data.rst

This adds cut-and-paste-able examples to the MAVLink Interface sections's [requesting data page](https://ardupilot.org/dev/docs/mavlink-requesting-data.html)
I've built the changes locally and tested the examples and it all seems fine

Dev: mavlink interface reg stream rates gets examples

---

dev/source/docs/using-sitl-for-ardupilot-testing.rst

This adds an explanation to the [Using SITL](https://ardupilot.org/dev/docs/using-sitl-for-ardupilot-testing.html) page to explain to developers how they can forward mavlink messages between the vehicles.  This is important for developers who want to test Follow mode and other features.
I've tested both the new command listed and that the page looks OK

Dev: sitl swarming explains how to forward mavlink between vehicles

---

dev/source/docs/mavlink-commands.rst
dev/source/docs/mavlink-nongps-position-estimation.rst

This adds info for developers on how to get non-gps position estimation (aka non-gps navigation) working
I only describe the preferred message, ODOMETRY.  We could add the rest but this is the most important.

Dev: mavlink interface section gets nongps position estimation page

---

common/source/docs/common-ground-resonance.rst

This fixes the bullet points on the ground oscillation page

Copter: fix ground oscillation formatting

---

common/source/docs/common-install-sdcard.rst
common/source/docs/common-loading-firmware-onto-pixhawk.rst

This makes the page describing how to load firmware via the SD card slightly easier to find.  This also includes a drive-by change to the page's title.

Common: loading firmware via SD card made easier to find

---

common/source/docs/common-rtf.rst

These changes can be a big controversial but I've tried to update the page as best I can including:
- Refreshed links for product changes for Event38, CUAV, FlyDragonDroneTech
- Removed duplicate link for MakeFlyEasy Fighter
- removed links for AionRobotics, WattsInnovations
- Alphabetised ordering
Also I added BathyDrone to the non-partners section

Common: update RTF page

---

dev/source/docs/plane-commands-in-guided-mode.rst

Document which guided commands are supported: https://github.com/ArduPilot/ardupilot/blob/5a8bc161709aba97a8b7a6da3ce0ec1a49df2718/ArduPlane/GCS_Mavlink.cpp#L897
The wiki is missing a few.
Guided takeoff is not yet supported.

dev: Document missing plane guided commands

---

update.py

The method was completely misnamed.
Also tidy the invocation of the Sphinx method call (whitespace+ordering changes only)

Tidy diagnostics around copying files to each wiki

---

dev/source/docs/plane-commands-in-guided-mode.rst

Document the following undocumented interfaces:
* SET_POSITION_TARGET_GLOBAL_INT
* SET_POSITION_TARGET_LOCAL_NED
* SET_ATTITUDE_TARGET
The support in Plane is VERY different than copter. It would be a misnomer to say that plane supports the intent of these packets, hence the very specific notes on what's supported and how to use it. As an autonomy developer, this is one of the most frustrating things to have to handle to develop cross-platform autonomy.
As the support for Copter and Plane become more similar, then we can instead move this to a common wiki that's not vehicle-specific.

dev: Document position target and attitude target support in Plane

---

plane/source/docs/auto-trim.rst

As discussed, add notes on what to do if your plane is badly out of trim. Add a note that GPS is required.

Plane: Improve autotrim requirements and trim process

---

dev/source/docs/setting-up-sitl-on-linux.rst

In order for `sim_vehicle.py` to send data to FlightGear, one has to set the `enable-fgview` flag.

Setting up sitl on linux: Fix FlightGear example

---

common/source/docs/common-install-sdcard.rst

This makes a few improvements to the install-firmware-via-sd-card page:
- corrects required firmware version
- fix spelling mistakes
- add demo video
- add info on how to avoid the need to power cycle the board (which could be important for companies attempting to do remote OTA updates)
This has been tested locally and looks OK to me

Common: install-via-sd-card improvements

---

common/source/docs/common-beagle-bone-blue.rst
common/source/docs/common-realsense-depth-camera.rst
common/source/docs/common-vio-tracking-camera.rst
mavproxy/source/docs/getting_started/download_and_installation.rst
rover/source/docs/walking-robots.rst

I have not addressed the use of "sudo" - that requires looking more closely at which sort of installation is being used.
This is also going to be out-of-date vis-a-vis venvs.
But pip3 vs python3 -m pip is an *important* time-saver.

Use python3 -m pip install rather than pip3 install

---

copter/source/docs/traditional-helicopter-autotune.rst

This PR updates the wiki docs for tradheli autotune.  I provides a explanation and video for the new method for tuning the feedforward gains.  It describes the new parameters that limit the rate and acceleration of the requested response.
@Hwurzburg 
Here is a link to the video that needs to be added to the ardupilot youtube channel.  Once it is added then I will put the link in the wiki page.
https://drive.google.com/file/d/1-k_Esz1qT0vUIaW_Aazs_nnTktBkhSY-/view?usp=drive_link

Tradheli: update autotune docs for 4.6 improvements

---

dev/source/docs/mavlink-get-set-params.rst

Continuing my quest to improve documentation for GCS developers.  This adds links to the parameter definition in json format
I've tested this locally and it looks OK.  This is a small change and I'm done updating the PR

Dev: mavlink get-set-param page gets json link

---

Sphinxsetup.sh

this file isn't in the pwd when setting up Vagrant.

SphinxSetup: correct installation from requirements.txt

---

dev/source/docs/adding_simulated_devices.rst
dev/source/docs/mavlink-commands.rst
dev/source/docs/mavlink-precision-landing.rst

This adds a simple page that explains how an external companion computer + camera can send precision landing information to the autopilot.
I've built this locally and it looks OK to me.
The only thing I couldn't figure out is how to add a link directly to the ["Testing Precision Landing"](https://ardupilot.org/dev/docs/adding_simulated_devices.html#testing-precision-landing) section of the "Using SITL" page.  I tried various difference references including all the below but nothing worked
```
:ref:`Testing Precision Landing in SITL <adding_simulated_devices_testing-precision-landing>`
:ref:`Testing Precision Landing in SITL <adding_simulated_devices#testing-precision-landing>`
:ref:`Testing Precision Landing in SITL <adding_simulated_devices_testing_precision_landing>`
:ref:`Testing …
```

Dev: mavlink interface gets precision landing

---

build_parameters.py
update.sh

From what I've gleaned from the logs on the Wiki server, it is possible for build_parameters.py to parse out 0 versions to build from its scanning of the firmware server's directory listing pages.
This leads us to removing the parameters.rst file but not copying in a special "versioning" replacement for it based on the master branch.
So.  Run update.sh with `-e` so that it doesn't just rumble on if there's an error.
Change build_parameters.py to exit with a non-zero exit code if there's ever an error in it.
Require at least one version/commit from each directory listing parsed from the firmware server.
Future enhancements here:
- make build_parameters.py a library, call it from update.py
- stop parsing directory listing of firmware server in build_binaries.py, grab the manifest file …

Stop parameters page in Wiki from just disappearing

---

build_parameters.py
update.sh

We can't generate many of the older files
```
[build_parameters.py][error]: Parameters.rst not found to rename to  parameters-Plane-stable-V3.9.3.rst
[build_parameters.py][error]: Parameters.rst not found to rename to  parameters-Plane-stable-V3.9.4.rst
[build_parameters.py][error]: Parameters.rst not found to rename to  parameters-Plane-stable-V3.9.5.rst
[build_parameters.py][error]: Parameters.rst not found to rename to  parameters-Plane-stable-V3.9.7.rst
[build_parameters.py][error]: Parameters.rst not found to rename to  parameters-Plane-stable-V3.9.8.rst
[build_parameters.py][error]: Parameters.rst not found to rename to  parameters-Plane-stable-V3.9.9.rst
```

Not having an older parameter file is no longer an error

---

dev/source/docs/mavlink-commands.rst
dev/source/docs/mavlink-rcinput.rst

This adds a new RC Input page to the developer MAVLink Interfaces section which will hopefully be useful for GCS developers.  I've tested this locally and it looks OK to me

Dev: mavlink interface gets RC input page

---

dev/source/docs/mavlink-camera.rst

This adds some more examples to the MAVLink Interface camera page's tracking commands.
I've tested the commands and built the changes locally and it looks OK to me
This change comes from testing this flight code PR https://github.com/ArduPilot/ardupilot/pull/29228

Dev: mavlink interface camera gets more tracking examples

---

dev/source/docs/debugging-with-gdb-on-stm32.rst

This fixes up the STM32 debugger hardware list including adding the VimDrones VM Probe.
I've also made a couple of non-critical drive-by changes to wording.
FYI @Huibean

Dev: debugging on stm32 gets vimdrones debugger

---

common/source/docs/common-caddx-gimbal.rst
common/source/docs/common-master-features.rst

Now that we've backported CADDX support to 4.6 we can update the note re versions and remove it from the "upcoming features" section.

Common: caddx version fix

---

common/source/docs/common-ethernet-adapters.rst

This adds the BlueRobotics ethernet switch to our ethernet adapters page

Common: ethernet-adapters page gets bluerobotics switch

---

common/source/docs/common-ethernet-adapters.rst

This updates the link for the CubePilot 8-port ethernet switch to point back to the official documentation (which has just been created)

Common: ethernet adapters link to CubePilot switch

---

dev/source/index.rst

It seems DIY Drones have changed their site structure since the original link was generated.

dev: index.rst: fix broken link to MAVLink tutorial

---

common/source/docs/common-dronecan-serial.rst

Correct typo in common-dronecan-serial.rst
DrooneCAN -> DroneCAN

Correct typo in common-dronecan-serial.rst

---

dev/source/docs/ros2-pi.rst

We were missing a space so the list wasn't rendered correctly.

dev: Fix bullet list rendering

---

dev/source/docs/ros2-gazebo.rst

Following the discussion in https://github.com/ArduPilot/ardupilot_ros/issues/32, this update improves the "ROS 2 with Gazebo" setup instructions by adding Gazebo sources to `rosdep`.
The current approach allows users to bypass `rosdep` errors using the `-r` flag, which can later lead to build failures. By instructing users to add Gazebo sources, rosdep will properly install the required `gz` libraries.

Added instructions to use Gazebo sources with `rosdep`

---

dev/source/docs/mavlink-get-set-flightmode.rst

This resolves issue https://github.com/ArduPilot/ardupilot_wiki/issues/6669 by adding explanations for other MAV_CMDs that can be used to set the flight mode
I've built this locally and tested the commands in SITL and it all seems OK to me

Dev: add alternative set-flight-mode command

---

dev/source/docs/copter-commands-in-guided-mode.rst
dev/source/docs/plane-commands-in-guided-mode.rst

This is a follow up to https://github.com/ArduPilot/ardupilot_wiki/pull/6671
This further clarifies what the MAV_CMD_**NAV_LOITER_UNLIM**, MAV_CMD_NAV_**RETURN_TO_LAUNCH** and MAV_CMD_**NAV_LAND** mav commands do when executed while Copter and/or Plane are in Guided mode which is to actually change the flight mode.
Previously these lines referred the user to the corresponding mission commands which made one community developer at least think that the behaviour would be Loiter-within-Guided and they were thus surprised when the pilot's throttle was suddenly consumed and the vehicle descended quickly.
I haven't added anything to the Rover pages because they simply don't mention these commands.  The description for these commands is there (for all vehicles) in the Get and Set FlightMode page …

Dev: copter and plane commands for loiter, rtl, land

---

common/source/docs/common-contact-us.rst
dev/source/docs/submitting-patches-back-to-master.rst

This gives some additional advice especially for "community developers" (as I call them at least) on how to get their PRs merged in case they get stuck.
As a drive-by change I've also add the dev call times to our Contacts page

Dev: submitting-patches-back-to-master gets advice for stuck PRs

---

common/source/docs/common-tuning.rst

This adds a link to Chris Rosser's ArduPilot tuning video playlist
I originally wanted to add the link so that a preview was displayed and users watch the video within the AP web site but I couldn't figure out how to make that work

Copter: add links to ChrisR's setup videos

---

common/source/docs/common-holybro-ph5x.rst

This adds a warning to the Holybro Pixhawk 5x to warn users that AP doesn't support networking on F7 boards (including this board)

Common: holybro pixhawk 5x ethernet warning

---

sub/source/index.rst

I wanted this to be [anchor-based](https://ardupilot.org/ardupilot/docs/common-wiki-editing-style-guide.html#internal-links), but that seemingly doesn't work for the sidebar, so I followed the approach used in the `ardupilot` wiki for linking to the other wikis (which is just a direct site URL).
This is a Sub-only change (@Williangalvani).

Sub: add sidebar link to MAVLink support page

---

common/source/docs/common-appendix.rst
common/source/docs/common-makeflyeasy-fighter-hand-throw.rst
common/source/docs/common-makeflyeasy-fighter-vtol.rst
common/source/docs/common-makeflyeasy-striver-mini-hand-throw.rst
common/source/docs/common-makeflyeasy-striver-mini-vtol.rst
common/source/docs/common-rtf.rst
sub/source/index.rst

Only a subset of the listed vehicles are relevant to each vehicle type.
This PR
- splits those out (removing the unwanted ones from the copy action), while also
- removing blimp entirely (it has no pre-made purchaseable vehicles), and
- adding Sub as a target
- ~cannot be merged before #6649 - hence draft PR for now (will need to be rebased over master once that's merged in)~

common: ready-to-fly: avoid unwanted duplication

---

dev/source/docs/mavlink-commands.rst
dev/source/index.rst
mavproxy/source/docs/getting_started/faq.rst

- Change a bunch of cross-wiki links to `:ref:` style, so they can be tracked if/when they get broken
- Update remaining `ardusub.com` references to the new ArduPilot wiki site
- Fix some miscellaneous broken links in the process

mavproxy/dev: update outdated and broken links

---

dev/source/docs/building-setup-mac.rst

This pull request includes a documentation update for the MacOS build environment setup guide. The most important change is the addition of instructions on how to use the pre-built script.
Documentation update:
* [`dev/source/docs/building-setup-mac.rst`](diffhunk://#diff-3d1dc20adf6b020b50313608b6d8ab50dbe5577cf5e129d42c3c82bd789438c5L13-R18): Added a section with instructions on how to use the pre-built script located at `/ardupilot/Tools/environment_install/install-prereqs-mac.sh`.

Common: update macOS build setup documentation with usage instructions for prebuilt script

---

dev/source/docs/mavlink-mission-upload-download.rst

This resolves issue https://github.com/ArduPilot/ardupilot_wiki/issues/6670 by adding a section to our mavlink interface section's Mission page to explain how to pause/resume a mission
I've tested the commands listed and also built locally and it seems OK to me

Dev: mavlink interface mission page gets pause mission explanation

---

dev/source/docs/using-sitl-for-ardupilot-testing.rst

This pull request includes a minor documentation change to correct the formatting of a code identifier in the `using-sitl-for-ardupilot-testing.rst` file.
* Corrected the formatting of the `sim_vehicle.py` script name by changing triple backticks to double backticks in the `using-sitl-for-ardupilot-testing.rst` file.

Common: fix formatting in SITL documentation for `sim_vehicle.py` script

---

common/source/docs/common-master-features.rst
common/source/docs/common-rangefinder-hexsoon-24g.rst
common/source/docs/common-rangefinder-hexsoon-radar.rst
common/source/docs/common-rangefinder-landingpage.rst

The Hexsoon radar have been included in AP-4.6.0-beta5 so we can move them from the "upcoming features" page to the standard rangefinder landing pages
I've tested these changes locally and they look OK to me

Common: promote hexsoon radar to rangefinder landing page

---

common/source/docs/common-cameras-and-gimbals.rst
common/source/docs/common-siyi-zr10-gimbal.rst

The Siyi page's download page link has changed so I've taken the opportunity to add download links per product.  This will hopefully help users more quickly find the Assistant (although this doesn't depend upon the product) and the user manual and latest firmware.
Thanks to @andyp1per for finding this issue!

Siyi: add product specific download links

---

copter/source/docs/indoor-flying.rst

This resolves issue https://github.com/ArduPilot/ardupilot_wiki/issues/6760 by clarifying the use-case that applies for the "Indoor Flight Guidelines" wiki page
I've also added a few links and cleared up some wording and corrected how the GPS should be disabled.  I don't think setting AHRS_GPS_USE was correct because (at least according to the parameter descriptions this only applies to DCM).  I think the two possible ways to disable the GPS are:
1. set EK3_SRC1_POSXY, EK3_SRC1_VELXY = 0
2. set GPS1_TYPE = 0
I've specified the 2nd because it's easier and I've also testesd in SITL that I can arm and takeoff in stabilize mode successfully

Copter: clarify indoor flight guidelines usecase

---

frontend/index.html

Seems to me to be more appropriate placement of description of project.

move description of project above the community content on ardupilot.org

---

common/source/docs/common-benewake-tf02-lidar.rst
common/source/docs/common-rangefinder-landingpage.rst

This includes a few small fixes to the Benewake rangefinder TF02/TF03/TFLuna pages
- removed instructions on very old version
- simplify rngfnd1-min to remove mention of an unrelated model
- unify naming of TF02-Pro
- fix broken link for DroneCAN model

Common: Benewake TF02/TF03/TFLuna fixes

---

common/source/docs/common-am32-escs.rst

This adds a link to the new [VimDrones 50Amp ESC](https://dev.vimdrones.com/products/vimdrones_esc_s50/) to the AM32 page

Common: add VimDrones S50 ESC to AM32 page

---

plane/source/docs/automatic-tuning-with-autotune.rst

According to Tridge, autotune was not designed with rudder only planes in mind. My experience has been very poor.
https://discuss.ardupilot.org/t/ardusoar-2025/128317/11
Although initially impressed with autotune, I found a few ways the controller breaks down with that tune. The P gain is far too low from autotune. I have tried a few different autotune levels, none are acceptable.

Plane: Recommend not using autotune roll for RUDDER_ONLY planes

---

common/source/docs/common-ethernet-adapters.rst
common/source/docs/common-network.rst
common/source/docs/common-optional-hardware.rst

This PR removes some duplicate PPP setup instructions:
- removed all PPP setup from the bottom of the Ethernet Adapters page.  This info is already present on the Dronenet and CubeNodeETH pages not to mention the Ethernet/Network Setup page.
- Ethernet/Network Setup page loses some info re PPP setup at the top of the page and instead refers the reader to the existing "PPP Configuration" section lower down on the page.  This "PPP Configuration" section is slightly reworded to make it consistent with the "DroneNet" and "CubeNodeETH" pages but mostly I've just added a picture of the custom build server page to highlight the exact option that users must select
I've also included a small fix to the Ethernet Adapters page to point some links to our internal pages instead of the manufacturer's …

Common: remove some duplicate PPP setup instructions

---

copter/source/docs/ArduCopter_MAVLink_Messages.rst
plane/source/docs/ArduPlane_MAVLink_Messages.rst
rover/source/docs/Rover_MAVLink_Messages.rst
sub/source/docs/ArduSub_MAVLink_Messages.rst

I added the corresponding numbers to the supported MAVLINK messages (https://ardupilot.org/plane/docs/ArduPlane_MAVLink_Messages.html#arduplane-mavlink-messages) to make it easier to e.g. generate the message_interval.txt files.
I used a python script to get the numbers in an automated way. 
I made several random checks and i was not able to find mistakes.
Since it was automated i did it for all four ardupilot branches.

Added mavlink numbers to supported command overview 

---

common/source/docs/common-siyi-zr10-gimbal.rst

This fixes a few of the link at the very top of the Siyi page.
ZT6 is no longer for sale so we're using their product page which is a little different than the store page

Common: update siyi product links

---

Sphinxsetup.sh

downloaded script doesn't support Python3.8 any more, and various of our processes still use it

Sphinxsetup.py: install pip using apt

---

common/source/docs/common-xfrobot-gimbal.rst

This adds a short "Downloading Images and Video" section to the XFRobot page similar to what we have on the Siyi camera gimbal page.  While it's unlikely that most users will use this to download images and videos from the camera gimbal over ethernet surely some "pro" users will and it will also be helpful for companion computer developers looking to setup automatic image and video downloads

Common: XFRobot gets download script link

---

common/source/docs/common-rangefinder-landingpage.rst

This fixes the Nanoradar MR72s name on the landing page.  This was at the request of Nanoradar.

Common: fix rangefinder landing page link for Nanoradar MR72

---

copter/source/docs/vibration-failsafe.rst

This updates the EKF fields to look at now that EKF3 is the default (the old values were for the EKF2)
I've also removed mention of a very old version of AP.
The vibration failsafe came up in [this 4.6 beta testing discussion](https://discuss.ardupilot.org/t/jumps-with-gaining-altitude-when-changed-mode-from-rtl-to-loiter/133889)
I've built this locally and it looks OK to me.

Copter: update vibration failsafe for EKF3

---

common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst

Parameter 2 can be used to specify which fence should be enabled or disabled.
This detail was not documented, so I will add it.

DO_FENCE_ENABLE: Add an explanation for parameter 2 in the command

---

common/source/docs/common-ark-v6x-overview.rst

Removes the PX4 info about /dev/tty*  instead to have the ArduPilot Serial Number for each port that is used in the parameter tree
@AlexKlimaj

Docs: ARKV6X Update Overview with Serial Parameter Number Ordering

---

dev/source/docs/adding_simulated_devices.rst

This updates the [adding-simulated-devices](https://ardupilot.org/dev/docs/adding_simulated_devices.html) page to include the LD06
This simulator was added as part of PR: https://github.com/ArduPilot/ardupilot/pull/27045

dev: adding-sim-devices gets ld06 proximity sensor

---

plane/source/docs/new-roll-and-pitch-tuning.rst

Plane: Fix plot bin log for pitch axis plotting

---

dev/source/docs/ros2-pi.rst

Add a minimal example showing how to stand up a cross compile workflow for the Micro ROS Agent on a Raspberry Pi.
This does it without any custom scripts because it's more intended as instruction.
Companies using ROS 2 likely have their own mechanicsm for deployment (docker images, debian packages, etc), however this is a good minimal start to cross compile and launch an application on a headless computer. I start with just the MicroROS agent. We can add python and C++ nodes later.
Flew it on my plane, verified DDS connected via GCS messages each flight. 
Use PPP: https://discuss.ardupilot.org/t/guide-for-using-dds-over-ppp-with-a-raspberry-pi-4-companion-computer/126128/3

dev: Add ROS 2 deployment to Pi with docker and systemd

---

common/source/docs/common-cubepilot-cubenodeeth.rst

This updates the firmware links for the CubeNode-ETH page.
This is required because we've recently released AP_Periph ver 1.8 and the device was renamed since the previous stable release
FYI @bugobliterator

Common: CubeNode-ETH firmware links updated

---

common/source/docs/common-am32-escs.rst

This adds a link to Pogo's DroneCAN ESCs as [requested here](https://github.com/am32-firmware/AM32/issues/175#issuecomment-3007555351) on the AM32 site.

Common: add Pogo DroneCAN AM32 ESCs

---

common/source/docs/common-stores.rst

This adds VimDrones (run by Huibean) to our list of stores (VimDrones is a Partner)
BTW, 3DXR's position in the list was not in alphabetical order, it's unclear whether "3" means it should be at the top or the bottom.  I've put it at the bottom but I could move it to the top if people prefer.

Common: add vimdrones to stores list

---

plane/source/docs/fly-by-wire-low-altitude-limit.rst

As per https://github.com/ArduPilot/ardupilot/commit/8151647e0465b5fe8b82b5f352f0f22b96025d33 the parameter is set in meters, I think that relates to 4.5.0 rescales of parameters away from centimeters. [The code](https://github.com/ArduPilot/ardupilot/blob/05dbacebd24e3354469a4c908fe8461d20ee1813/ArduPlane/altitude.cpp#L406) clearly expects meters in parameter too.

Cruise alf floor units fix

---

dev/source/docs/copter-adding-custom-controller.rst

This PR adds a missing step for the **Custom Controller** module. The step was copied from [README](https://github.com/ArduPilot/ardupilot/blob/Copter-4.6.0/libraries/AC_CustomControl/README.md#how-to-add-new-custom-controller) file.
This step was inserted between other existing steps, so I modified them in order to keep the sequence correct.

Copter: Added missing step to add custom controller (from README)

---

common/source/docs/common-radio-control-calibration.rst

Reading through the Radio Calibration page, I noticed that Mode 3 and 4 are missing.
I fly Mode 3.

Update common-radio-control-calibration.rst for Mode 3 and 4

---

common/source/docs/common-gps-ublox-firmware-update.rst

Update uBlox  link + version number.
Remove discussion regarding setting up constellations, as GPS*_GNSS_MODE has done that since around the time AP 4.0 was released (it dates back quite some time).

Common/GPS: update F9P firmware instructions

---

common/source/docs/common-network.rst
dev/source/docs/ros2-over-ethernet.rst
dev/source/docs/ros2-pi.rst

This adds in 2 things:
* Method to run a ppp link from a Linux-based computer (thanks to https://discuss.ardupilot.org/t/guide-for-using-dds-over-ppp-with-a-raspberry-pi-4-companion-computer/126128)
* Add notes about DDS (ROS2) not being in standard ArduPilot builds (see https://github.com/ArduPilot/ardupilot/pull/30835 for background)

Add notes for PPP and DDS

---

dev/source/docs/ros2-gazebo.rst

This pull request addresses write permission issues in the documentation by adding sudo to necessary commands in the ros2-gazebo.rst file. Specifically, it modifies commands related to adding Gazebo APT sources and updating Gazebo sources in rosdep to ensure they can be executed without permission errors. The changes include:
Added sudo to tee command for writing to /etc/apt/sources.list.d/gazebo-stable.list.
Added sudo to wget command for writing to /etc/ros/rosdep/sources.list.d/00-gazebo.list.
These changes ensure that users can follow the documentation without encountering write permission issues.

Update ros2-gazebo.rst to include sudo for directory write permissions

---

rover/source/docs/arming-your-rover.rst

Fix typos for ArduRover Arming doc
Parameter key should be `RCX_OPTION` (not `RC_XOPTION`)

Fix RCX_OPTION typos

---

dev/source/docs/code-overview-adding-a-new-mavlink-message.rst

The previous link to GCS_MAVLink.cpp in [Learning the Ardupilot Codebase/Adding a new MAVLink Message](https://ardupilot.org/dev/docs/code-overview-adding-a-new-mavlink-message.html) was incorrect. Updated it to point to GCS_MAVLink_Copter.cpp to fix the broken link and clarify that this file is specific to ArduCopter.

dev: fix broken link to GCS_MAVLink.cpp

---

dev/source/docs/companion-computer-blueos-install.rst
dev/source/docs/companion-computer-blueos-live-video.rst

This fixes a mismatch between the comment (which mentions the Siyi A8 camera) and the actual MediaMTX setting (which is for the XFRobot)
I've also snuck in a change to the BlueOS installation instructions after recently re-isntalling BlueOS on one of my boards.
I'm all done updating this PR now and I've tested this locally and it looks OK to me

Dev: small fix to BlueOS live video setup
